<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skip to Main Content_t_Button_navControl</name>
   <tag></tag>
   <elementGuidId>2a826990-fe74-4397-8447-52c7a7bea6a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#t_Button_navControl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='t_Button_navControl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>451f81e8-9df4-4cfe-9c17-2d3c0b878736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--icon t-Button--header t-Button--headerTree</value>
      <webElementGuid>b39611ee-edd4-4dd4-a30d-c96927e7cb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>cc1bdeb9-3140-4037-89e2-6f3d0a4d6086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>dc19bda4-a470-4d0e-a5a5-a91cbb1c4dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>t_Button_navControl</value>
      <webElementGuid>8a932419-f515-40fe-9e1f-873277e6cad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c058d78b-ba59-4ef6-910d-bc6397dcbad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>t_TreeNav</value>
      <webElementGuid>fcf57a4c-bfc9-47a9-b630-a9e7950776a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c242fcdd-6359-4e70-a394-6f4fb951ca93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_Button_navControl&quot;)</value>
      <webElementGuid>a62d1a52-4c43-4081-9bb4-f8bff21d1133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='t_Button_navControl']</value>
      <webElementGuid>93e64867-dce4-49b3-a4e4-c32f10f8333e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='t_Header']/div/div/button</value>
      <webElementGuid>519ae138-c6c4-4635-baf4-70ff19ad825c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::button[1]</value>
      <webElementGuid>040f9deb-54c2-414e-b490-d25cbfef327c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MV School Registration'])[2]/preceding::button[1]</value>
      <webElementGuid>55524dad-bd78-4440-bcc4-5736ef5d1ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Install App'])[1]/preceding::button[1]</value>
      <webElementGuid>9ee90fed-be4f-4e6a-8a0a-7a2ba5778812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ae2a1e91-3e9f-4ff7-9467-1807567ccd49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Main Navigation' and @id = 't_Button_navControl' and @type = 'button']</value>
      <webElementGuid>9b0bbd99-b019-477c-9205-9365c4a3ceaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
