<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Report</name>
   <tag></tag>
   <elementGuidId>b04a8d72-1009-4d2e-9fd2-9bc4105aed0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a-TreeView-content.is-hover > a.a-TreeView-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='t_TreeNav_5']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>304266ab-0619-4e54-856c-4b19e7c0e5ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2b46545e-94d1-4fb3-8e57-c545623f7070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>deb57c07-e23a-4505-a513-1507685f6c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-label</value>
      <webElementGuid>1a8baae4-19af-4cc3-83d3-3a0346e1a7cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ords/r/mulyavardhan/mv-school-registration/users-list?session=111361847316227</value>
      <webElementGuid>f11451f7-40d6-433b-96f4-c61b43d9f26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>56c0cd7d-850d-47c3-8729-b00a5f7f29d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>afda7157-2e46-4e8f-b7e6-8f2c41347c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>User Report</value>
      <webElementGuid>ba5d508e-dbeb-4547-8304-89cfff7cddd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_5&quot;)/div[@class=&quot;a-TreeView-content is-hover&quot;]/a[@class=&quot;a-TreeView-label&quot;]</value>
      <webElementGuid>8c8e2f17-a673-4c23-b567-701f7c89cf5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_5']/div[2]/a</value>
      <webElementGuid>f6164772-6644-4db4-ba87-8aee6e9c06e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'User Report')]</value>
      <webElementGuid>1abc18a1-2742-4e96-8617-03af5cc5aea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School Followup'])[2]/following::a[1]</value>
      <webElementGuid>5578f8e3-cb5b-46b4-91dd-f7745cd62348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Followup Topic'])[1]/following::a[2]</value>
      <webElementGuid>308f5f4a-0f42-4060-93cc-c4146fecd980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::a[1]</value>
      <webElementGuid>987feb8c-58f1-4ab7-995c-c568be2ab886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/preceding::a[1]</value>
      <webElementGuid>50243f85-cb26-4b07-9da3-a6f0c85b84c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='User Report']/parent::*</value>
      <webElementGuid>72647694-2ee4-461e-bedd-097f85ba3518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ords/r/mulyavardhan/mv-school-registration/users-list?session=111361847316227')]</value>
      <webElementGuid>c4c88a4a-54d2-4b4e-824d-0c1832373363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div[2]/a</value>
      <webElementGuid>4534b919-91dc-4cc3-aded-b48371434390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ords/r/mulyavardhan/mv-school-registration/users-list?session=111361847316227' and (text() = 'User Report' or . = 'User Report')]</value>
      <webElementGuid>a0bb03e3-de6e-4722-9d2b-f27cbc4cd297</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
