<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Reset</name>
   <tag></tag>
   <elementGuidId>ebd4f770-6ef3-41b9-aaf8-afb6a7a4dda4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B48555332334758141 > span.t-Button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B48555332334758141']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f892d526-0cb9-427d-b3df-0e68ecf1a2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button-label</value>
      <webElementGuid>eb3ac1f8-01ab-4d9c-841d-27dba8639228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>b339ed6e-e535-4f1f-b736-bcc8dc16cc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B48555332334758141&quot;)/span[@class=&quot;t-Button-label&quot;]</value>
      <webElementGuid>ca2ca7aa-a481-412f-81de-7863b2b65200</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='B48555332334758141']/span</value>
      <webElementGuid>fe88885c-d47d-4420-afcb-85c6e6d4209d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trust Name'])[1]/following::span[3]</value>
      <webElementGuid>40fbc079-3ffe-4298-b2ea-cde58d5edf35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade'])[1]/following::span[5]</value>
      <webElementGuid>84c4a1a3-d259-4961-bd39-b13cb4344754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Count'])[1]/preceding::span[1]</value>
      <webElementGuid>e41d055c-eb07-407c-b506-8ac3d2a0903c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::span[4]</value>
      <webElementGuid>24bc5060-23b6-4f91-a4c3-c618ce5a3edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reset']/parent::*</value>
      <webElementGuid>24decc65-34bb-40ba-8991-e41fa2d118ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>5c607e29-9f7d-4bd1-a090-f4a79d42b448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Reset' or . = 'Reset')]</value>
      <webElementGuid>a2f466fe-d762-49be-8b29-aba14ceda92c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
