<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Grade_a-Icon icon-popup-lov-under</name>
   <tag></tag>
   <elementGuidId>dff51430-5f77-424b-9769-99b7735c9fea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P10_GRADE_lov_btn > span.a-Icon.icon-popup-lov-under</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P10_GRADE_lov_btn']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0a7029cc-331c-4263-bd98-27db967ace2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Icon icon-popup-lov-under</value>
      <webElementGuid>e88e9b66-ea5f-4015-acad-82be4eeb068c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P10_GRADE_lov_btn&quot;)/span[@class=&quot;a-Icon icon-popup-lov-under&quot;]</value>
      <webElementGuid>ee993a17-f5a9-4ecd-9e12-5ba098da669b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='P10_GRADE_lov_btn']/span</value>
      <webElementGuid>e4836aa0-d64b-4a80-8b1c-f28cb9988f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/button/span</value>
      <webElementGuid>63528a2b-e0a5-48cc-8fce-e2bf802dffd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
