<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Skip to Main Content_t-Header-controlsIcon</name>
   <tag></tag>
   <elementGuidId>8da7d841-ee34-4c1e-b26d-ab4e91ebe77e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='t_Button_navControl']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.t-Header-controlsIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a527ddd8-2463-43bc-8aea-5e6a95f9ff48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Header-controlsIcon</value>
      <webElementGuid>c065eb40-e592-4589-bca7-1c196c8aeb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>50f5da89-8978-458c-956c-16eba4246cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_Button_navControl&quot;)/span[@class=&quot;t-Header-controlsIcon&quot;]</value>
      <webElementGuid>2f1b4bf3-7c07-41d7-a919-54e6fd5e30d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='t_Button_navControl']/span</value>
      <webElementGuid>0a44d109-7e2a-4803-bdc5-a4b18aa267a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>ad62956e-6f82-4018-8bf3-3228dd223c61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
