<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Followup Topic</name>
   <tag></tag>
   <elementGuidId>c3eeeacd-d8e9-44dc-a02d-243201cf9ba1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a-TreeView-content.is-hover > a.a-TreeView-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='t_TreeNav_3']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c3b2dcda-bffd-41b8-af46-cb9f0dd9f48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c2d73280-230a-4de9-9651-5fb6add2344d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>1b701240-48a9-4722-bba1-7d0fd659d5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-label</value>
      <webElementGuid>ec611be7-120f-4c69-a49f-35a769abfc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:apex.theme42.dialog('\u002Fords\u002Fr\u002Fmulyavardhan\u002Fmv-school-registration\u002Ftopic-master?session=110410397002070\u0026dialogCs=VWm_hvH0VE3v8_W06LiFuf36TF7ZduWVpGRbFHszwW1j7tuDBqg1SuVwDzHdd7LF-CIFErDmYKiKepi4wSQuCA',{title:'Topic Master',h:'auto',w:'800',mxw:'960',modal:true,dialog:null,dlgCls:'t-Dialog-page--standard '+''},'','#t_Body')</value>
      <webElementGuid>f878eb55-2db0-4aff-b920-3240897a6506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4558135b-332c-4524-afe7-e95c0607763c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>54b54bce-5f22-43eb-a8a5-8a95bc0d9fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Followup Topic</value>
      <webElementGuid>7f1a1a16-932d-4602-97c7-b7d0d858d90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_3&quot;)/div[@class=&quot;a-TreeView-content is-hover&quot;]/a[@class=&quot;a-TreeView-label&quot;]</value>
      <webElementGuid>254472e3-c94e-4215-8f59-c2d3960f1226</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_3']/div[2]/a</value>
      <webElementGuid>279153a4-4374-4dbb-80b4-c3ba52c09ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Followup Topic')]</value>
      <webElementGuid>172b1d22-f09d-49cc-bd36-7e80d7d1c00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School Report'])[1]/following::a[1]</value>
      <webElementGuid>0021e0e0-7828-4960-868c-daf9f5b2bc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School Registration Form'])[1]/following::a[2]</value>
      <webElementGuid>ba1d86ca-c930-4bee-9111-4618ef6bb860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='School Followup'])[1]/preceding::a[1]</value>
      <webElementGuid>ab99b853-5aad-4bda-9452-bc13d67b4880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Report'])[1]/preceding::a[2]</value>
      <webElementGuid>00b42583-1f9e-4f41-ba8f-0e534096eea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Followup Topic']/parent::*</value>
      <webElementGuid>1d09c06c-30f4-4479-9062-b35a3848d539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:apex.theme42.dialog('\u002Fords\u002Fr\u002Fmulyavardhan\u002Fmv-school-registration\u002Ftopic-master?session=110410397002070\u0026dialogCs=VWm_hvH0VE3v8_W06LiFuf36TF7ZduWVpGRbFHszwW1j7tuDBqg1SuVwDzHdd7LF-CIFErDmYKiKepi4wSQuCA',{title:'Topic Master',h:'auto',w:'800',mxw:'960',modal:true,dialog:null,dlgCls:'t-Dialog-page--standard '+''},'','#t_Body')&quot;)]</value>
      <webElementGuid>2cb245f0-173d-425d-9e5f-0490675e0316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/a</value>
      <webElementGuid>f29e1514-816d-41c8-a728-5456801e7408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:apex.theme42.dialog(&quot; , &quot;'&quot; , &quot;\u002Fords\u002Fr\u002Fmulyavardhan\u002Fmv-school-registration\u002Ftopic-master?session=110410397002070\u0026dialogCs=VWm_hvH0VE3v8_W06LiFuf36TF7ZduWVpGRbFHszwW1j7tuDBqg1SuVwDzHdd7LF-CIFErDmYKiKepi4wSQuCA&quot; , &quot;'&quot; , &quot;,{title:&quot; , &quot;'&quot; , &quot;Topic Master&quot; , &quot;'&quot; , &quot;,h:&quot; , &quot;'&quot; , &quot;auto&quot; , &quot;'&quot; , &quot;,w:&quot; , &quot;'&quot; , &quot;800&quot; , &quot;'&quot; , &quot;,mxw:&quot; , &quot;'&quot; , &quot;960&quot; , &quot;'&quot; , &quot;,modal:true,dialog:null,dlgCls:&quot; , &quot;'&quot; , &quot;t-Dialog-page--standard &quot; , &quot;'&quot; , &quot;+&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;},&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;#t_Body&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Add Followup Topic' or . = 'Add Followup Topic')]</value>
      <webElementGuid>c0f70cf2-8e4b-45b1-9f1d-2a8a3ea2e7fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
