<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skip to Main Content_t_Button_navControl</name>
   <tag></tag>
   <elementGuidId>9f0d0453-672e-4d2d-8141-bdebb3e0862b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#t_Button_navControl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='t_Button_navControl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b45b131e-8e00-4f45-b5c0-113d60736fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--icon t-Button--header t-Button--headerTree</value>
      <webElementGuid>60c1293e-25b9-49ab-a17a-4753f71ce439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>607943e3-28b5-413b-bb04-6051c1687fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>b81e794d-ffb7-40d0-a112-c26f56d3fde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>t_Button_navControl</value>
      <webElementGuid>211a66e0-222e-4c46-b3ae-be982c71a2d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f980cd16-30cf-4b00-9de2-44cfd51979e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>t_TreeNav</value>
      <webElementGuid>3e74bc7f-ffee-4a3f-b550-fe8514e99e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5e322fb3-0851-4318-94bf-0235ae3e13a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_Button_navControl&quot;)</value>
      <webElementGuid>6397b22a-97f5-46c1-8cf1-2934525ae6c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='t_Button_navControl']</value>
      <webElementGuid>4395a0bf-aaec-46c7-bdf7-04b0f4782d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='t_Header']/div/div/button</value>
      <webElementGuid>c30df014-767b-40f5-944f-97a3b4b314c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::button[1]</value>
      <webElementGuid>5dbf1416-1f1b-4d57-822d-5911ffb5d1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MV School Registration'])[2]/preceding::button[1]</value>
      <webElementGuid>e335f3e6-b21c-47d0-a929-fe2c5accd798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Install App'])[1]/preceding::button[1]</value>
      <webElementGuid>14b01366-9f72-454b-8a92-9f5ecd059cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>ec940d92-6e65-436a-a0da-141e8eb53872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Main Navigation' and @id = 't_Button_navControl' and @type = 'button']</value>
      <webElementGuid>9a7b1733-9dc5-4201-821e-2241a0cb879c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
