<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Save</name>
   <tag></tag>
   <elementGuidId>97b4a14b-e5df-41fd-8ab8-37ae725fd040</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B48392503930122040</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B48392503930122040']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4fee0608-6095-46c3-8867-97286961cefe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>apex.submit({request:'Save',validate:true});</value>
      <webElementGuid>aafa291b-788f-4a70-bc6c-83ebb3e53cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--warning</value>
      <webElementGuid>f9ae212d-2777-41e6-acfa-b74c62950338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fac6a167-2ee9-43aa-b668-a748d700e910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B48392503930122040</value>
      <webElementGuid>8cc0fd05-1e07-4658-a8fe-681d485c8a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>4678f49b-0e86-4889-9f3e-8b920f4297e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B48392503930122040&quot;)</value>
      <webElementGuid>47be73b7-7cf0-4e51-987d-1f596ebd5684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add Follow-Up Topics(MV School)/Page_MV School Registration/iframe</value>
      <webElementGuid>55bfac3a-2dbb-4f46-ab22-caca15a8b116</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='B48392503930122040']</value>
      <webElementGuid>b6e1aef1-fe4c-4bf1-a5e5-75b1676971b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R251128408925308249']/div[2]/div/div[2]/button</value>
      <webElementGuid>e29d145e-a26b-4449-aee9-9297b9fcbae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mulyavardhan'])[1]/following::button[1]</value>
      <webElementGuid>5c9520c4-18c5-49fa-8f1a-747932a79fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project : -'])[1]/following::button[1]</value>
      <webElementGuid>0f5f268a-b963-4121-9fc0-63d62509af06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::button[2]</value>
      <webElementGuid>75db1205-4d24-445f-83fc-4c04f71ecf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fc7d00f8-aae0-4bbd-8375-011c5505b4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'B48392503930122040' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>7404e8b8-89a9-4702-bfb7-206b59ba3f33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
