<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>2d7d5eaf-bb4b-4086-9840-1dc25c2577b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Topic Master&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a7ad482f-9654-412f-a2dc-86e6750f1020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/mulyavardhan/mv-school-registration/topic-master?session=110410397002070&amp;dialogCs=VWm_hvH0VE3v8_W06LiFuf36TF7ZduWVpGRbFHszwW1j7tuDBqg1SuVwDzHdd7LF-CIFErDmYKiKepi4wSQuCA</value>
      <webElementGuid>a1dc61da-2404-4340-a886-4e933d7ef98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Topic Master</value>
      <webElementGuid>7c74b401-d1e3-4c86-a642-f393b181bcee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f98009cd-229f-4824-a3f1-3a96101ac6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>506b30d3-36d0-4c83-8405-cd28c5ece09b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>89a161be-e470-4037-a9ee-03859a69ab9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>084a4bbe-2d33-4569-8b1e-afefe9c9b372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>ee95e53c-1fff-467e-826c-5f08ba6ed629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3b8a09b6-5a8f-4821-8c45-18ca5a2b6de5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/mulyavardhan/mv-school-registration/topic-master?session=110410397002070&amp;dialogCs=VWm_hvH0VE3v8_W06LiFuf36TF7ZduWVpGRbFHszwW1j7tuDBqg1SuVwDzHdd7LF-CIFErDmYKiKepi4wSQuCA' and @title = 'Topic Master']</value>
      <webElementGuid>11e579d7-2c3a-412e-ad45-b43ff5b4f5b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
