<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>83e70999-d50f-4447-9b6e-151463158ea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add/Edit Meeting Docs&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5e980b94-28ad-4db9-b546-583bed4b4158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/add-edit-meeting-docs?p331_meeting_id=162&amp;clear=331&amp;session=5015463629664&amp;cs=1cYw0om3KDJ3GMvgj31E9vVhdTYHgY4QtIJrUubapk9TD5ucOkettXHjAGHR-mjukEa0K2eXMsXUymREpg7eIlA&amp;dialogCs=h4bNT5JDMvzeMRF9xd2JHlVjDXZbw4cPb85PM1D4OjuazNZYINKea6kGv_iGgN0sbEqTWvHQuQ5Y00gchumLDA</value>
      <webElementGuid>aa58f77a-5cfe-4413-a208-2a3b6483aaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add/Edit Meeting Docs</value>
      <webElementGuid>8d9678c0-bd2e-4fab-bbb5-b9d27c1f7527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c761adcc-1704-4ea2-83b6-ea5d506f1dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c78a047a-34d4-43ce-bbae-478eea170972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>5dd23ff4-23b5-488a-96a6-81c08c1ac925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>58078f9f-300e-4ba1-b44a-66a45bba9221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>e88bf17a-bf77-4164-a743-248a77e46296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7231a2f4-a12b-448f-b06f-354d8c51a699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/add-edit-meeting-docs?p331_meeting_id=162&amp;clear=331&amp;session=5015463629664&amp;cs=1cYw0om3KDJ3GMvgj31E9vVhdTYHgY4QtIJrUubapk9TD5ucOkettXHjAGHR-mjukEa0K2eXMsXUymREpg7eIlA&amp;dialogCs=h4bNT5JDMvzeMRF9xd2JHlVjDXZbw4cPb85PM1D4OjuazNZYINKea6kGv_iGgN0sbEqTWvHQuQ5Y00gchumLDA' and @title = 'Add/Edit Meeting Docs']</value>
      <webElementGuid>9a657259-a351-47e1-8181-3c6178c8fdbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
