<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Upload Document</name>
   <tag></tag>
   <elementGuidId>6b078c7d-71a1-446e-af04-7d56349fec4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B240186463145500540 > span.t-Button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B240186463145500540']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1bf5a150-eefe-440c-b138-7d877070d619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button-label</value>
      <webElementGuid>7a45a1c2-95e9-416f-acf5-8cf024861dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Upload Document</value>
      <webElementGuid>2542643b-dad7-4ede-abcd-976c16151498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B240186463145500540&quot;)/span[@class=&quot;t-Button-label&quot;]</value>
      <webElementGuid>314d752e-05d9-4e79-b272-cdf4f4dae075</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='B240186463145500540']/span</value>
      <webElementGuid>47a1b2ae-a127-40b7-a9c1-a3893c2de77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meeting Documents'])[2]/following::span[1]</value>
      <webElementGuid>01a4111e-68e5-40e0-8800-419bb6d28dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latur'])[2]/following::span[3]</value>
      <webElementGuid>bac2e9f4-72ab-4611-8bb9-0c364cc9ac70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potential sponsor'])[2]/preceding::span[4]</value>
      <webElementGuid>0b940881-6614-46b3-94c1-5d61a43f3d9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form'])[2]/preceding::span[4]</value>
      <webElementGuid>52f761e6-ddfb-4202-822d-8c04432541cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Upload Document']/parent::*</value>
      <webElementGuid>1446f606-84b9-4000-97b1-333c87fd7628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[3]/button/span</value>
      <webElementGuid>a7d4bb55-5066-4e9b-bb1a-a73bc81d16cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Upload Document' or . = 'Upload Document')]</value>
      <webElementGuid>5b327afb-d4d8-45d0-82ea-f4e353a271a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
