<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_P9999_PASSWORD</name>
   <tag></tag>
   <elementGuidId>5748cbb5-3535-405a-8e6b-08f35a25b025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P9999_PASSWORD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P9999_PASSWORD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39ec5c58-86db-4466-bb28-f8a76d926998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a49dc6b9-3418-4e6c-b7d6-e0800bc90691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P9999_PASSWORD</value>
      <webElementGuid>8d936a53-7052-4bb7-af6a-6466f3f02136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>01c90591-5c68-490c-af8b-48897ba0b83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b67bc08f-7f40-4e4a-93d5-42d6f142d175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P9999_PASSWORD</value>
      <webElementGuid>2c3e6b89-1c72-4602-95b3-e27537a3f9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>eae7b91e-abdb-492e-a569-11f4df8b2fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password apex-item-text apex-item-has-icon</value>
      <webElementGuid>6c1d8cf7-7f2e-4ee9-96e6-478599c8da51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return apex.submit({request:'P9999_PASSWORD',submitIfEnter:event})</value>
      <webElementGuid>a72b17bc-5014-4560-8a86-198c0a5ab21d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P9999_PASSWORD&quot;)</value>
      <webElementGuid>176915bb-d066-4cd7-81f0-83d9ddd9b36d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P9999_PASSWORD']</value>
      <webElementGuid>aeec4d59-4b3a-457e-bc58-8c6a5b32d67a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P9999_PASSWORD_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>6d30644c-4b78-4107-be7e-ce43931b8ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::input[1]</value>
      <webElementGuid>ce3e5b46-9c59-48e4-8ae7-08d942850b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::input[2]</value>
      <webElementGuid>196fb84d-33b2-4a28-a0f1-3617e7b34814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::input[5]</value>
      <webElementGuid>42d16209-156e-419e-b09f-c982f79e3b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'P9999_PASSWORD', '&quot;', ')')])[1]/preceding::input[8]</value>
      <webElementGuid>3437a6ea-4979-42f1-8280-5965f0558b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>20187583-faf9-42d7-b658-2a65e6ce3027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'P9999_PASSWORD' and @id = 'P9999_PASSWORD' and @placeholder = 'Password']</value>
      <webElementGuid>20cf4896-6b84-4c26-b202-34146d6c5794</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
