<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>25bc4dcf-6303-4f72-a619-71e797f65fec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Meeting Observation Points&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>38b709db-e53d-47d7-a024-a9f116afe3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/meeting-observation-points?p322_x_meeting_id=162&amp;session=587382794373&amp;cs=1ExJ1546Y5UOJTvrelxXz04LPjB8Cn9-p1VwdvQ4kWDqZwZC52IZpEac8aDzYhLDAkhz7F22duOg_ATScB4Kqig&amp;dialogCs=ayKhnd64OFBlBQzsQjqinAKpRCZNPSUA0q4u8OPykiTkku5x7B1Yk7EcdtcMdR2ME8cIMgc-a0ia-z8xt40vkw</value>
      <webElementGuid>a6dbc6e6-a64a-4745-8c3c-b170c4a474b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Meeting Observation Points</value>
      <webElementGuid>84251276-f1f7-4896-a690-154b9e3eb533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9dc4d0b5-4c29-4528-9dc3-0e2f7ec8cd7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>f18c9b90-61b0-4564-9ef3-bac85d8da7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>ebf38b4f-8369-498b-b5e2-df931d344fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>142a4e7a-8fc9-43dd-84e4-ba3e00926b69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>11c6b9ad-cc09-48fd-85e0-3ad6ad14afc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>208ab84e-092b-4193-8058-d5cee5eaa635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/meeting-observation-points?p322_x_meeting_id=162&amp;session=587382794373&amp;cs=1ExJ1546Y5UOJTvrelxXz04LPjB8Cn9-p1VwdvQ4kWDqZwZC52IZpEac8aDzYhLDAkhz7F22duOg_ATScB4Kqig&amp;dialogCs=ayKhnd64OFBlBQzsQjqinAKpRCZNPSUA0q4u8OPykiTkku5x7B1Yk7EcdtcMdR2ME8cIMgc-a0ia-z8xt40vkw' and @title = 'Meeting Observation Points']</value>
      <webElementGuid>cd7c9835-5f69-4c71-9a9d-1ba75a58b847</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
