<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_1</name>
   <tag></tag>
   <elementGuidId>0a375c60-5265-4b8f-849f-b5b9ddfc8fd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Meeting  Organisers&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_2']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fe2b621a-1fb1-4567-ae2e-0253aac6e409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/meeting-organisers?p325_x_meeting_id=162&amp;p325_x_state_id=17&amp;p325_x_district_id=407&amp;session=587382794373&amp;cs=1JICAkRtubXZYXv6Z6TNcqBBlcsj_VrGJGg6gkTtzVW4d6F1kcvE_k0YyZgJ7otodUHKQ1TwkLA03OlwIWpnHwA&amp;dialogCs=_lmtAhwRcRqFi_aI2mc-s2cIBm96P6One9hgwxw2u6h_5ojPfWx-cNvJY74H6cg_9N0oyrP2uSRB07MNOrWuzw</value>
      <webElementGuid>3ce7d505-071e-4455-86a1-41c8b7ec04b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Meeting  Organisers</value>
      <webElementGuid>956d9c97-cac9-4291-9297-7314a8ef1359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>a979905c-8568-4d09-9a49-62d2f790e0c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>cab2ed8d-409b-4cf0-aed1-100d6e394b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>2319f0d3-ccd4-49c1-a41d-7a83267107f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_2&quot;)/iframe[1]</value>
      <webElementGuid>9bf1dcc4-0a14-48b8-a3f3-982a7155a601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_2']/iframe</value>
      <webElementGuid>e201c2dd-fa6a-4c22-ae33-2ec3c5be4de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>1a678781-26e4-4885-8a2f-b6393b545826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/meeting-organisers?p325_x_meeting_id=162&amp;p325_x_state_id=17&amp;p325_x_district_id=407&amp;session=587382794373&amp;cs=1JICAkRtubXZYXv6Z6TNcqBBlcsj_VrGJGg6gkTtzVW4d6F1kcvE_k0YyZgJ7otodUHKQ1TwkLA03OlwIWpnHwA&amp;dialogCs=_lmtAhwRcRqFi_aI2mc-s2cIBm96P6One9hgwxw2u6h_5ojPfWx-cNvJY74H6cg_9N0oyrP2uSRB07MNOrWuzw' and @title = 'Meeting  Organisers']</value>
      <webElementGuid>37d45f45-0012-46b6-b37e-8f15900438ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
