<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_AddEdit Organiser</name>
   <tag></tag>
   <elementGuidId>d3fe099f-988f-4d9d-9804-8417460230a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B238969257167963572 > span.t-Button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B238969257167963572']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a8139333-2fcd-42a0-909c-3f49a1a62dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button-label</value>
      <webElementGuid>42a5f4b5-1774-47e5-98af-d7b488682285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add/Edit Organiser</value>
      <webElementGuid>3f6b2207-5cb3-41c2-acee-c9d59d7383af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B238969257167963572&quot;)/span[@class=&quot;t-Button-label&quot;]</value>
      <webElementGuid>4476581e-fcb8-4da0-b428-2ef97d3fd04d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='B238969257167963572']/span</value>
      <webElementGuid>11e32630-e4eb-403d-b146-3ee4085a936a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organiser Details'])[2]/following::span[1]</value>
      <webElementGuid>6b69a3c2-d7a7-4feb-a35c-ac2c49574d38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dfvfv'])[1]/following::span[4]</value>
      <webElementGuid>a04ed700-7d47-4b90-9ed0-b55d8c0b4518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meeting Documents'])[2]/preceding::span[4]</value>
      <webElementGuid>a0b9ec52-fe3c-49a1-9314-db19185708ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Document'])[1]/preceding::span[4]</value>
      <webElementGuid>b4d482f3-dcc5-4fd0-9e5c-3f84ed809d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add/Edit Organiser']/parent::*</value>
      <webElementGuid>28cedb1a-3b3e-4d5c-8b98-fe077312cf6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[3]/button/span</value>
      <webElementGuid>a5e408f2-d69d-485a-90f5-76c2e61fb4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add/Edit Organiser' or . = 'Add/Edit Organiser')]</value>
      <webElementGuid>397871ed-4aea-49b2-b167-fd3b049795d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
