<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Disctrict_R239146613345264742_ig_grid_vc_cur</name>
   <tag></tag>
   <elementGuidId>1bdba1ac-4b27-4331-a990-f004d23a3332</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='R239146613345264742_ig_grid_vc_cur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R239146613345264742_ig_grid_vc_cur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1483ebc6-5d82-4890-8891-f4b2dedbc6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1e65b21c-d95b-4e76-84aa-27e0571ebe52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>22b3b3ad-b449-4d78-85ad-f4c843656beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tS</value>
      <webElementGuid>9dccdeeb-bc07-4935-a055-020b2d1f27f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>R239146613345264742_ig_grid_vc_ctx R239146613345264742_ig_grid_vc_cur</value>
      <webElementGuid>dcf2c49b-7d22-4f42-987b-a0edcb7c9477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R239146613345264742_ig_grid_vc_cur</value>
      <webElementGuid>13645379-e7fb-493d-bc0c-ad76107a1d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R239146613345264742_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>db46714e-6ac2-4a60-8c4f-28c404f164c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Meeting coordinator (Meeting coordinator)/Page_View Meetings/iframe_1</value>
      <webElementGuid>06fb63b7-ca47-4a1a-a3f4-22e24298e668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='R239146613345264742_ig_grid_vc_cur']</value>
      <webElementGuid>25428c02-b1fe-4fed-9dda-d75d6820cfd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R239146613345264742_ig_grid_vc']/div[3]/div[3]/table/tbody/tr/td[2]</value>
      <webElementGuid>635255ae-d6be-442b-a986-eca30da62b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>d3401d5f-19dc-48cc-8c8a-695fb0c63820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'R239146613345264742_ig_grid_vc_cur']</value>
      <webElementGuid>24ee2c3a-d4a4-4f09-9326-6bf876bbf010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
