<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Testing all chaturmas event_R23919431883_e2ecd3</name>
   <tag></tag>
   <elementGuidId>072372dd-807a-4f50-8ed7-cc612f8b2bb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='R239194318834513813_ig_grid_vc_cur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R239194318834513813_ig_grid_vc_cur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3f408ed8-859a-46b7-b39d-0ef19493282f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>4ff89009-8c13-43a9-b268-284339c533ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>c57dce2b-d9fe-4a22-8d61-e4dbe58af3bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tS is-active</value>
      <webElementGuid>bae8a043-adac-428a-a5a5-80d1b271fa12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>R239194318834513813_ig_grid_vc_ctx R239194318834513813_ig_grid_vc_cur</value>
      <webElementGuid>b41df003-685e-4da4-ad16-c1c368333847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R239194318834513813_ig_grid_vc_cur</value>
      <webElementGuid>7732280a-d808-484e-a241-1a4e7fd09d72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R239194318834513813_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>c415f8af-a6ac-4cbf-9a65-f67cf2fe9d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Meeting coordinator (Meeting coordinator)/Page_View Meetings/iframe</value>
      <webElementGuid>7f944857-69e1-42ac-9f57-dcf4662350f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='R239194318834513813_ig_grid_vc_cur']</value>
      <webElementGuid>c34ce6ff-1dde-42b2-b619-24c45f43ab69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R239194318834513813_ig_grid_vc']/div[3]/div[3]/table/tbody/tr/td[4]</value>
      <webElementGuid>0a0e8f1c-af9c-4fbb-83e3-4a5bf95c4cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]</value>
      <webElementGuid>37077f7f-aff1-4f99-9d42-f26ae17a2643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'R239194318834513813_ig_grid_vc_cur']</value>
      <webElementGuid>83c2000b-8665-4184-a276-9b603fc109cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
