<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Testing all chaturmas event</name>
   <tag></tag>
   <elementGuidId>ecf1e87e-8aea-408c-b208-b29c1a7fa561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='R239194318834513813_ig_grid_vc_cur']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#R239194318834513813_ig_grid_vc_cur</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e7e6ac18-95fd-43df-8693-8505f0cb7658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6b0c9c9b-c1c7-485a-aa36-5ecc010a7b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>379339a6-a044-4368-b4d5-ae9f0c877009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tS is-readonly is-focused</value>
      <webElementGuid>d4a30ef8-fd15-4ad6-9a07-07b85a5bc86e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>R239194318834513813_ig_grid_vc_ctx R239194318834513813_ig_grid_vc_cur</value>
      <webElementGuid>8008f01c-a29c-43eb-8ab4-b3a6f3983eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>R239194318834513813_ig_grid_vc_cur</value>
      <webElementGuid>5f80332d-36b8-4718-a5a7-b487655361e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing all chaturmas event</value>
      <webElementGuid>bcb928f1-8523-49d0-b44f-a00e5e270945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R239194318834513813_ig_grid_vc_cur&quot;)</value>
      <webElementGuid>545dec0a-978a-4fc3-b5f6-6c4bd4d8447e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Meeting coordinator (Meeting coordinator)/Page_View Meetings/iframe</value>
      <webElementGuid>46d3bba1-6cec-484e-a3e5-1214e9d0444c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='R239194318834513813_ig_grid_vc_cur']</value>
      <webElementGuid>5924411b-c265-4ed8-ae2a-7cfe4847714f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R239194318834513813_ig_grid_vc']/div[3]/div[3]/table/tbody/tr/td[2]</value>
      <webElementGuid>89f485fb-43c6-45f0-b382-ea51ba110dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seq Number'])[2]/following::td[2]</value>
      <webElementGuid>e5a10a73-b192-4e27-9a76-1a616b8c04c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason'])[2]/following::td[2]</value>
      <webElementGuid>c9d7cea9-7620-4983-b652-3162febdb4bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dfvfv'])[1]/preceding::td[5]</value>
      <webElementGuid>d55730aa-6667-4e0c-a911-db975fdf5022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Munies comming on this day 1'])[1]/preceding::td[10]</value>
      <webElementGuid>884b4445-a81c-4084-ab20-ed006a7950f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Testing all chaturmas event']/parent::*</value>
      <webElementGuid>c8dbdc31-bbeb-4248-a485-37de0ff0874d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]</value>
      <webElementGuid>deade7c3-0848-4ed8-8b42-87df8da56a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'R239194318834513813_ig_grid_vc_cur' and (text() = 'Testing all chaturmas event' or . = 'Testing all chaturmas event')]</value>
      <webElementGuid>77314647-79ad-476e-ac44-e6c54544b851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
