<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Skip to Main Content_t-Header-controlsIcon</name>
   <tag></tag>
   <elementGuidId>7c8d2473-005a-4346-83d2-e85bf0eb8b68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='t_Button_navControl']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.t-Header-controlsIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>01b211d4-6a67-4f40-bad1-8193a67eb9ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Header-controlsIcon</value>
      <webElementGuid>277f2da2-0677-45f9-955e-720d176d1dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42922259-01a1-4422-b64f-d095d8c736b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_Button_navControl&quot;)/span[@class=&quot;t-Header-controlsIcon&quot;]</value>
      <webElementGuid>98286d0e-b3d9-489a-b208-a0466d97ffc3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='t_Button_navControl']/span</value>
      <webElementGuid>374a920a-6464-4334-ad09-bc31c2e00cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>ca614b03-fbf1-4c76-910d-df0312498409</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
