<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_concat(id(, , C124596012722112820,_740d32</name>
   <tag></tag>
   <elementGuidId>363f2e6e-2a2c-41f3-8a88-f9dfb9d44045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C124596012722112820</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='C124596012722112820']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>11212521-f9c0-4cbf-bf8d-de72c03890c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>124596012722112820</value>
      <webElementGuid>46a5254d-d354-4b6f-9ff2-3eab991b0bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>b180989d-3581-44b3-b5b0-069bbae3df0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1000</value>
      <webElementGuid>ee91da6a-4a69-4c10-ba09-56133cc2f642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C124596012722112820</value>
      <webElementGuid>bcce0f4f-911a-47fa-9a22-1b35334b139d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea apex-item-textarea js-uses-enter</value>
      <webElementGuid>fd95d7b3-872c-4589-88f6-b1e9e54d42bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resizable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>93c5ebf7-3bb1-4a9b-b8b9-831d2a12fcec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2ca25305-c6ef-4c03-9b75-d16c043435fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C124596012722112820_HDR</value>
      <webElementGuid>b22f995a-611a-45bc-a7eb-fc9b831dc11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C124596012722112820&quot;)</value>
      <webElementGuid>bc5d7c56-faa9-4a7a-9505-1681feb61154</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='C124596012722112820']</value>
      <webElementGuid>e5ba05ff-6137-4ef8-99af-16aa3c2f1cd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='t_PageBody']/div[14]/div[2]/div/div/textarea</value>
      <webElementGuid>f807a671-1e3d-444e-83d8-81789e1eb831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/div/div/textarea</value>
      <webElementGuid>a59a52e2-5fac-4f62-9460-0746f56640f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = '124596012722112820' and @id = 'C124596012722112820']</value>
      <webElementGuid>31f6c5ed-acdc-48fa-9d78-9846be62954f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
