<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_P9999_USERNAME</name>
   <tag></tag>
   <elementGuidId>52ed6510-7471-44c5-a713-d5ab7885a4ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P9999_USERNAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P9999_USERNAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e85b36cc-2587-49e0-8070-d58e2a139fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0abe453e-e176-46b6-9d0e-6cba59f547b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P9999_USERNAME</value>
      <webElementGuid>7f07f1e0-6980-408e-b9df-e209feda2c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P9999_USERNAME</value>
      <webElementGuid>e993411e-9bf2-4c9b-888a-96d4e0f7f94b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>8ed86ef3-e287-47c5-89b1-7645159cb701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text apex-item-has-icon</value>
      <webElementGuid>35f06bf9-0c80-40bc-946e-c0764bde3b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>b68bab01-5136-40a2-9bda-d380090cff03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>4c8d6479-82cc-4882-9229-0e16cbe9dbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2467fe64-bcd9-42bf-aac6-0c77b09fac5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>e3bb5bc2-b46d-4e1f-a713-2d7a842b98ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P9999_USERNAME&quot;)</value>
      <webElementGuid>437ac433-f254-466e-8d49-7fd644b43613</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P9999_USERNAME']</value>
      <webElementGuid>afda77b0-60e3-46a0-80b2-f3560dd0992f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P9999_USERNAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>51acc1d7-27f4-4df1-a656-fcd8d428993c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::input[1]</value>
      <webElementGuid>588f1e7b-5e39-4672-94dd-023564dd53c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doner Receipt Generation'])[1]/following::input[1]</value>
      <webElementGuid>043a0a78-7494-437a-b0ef-ab6a8fe90812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/preceding::input[1]</value>
      <webElementGuid>d3441c8c-6361-466e-8580-fdb8fc2abd74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::input[4]</value>
      <webElementGuid>ec18f9f7-30db-403f-b02e-5fe59ef3da6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>f9c485e8-ab6c-4b4a-a0ac-ba5e8dccd27f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P9999_USERNAME' and @name = 'P9999_USERNAME' and @placeholder = 'Username']</value>
      <webElementGuid>7408290c-65d0-4db3-9aa1-f74f079db9a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
