<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_(Value Required)_t-Form-itemWrapper</name>
   <tag></tag>
   <elementGuidId>287fc30a-e652-4ad7-b4bc-5235ea64ed4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P202_MEETING_OUT_TIME_CONTAINER > div.t-Form-inputContainer > div.t-Form-itemWrapper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='P202_MEETING_OUT_TIME_CONTAINER']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02071dc8-d132-41bd-8b95-4d605705a3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Form-itemWrapper</value>
      <webElementGuid>b0d44a34-9d11-4183-8c0b-ba04ea3b1599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P202_MEETING_OUT_TIME_CONTAINER&quot;)/div[@class=&quot;t-Form-inputContainer&quot;]/div[@class=&quot;t-Form-itemWrapper&quot;]</value>
      <webElementGuid>0ed4a7c4-6f0b-4553-9ead-9a1fe37db603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Create meeting(Meeting Coordinator)/Page_Meeting- Calendar/iframe</value>
      <webElementGuid>1e164986-d6ac-4ae5-9097-bfab7c8b5b30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P202_MEETING_OUT_TIME_CONTAINER']/div[2]/div</value>
      <webElementGuid>d2538611-e5ab-4d37-bdc1-79fd67c7799e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[7]/following::div[2]</value>
      <webElementGuid>e5a536fa-e2cf-404e-b4e1-89610940c524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::div[3]</value>
      <webElementGuid>6615e941-5af4-4a46-8b36-3ccdcdc0f268</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[1]/preceding::div[7]</value>
      <webElementGuid>472b1b20-0b76-4841-97d7-122b90e21991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div</value>
      <webElementGuid>e2fe6653-2a01-4c6a-a452-70f4db7ed449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
