<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>e7780432-cb4e-4e12-936f-1c0a85c4ef88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add/Edit Meetings&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2a2b80bc-1478-4ce6-9d19-e10b22bf133c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/add-edit-meetings?p202_meeting_time=03-OCT-2023%2012%3A00AM&amp;session=2034713681443&amp;cs=1oXC4uMeqPUyoH-o2IztkKIiCvKpcvFhsvvxZo4J6_q0k8xDKS6tJ4yzimJigp2IVhRnJDCu6aGry9R__ewfwmg&amp;dialogCs=R2IfYS5DgiOIyauskG7L_4FHn6Zj0rfWXA2plvRlpO6qSjX4VI822M7t39Zs7kG2pIGTOddGCSUA0SFt7Dqsyw</value>
      <webElementGuid>f0c9c860-393b-430c-ae0e-b7b20744cbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add/Edit Meetings</value>
      <webElementGuid>90b79e6b-04b6-456d-b9d1-79b1cbbde9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>676a89c5-29bd-4c39-bc85-ae3e8e7b62f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>5a488082-ad71-4832-b072-11e88522b5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>28ae77f2-71fa-4a43-80f9-b3c59e078fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>1e434415-db08-4c27-b3ec-0dd11045531a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>bec64074-b6a2-4db2-ba8d-3897314a632e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e3cb84d0-0f80-4482-a35b-19788923deae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/add-edit-meetings?p202_meeting_time=03-OCT-2023%2012%3A00AM&amp;session=2034713681443&amp;cs=1oXC4uMeqPUyoH-o2IztkKIiCvKpcvFhsvvxZo4J6_q0k8xDKS6tJ4yzimJigp2IVhRnJDCu6aGry9R__ewfwmg&amp;dialogCs=R2IfYS5DgiOIyauskG7L_4FHn6Zj0rfWXA2plvRlpO6qSjX4VI822M7t39Zs7kG2pIGTOddGCSUA0SFt7Dqsyw' and @title = 'Add/Edit Meetings']</value>
      <webElementGuid>e76f8ea3-476c-43ca-98f0-8b878357f6a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
