<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P202_MEETING_OUT_TIME</name>
   <tag></tag>
   <elementGuidId>0c6e3c13-d78a-43e6-92e4-9ee4ea0d363b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P202_MEETING_OUT_TIME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P202_MEETING_OUT_TIME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>845385e3-68bb-4e35-8318-f0753eb06563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>798f73c6-46ef-4b14-97ea-3864e50a4f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P202_MEETING_OUT_TIME</value>
      <webElementGuid>36f49f3d-d7d2-439b-9ae9-0b415dbc8d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P202_MEETING_OUT_TIME</value>
      <webElementGuid>bc52de5a-b70d-4abb-89cc-6142da2386b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>03-OCT-2023 03:50PM</value>
      <webElementGuid>21b07467-56ed-400a-af65-82e80712e72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>248059df-2542-4435-9066-a669dc4f4eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>6fe16970-2186-4f09-af12-0f92e98dba75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-form-text</value>
      <webElementGuid>4d10870b-7fb7-47b0-b4c7-5d903819718c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P202_MEETING_OUT_TIME&quot;)</value>
      <webElementGuid>aa53d290-0c77-42cf-b30e-bbe78a7e5dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Create meeting(Meeting Coordinator)/Page_Meeting- Calendar/iframe</value>
      <webElementGuid>0d3b340e-14e2-4eca-b74c-3d60b7f05bab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P202_MEETING_OUT_TIME']</value>
      <webElementGuid>dc306816-058d-42f4-87f9-4ca2a14e6503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P202_MEETING_OUT_TIME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>df000f07-41f0-4693-992f-29d8b9f2ea49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/input</value>
      <webElementGuid>65ce7ba8-7643-4eea-8dbc-34bbd0705973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P202_MEETING_OUT_TIME' and @name = 'P202_MEETING_OUT_TIME']</value>
      <webElementGuid>5c2d36f1-5e3f-4f90-b4c6-1ad3954b8771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
