<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Select--Chaturmas Get together</name>
   <tag></tag>
   <elementGuidId>e9d35e63-beb8-49c9-92e9-4c7944613f56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P202_TEAM_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P202_TEAM_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>470d1c93-1857-4609-9aaa-4ac64c1aa5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P202_TEAM_ID</value>
      <webElementGuid>ee958692-d93a-46d3-9dc6-c1a66658ff49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P202_TEAM_ID</value>
      <webElementGuid>387a623b-33d9-45d9-88ba-c455cea8c9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>1394d5e0-0e8b-4ea4-9630-8e63abd6612e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6612db8c-c85d-4dac-973d-77d3b4fc89c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5ef8ecfb-96d1-46ef-b862-99f9dbe68cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--Select--
Chaturmas Get together
</value>
      <webElementGuid>6dd32896-b91c-42ee-afdf-5a8ed3506c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P202_TEAM_ID&quot;)</value>
      <webElementGuid>e75fdb7d-73f0-4f67-8f71-6cd786b19866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Create meeting(Meeting Coordinator)/Page_Meeting- Calendar/iframe</value>
      <webElementGuid>5abf0ff1-bb0f-48d2-aa2d-60eab1209851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P202_TEAM_ID']</value>
      <webElementGuid>87f4b77e-145f-4582-869f-d189504ee204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P202_TEAM_ID_CONTAINER']/div[2]/div[2]/select</value>
      <webElementGuid>d7028b91-e5f9-4ee6-9d11-0e1745964922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[3]/following::select[1]</value>
      <webElementGuid>ac30e0ca-00f0-4035-8ccc-4a91d04fc7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[4]/preceding::select[1]</value>
      <webElementGuid>e82e016c-a7f9-4fa0-9811-7dd215229885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>496a180d-6ca1-4be3-9ebd-8f03c17fe5d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P202_TEAM_ID' and @name = 'P202_TEAM_ID' and (text() = '--Select--
Chaturmas Get together
' or . = '--Select--
Chaturmas Get together
')]</value>
      <webElementGuid>ceba395c-8106-48d7-a8a2-d55d3180ebc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
