<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Maharashtra</name>
   <tag></tag>
   <elementGuidId>d9a9e16c-9ca5-47e3-bac6-09170d206e4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P202_STATE_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P202_STATE_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ca89c5ad-a5fe-4ee2-b69f-91af73ab405e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P202_STATE_ID</value>
      <webElementGuid>2fa827a6-c748-4489-9afd-31ba0e9f9583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P202_STATE_ID</value>
      <webElementGuid>3d589dc8-28d9-4df7-9125-7e3fad0dd71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>81d64357-10fd-424f-ace6-42f593ce2456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1f9ee12-c8d2-4084-b41d-b200f8a9cbcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>79c0b6ba-a68c-434d-8a54-98728e81cbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

Maharashtra</value>
      <webElementGuid>0bd9b99e-e358-4741-9831-f8910611d87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P202_STATE_ID&quot;)</value>
      <webElementGuid>11d242be-eabd-4a3b-976f-343551d8da59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Create meeting(Meeting Coordinator)/Page_Meeting- Calendar/iframe</value>
      <webElementGuid>cd950071-be70-452e-819c-be8ee12e14fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P202_STATE_ID']</value>
      <webElementGuid>429ad713-52fd-464a-8a03-e4959716c322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P202_STATE_ID_CONTAINER']/div[2]/div[2]/select</value>
      <webElementGuid>c219ac54-fc70-41a4-bb5f-c6d4b78e31eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[4]/following::select[1]</value>
      <webElementGuid>1181f087-5636-45ad-93fa-eb45ccef60a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[5]/preceding::select[1]</value>
      <webElementGuid>5ed2a1f7-e6be-49a4-bd85-68cc6bca1698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[2]/select</value>
      <webElementGuid>2ea3404b-d944-48e6-bca0-9b026ea8be2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P202_STATE_ID' and @name = 'P202_STATE_ID' and (text() = '

Maharashtra' or . = '

Maharashtra')]</value>
      <webElementGuid>179da508-72b7-4988-af12-1aae90823241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
