<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Board_P6_BOARD_lov_btn</name>
   <tag></tag>
   <elementGuidId>bbda1f04-3e29-4b13-9ffd-19687f7deef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_BOARD_lov_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P6_BOARD_lov_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd7ae3c8-0925-44e4-b384-df37f34424a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1f83fedf-fe2d-49a0-8694-dddf0913dd1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88eba2f3-6096-4ee1-ae66-4ae9899ff4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Button--popupLOV</value>
      <webElementGuid>9ce5ebc4-9566-4b78-b502-4c06a2f4cb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_BOARD_lov_btn</value>
      <webElementGuid>aa11fe1c-34d0-4a1b-9541-9cf39f9c9561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2d680485-81ef-452a-99f9-776c838b8ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_BOARD_lov_btn&quot;)</value>
      <webElementGuid>5b9b4221-46ed-4d02-ab1d-ff0c6b772507</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='P6_BOARD_lov_btn']</value>
      <webElementGuid>a6cc53c4-ce19-4d4e-b7ee-eefcf4948a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_BOARD_CONTAINER']/div[2]/div/div/button</value>
      <webElementGuid>c2ea1a15-9bc2-4203-b6db-ced7f2ef30b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Board'])[1]/following::button[1]</value>
      <webElementGuid>f5006de0-07c2-4b99-af11-2967e8e7daad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pincode'])[1]/following::button[1]</value>
      <webElementGuid>2b3bae44-d56b-450f-b59c-4d77a661df0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grade'])[1]/preceding::button[1]</value>
      <webElementGuid>05c32390-6c41-4f2e-8aed-74dc050297c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium Of Education'])[1]/preceding::button[2]</value>
      <webElementGuid>7fd05d4d-3535-4d26-b335-ac308b1ef618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/button</value>
      <webElementGuid>3f8f14c5-b6ad-43fa-b7b4-0270949a176f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'P6_BOARD_lov_btn']</value>
      <webElementGuid>8e938db3-d632-4e8b-adf5-a67fba7046a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
