<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Principal Name_P6_PRINCIPAL_NAME</name>
   <tag></tag>
   <elementGuidId>eb34dce7-fdd3-4f2c-b1b5-3c3b861fe83b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_PRINCIPAL_NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_PRINCIPAL_NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>089b7645-46c0-455d-8889-06527cc56f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>343d86bb-b4ec-4785-a36e-dc1fa0b7b7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_PRINCIPAL_NAME</value>
      <webElementGuid>a64c00d8-e70f-4d7a-8bda-d8efa9ccefd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_PRINCIPAL_NAME</value>
      <webElementGuid>224e7554-28c6-4324-bc05-0c76e68499c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>2ba05da8-c36f-4349-a342-3898d2fca3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>bfe6a6a9-31cb-4a25-9b3b-59db5e939787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>d89c934b-6252-4849-a085-a03fb8aef64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_PRINCIPAL_NAME&quot;)</value>
      <webElementGuid>0af6b458-f46a-4dba-a4e8-da59fc5480ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_PRINCIPAL_NAME']</value>
      <webElementGuid>68a45d2a-9355-4f30-9e25-13c08842f267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_PRINCIPAL_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>5aa4fe22-574c-48e8-a179-d43771012c24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>1d46578d-c12f-490e-bd82-9d29d7a0afba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_PRINCIPAL_NAME' and @name = 'P6_PRINCIPAL_NAME']</value>
      <webElementGuid>57f1c557-4e3b-4b01-b618-af9715ac2c29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
