<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trustee Whatsapp No_P6_TRUSTEE_WHATSAPP_NO</name>
   <tag></tag>
   <elementGuidId>ba8e4347-7273-49b7-8b9e-daa64b9e01cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_TRUSTEE_WHATSAPP_NO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_TRUSTEE_WHATSAPP_NO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bc86f77-ce87-4000-a119-f11ab399430d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b38cb541-038f-4c8a-950c-f6aea00774c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_TRUSTEE_WHATSAPP_NO</value>
      <webElementGuid>238f3784-9de4-4d19-89fa-732718a681a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_TRUSTEE_WHATSAPP_NO</value>
      <webElementGuid>f4c1e2f3-81d0-4685-9b36-5bbb187a8514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number</value>
      <webElementGuid>a135c7b5-3f0b-4855-a6f7-11f9f7100d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>642f8dcf-9434-40dd-a234-be3cc18e75e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>8b786129-9565-4471-ba31-65f207d518d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>4f84041b-7d87-4c76-9742-4d9db0d49e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_TRUSTEE_WHATSAPP_NO&quot;)</value>
      <webElementGuid>0cd877b1-cef4-41b6-ac81-e41265a39405</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_TRUSTEE_WHATSAPP_NO']</value>
      <webElementGuid>d15505ce-976e-4c83-8a8a-1d0250a2bb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_TRUSTEE_WHATSAPP_NO_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>44c528a8-4feb-4730-b1a0-65d127f55d2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>ef798e0f-48de-48bc-84b4-83f7f1c5a16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_TRUSTEE_WHATSAPP_NO' and @name = 'P6_TRUSTEE_WHATSAPP_NO']</value>
      <webElementGuid>ff4385a0-bef1-47e4-8b39-97e80c7b6ef7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
