<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Person_P6_CONTACT_PERSON</name>
   <tag></tag>
   <elementGuidId>b0fc89e8-912b-420d-91e3-1edacd4b7fc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_CONTACT_PERSON</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_CONTACT_PERSON']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7b25c2d-59c0-4e3d-8a79-928d3c1c3ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8783ece-977d-4bb9-a27a-1c1aca4fef0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_CONTACT_PERSON</value>
      <webElementGuid>c692384c-18e2-4843-91e3-79f7d32f9b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_CONTACT_PERSON</value>
      <webElementGuid>fbeb3698-25cc-43b3-886c-1e3c7ee20802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>397699ab-ad00-4987-98d7-44dbc289a025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>bb6142d4-a781-40b0-af51-49e59923ce98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>7b65fd74-cdff-4a72-aeab-2664fa4d3843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_CONTACT_PERSON&quot;)</value>
      <webElementGuid>14b9cf1a-ae22-48c8-a96d-bb4c36bb3a59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_CONTACT_PERSON']</value>
      <webElementGuid>0d268011-e49f-43b3-a7b5-17006560f1a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_CONTACT_PERSON_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>3bef4818-3f76-4389-a4e0-a5ad49912efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>7564c350-22d5-4b95-9a4a-7b7eed86fe07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_CONTACT_PERSON' and @name = 'P6_CONTACT_PERSON']</value>
      <webElementGuid>f0293608-f69a-494a-afe7-17b35c3460db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
