<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Principal Mobile No_P6_PRINCIPAL_MOBILE_NO</name>
   <tag></tag>
   <elementGuidId>a71af401-7009-40ea-a487-a2da5987d4b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_PRINCIPAL_MOBILE_NO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_PRINCIPAL_MOBILE_NO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>549c3818-ed6e-4ed0-ad76-20240b7df1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98137b98-6164-4b7a-946a-ca73009587b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_PRINCIPAL_MOBILE_NO</value>
      <webElementGuid>eb821272-79bf-4efe-92eb-7ddb9a8c4eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_PRINCIPAL_MOBILE_NO</value>
      <webElementGuid>7559aeec-7ee4-4695-b364-32e54a49d873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number</value>
      <webElementGuid>28f54445-ca2b-4a47-aa8d-5de74c026f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>7d9337c3-d820-4168-a4ba-27d7442e4204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6bee1c66-5c75-42f5-9231-b00e3aab8a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>d718bd34-1193-4808-bfd9-5a0b8d200e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_PRINCIPAL_MOBILE_NO&quot;)</value>
      <webElementGuid>a705b282-22d8-4a9b-b684-c7a1f575eaee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_PRINCIPAL_MOBILE_NO']</value>
      <webElementGuid>df60a6f5-c958-4e60-80ca-bc46c5de45a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_PRINCIPAL_MOBILE_NO_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>1bd67f25-7777-42d0-96fd-dda290525f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div[2]/div[2]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>49b515d1-3a60-4599-b738-b7a72990d96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_PRINCIPAL_MOBILE_NO' and @name = 'P6_PRINCIPAL_MOBILE_NO']</value>
      <webElementGuid>5ba11797-fc91-4683-bcce-7407ebfc848a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
