<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_School Name_P6_INSTITUTIONNAME</name>
   <tag></tag>
   <elementGuidId>1e49d28c-4174-4c12-a574-eed642858bc6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_INSTITUTIONNAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_INSTITUTIONNAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf4257ef-8bfd-425f-b757-685a89b0d67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e2ff282-ade1-4a87-b399-5897764e384a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_INSTITUTIONNAME</value>
      <webElementGuid>d1dc245e-84ca-4687-ba61-eccadc406fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_INSTITUTIONNAME</value>
      <webElementGuid>e7377a69-bd9e-4742-985c-9d3b31a05d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>a5f5313b-23da-40f6-b678-89c6def5a1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>d3f11a01-a179-42a6-b8ec-7be39889751a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>64f4485e-8b60-46b0-af08-2c3f5af70c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>7782e0b3-0784-4dfc-bd38-85ca73f25b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_INSTITUTIONNAME&quot;)</value>
      <webElementGuid>639cc3b3-12ae-4737-83a8-7f066439faa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_INSTITUTIONNAME']</value>
      <webElementGuid>9248e6b5-d5b6-47c5-9654-99ed810740f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_INSTITUTIONNAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>babe325e-0d3a-4a7e-9675-5a34aa9142e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>828cc4fc-6126-4108-9f06-6339621f2d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_INSTITUTIONNAME' and @name = 'P6_INSTITUTIONNAME']</value>
      <webElementGuid>5375361a-f98d-484a-b402-a00fc7b49a99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
