<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trustee Position_P6_TRUSTEE_POSITION</name>
   <tag></tag>
   <elementGuidId>ffd2bcfa-b999-44f9-a1d0-31f2ff4f1443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_TRUSTEE_POSITION</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_TRUSTEE_POSITION']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0cad187-c8e7-491f-87cb-6fd823c89130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1018ca10-29c3-4a7d-acfd-82f7a8d461e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_TRUSTEE_POSITION</value>
      <webElementGuid>0fbcf80e-6bb8-4744-914c-bab129918370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup_lov apex-item-text apex-item-popup-lov</value>
      <webElementGuid>0f59ee16-116e-4279-9535-f9cdee735bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>d9dda9a5-e044-435b-9a89-9a9cf2163f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>b964e456-a975-4f95-94bc-40b8ab88c41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>7467b5c2-32a0-4727-8131-e12fcb0d7406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>f0ce18fc-cbf4-4d57-a802-857d3ecf802c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b199e67-224f-4521-8b31-8d272237d58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>acc6e0fd-11a6-4a9d-a126-b3c3d73f6f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_TRUSTEE_POSITION&quot;)</value>
      <webElementGuid>ccc18307-8dcd-41f2-abe6-8cfeeff8e1e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_TRUSTEE_POSITION']</value>
      <webElementGuid>5c152e1d-baa3-4f79-bb5e-b003dc9de724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_TRUSTEE_POSITION_CONTAINER']/div[2]/div/div/input</value>
      <webElementGuid>b4bad525-d478-4a32-8abd-11c7e24d0496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d795590d-2678-428d-8f92-99f011cc3bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_TRUSTEE_POSITION']</value>
      <webElementGuid>7e7c1610-da1e-4ebb-8ae5-e5e3efceb695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
