<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pincode_P6_PINCODE</name>
   <tag></tag>
   <elementGuidId>c981d8ca-e13e-4cba-80e4-09062c1a3c81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_PINCODE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_PINCODE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc9ba807-9b42-4c7d-8f61-22d7e40ceb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aceb2517-e6ed-4e79-8e04-60c2fe19364d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_PINCODE</value>
      <webElementGuid>e99282b4-6ef5-45e6-b257-fe9eee932f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_PINCODE</value>
      <webElementGuid>46800ae6-e1da-46d7-9d4b-70a21ec9ef7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number</value>
      <webElementGuid>eba85d3e-d844-4ba6-a889-b637b7396b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>a99ae1ac-f373-4edd-b14d-c08e456c34ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>770bb6fa-8b19-4b48-a40b-b4e83453abef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>d29ed51b-c86a-4a19-9fc1-1d5fdba601bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_PINCODE&quot;)</value>
      <webElementGuid>c87577b5-aff7-4dd7-9d34-1afdf66e3c99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_PINCODE']</value>
      <webElementGuid>5c3ae8a8-0851-40e7-a2be-6e8ca90cfa7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_PINCODE_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>de78696a-c5a8-47a4-853d-8afc96dcb952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>4d70653a-3ad3-453e-9ad0-188df7a49399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_PINCODE' and @name = 'P6_PINCODE']</value>
      <webElementGuid>58874377-55d3-4d22-93cd-ab8bdd3c7059</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
