<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trustee Name_P6_TRUSTEE_NAME</name>
   <tag></tag>
   <elementGuidId>2bb48bf1-615b-493b-8917-8de251d7a9b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_TRUSTEE_NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_TRUSTEE_NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9dbcf496-8840-4e10-875a-b07782e68cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ad9a38d-90b9-48f4-bf24-8f74a574b244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_TRUSTEE_NAME</value>
      <webElementGuid>8aa488b6-75e9-471c-bf55-02ac15bd5a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_TRUSTEE_NAME</value>
      <webElementGuid>6e8d282f-e6e4-40a8-a240-abde2f87e983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>6b3a2f17-d88b-4258-a19e-444d36142778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>34e77305-626c-41c1-8132-8281b1c97c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>e6bfbbb3-3f67-4c28-a7b5-befa564608a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_TRUSTEE_NAME&quot;)</value>
      <webElementGuid>679919a0-b6f9-4182-94e2-75402ead17ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_TRUSTEE_NAME']</value>
      <webElementGuid>cadef089-ae15-4288-bfe9-808567ba922f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_TRUSTEE_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>1145f860-6347-4930-bc37-f172e264a890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>2e822661-4442-4d37-b5ac-3ea494c7688d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_TRUSTEE_NAME' and @name = 'P6_TRUSTEE_NAME']</value>
      <webElementGuid>f0f49f22-61dc-41bf-8d47-0843dbaa945d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
