<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_District_P6_DISTRICT</name>
   <tag></tag>
   <elementGuidId>3ed21518-c171-4947-9c4d-f65a89fcb6b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_DISTRICT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_DISTRICT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de665fe7-9411-4f24-bb7d-0e1d0bc20ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f5989a8-a239-4b10-af7a-37823e1d3499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_DISTRICT</value>
      <webElementGuid>2f5a9ad6-e89f-420d-9b53-ab9f183c82e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup_lov apex-item-text apex-item-popup-lov</value>
      <webElementGuid>10e6c800-705f-4531-ab9b-4f9dccf82fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>2e3b2d80-23df-474d-8e5e-1cbfea78e978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>05942e99-8f0d-4dd6-af33-0fdfb59e485d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3241c936-b5eb-4458-a730-0abd46682c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>b511f44f-a7c8-4afc-b118-e440ab677730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b11ea2bf-a4db-49ff-9e20-56c8fe6db808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>8b0cc997-2f7e-4582-a787-51608cd40b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_DISTRICT&quot;)</value>
      <webElementGuid>c694aed7-7c11-41a9-8804-455a92b7277b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_DISTRICT']</value>
      <webElementGuid>0965957e-b1e7-4de2-a946-e55431ac4e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_DISTRICT_CONTAINER']/div[2]/div/div/input</value>
      <webElementGuid>60a4bded-9a87-40c8-8da6-bcffd25cd255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/div[2]/div[3]/div/div/div[2]/div/div/input</value>
      <webElementGuid>6b428e41-033d-4506-a31a-69da858533a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_DISTRICT']</value>
      <webElementGuid>23304107-1030-437d-b0d9-d9232954f787</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
