<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trustee Mobile No_P6_TRUSTEE_MOBILE_NO</name>
   <tag></tag>
   <elementGuidId>cb4db48d-cd11-459a-ad57-97ae49278518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_TRUSTEE_MOBILE_NO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_TRUSTEE_MOBILE_NO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>411989ae-277c-431a-b1a3-cf3a5c44c696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>64eb0985-4891-48fb-be86-018325ae2719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_TRUSTEE_MOBILE_NO</value>
      <webElementGuid>2b41929d-54e4-4cf7-94ce-32d7daad89ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_TRUSTEE_MOBILE_NO</value>
      <webElementGuid>66a76626-149f-4b42-b490-ba31774d2016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number</value>
      <webElementGuid>9686ac79-e9a4-4b33-b06d-21a9260d8288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>c0523312-657c-4b6e-b67f-601f453892da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>072a52c6-cd31-420e-bab7-f03e38706ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>74b7e1d0-4d52-4117-b8d8-b448dba158a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_TRUSTEE_MOBILE_NO&quot;)</value>
      <webElementGuid>43e2587e-27f3-42e7-a72b-a1f5f0d0d6c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_TRUSTEE_MOBILE_NO']</value>
      <webElementGuid>262d585a-b3fa-4222-b524-1859f1a0ee92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_TRUSTEE_MOBILE_NO_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>a1847f56-743c-461d-a319-5ae888e3ada9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>d7e9636e-852d-4c4f-8a2b-907f49717c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_TRUSTEE_MOBILE_NO' and @name = 'P6_TRUSTEE_MOBILE_NO']</value>
      <webElementGuid>079bf7de-8bf5-4844-8ca1-52862da9e33a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
