<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Address_P6_ADDRESS</name>
   <tag></tag>
   <elementGuidId>676a4ff6-9248-4fbe-9e2a-94000f670134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P6_ADDRESS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='P6_ADDRESS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>10565314-9655-46fd-8314-57174bf9e41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_ADDRESS</value>
      <webElementGuid>13373b45-0ef7-4955-8f9d-b69a9955c118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>91b77673-0681-48a0-90ee-e776bf497748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>cd90752c-2795-4bd8-9005-6737a14f317e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>3d469371-986b-41f5-bef4-04675475d15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_ADDRESS</value>
      <webElementGuid>fc91efbb-9f39-4e97-a9cd-e5ad28813c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea apex-item-textarea</value>
      <webElementGuid>ac10f4cb-1436-40df-88d9-22654e1b327f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resizable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9168df7f-1c0d-450a-8e17-fea0ae9e6c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_ADDRESS&quot;)</value>
      <webElementGuid>6194a792-80a8-473f-a505-d09580a391d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='P6_ADDRESS']</value>
      <webElementGuid>be41a5e3-acff-4ad9-aedb-45fee15422dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_ADDRESS_CONTAINER']/div[2]/div/div/textarea</value>
      <webElementGuid>71d849b5-f881-4435-be9c-3e3727dbdb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>a6573a79-9e35-4626-ad0f-f51879959450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'P6_ADDRESS' and @id = 'P6_ADDRESS']</value>
      <webElementGuid>8d2d98c4-07ed-4d8f-afd6-9a62d4d293f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
