<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>86de2b15-a61c-46ab-859a-33b38162b059</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add Donor Type&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>74eb7c63-13f2-4e87-8f93-e92fc8db1cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation/add-donor-type?clear=19&amp;session=665394213770&amp;cs=3HjAh3W8Y9Y21jGaYcx_k3FyyH3caAoHeL1SfIsR4-c4GcIng6wFvTKisxtagM4WAidGv-go5yrWZSHAE6i7OzQ&amp;dialogCs=2ZRpM1rC7Yo6-GVTRfzWzdkjFJG0LOHXLpsMMLbyrFBmiQ0P6uUXPQcirimPdiJzsajlIGxbFPfrRs-c9LvnlQ</value>
      <webElementGuid>ac01f7d3-4835-4f06-a5e1-9e3c98afe1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Donor Type</value>
      <webElementGuid>4c1958b9-5903-4da8-80fe-fa47d5ed8eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c1fa2b05-9ecf-4b78-97a8-e42c70da063d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>644924bc-afa7-4f92-8132-5d885f4cc190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>5360ef43-bf34-4e55-9d1f-0348b3d5c002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>8eb5c231-240b-43de-b98c-43112333ce72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>2a258638-fd6e-4a62-a4a0-cd39fdc83b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cf432aae-8cb7-4de8-9ce6-f8f4a206087d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation/add-donor-type?clear=19&amp;session=665394213770&amp;cs=3HjAh3W8Y9Y21jGaYcx_k3FyyH3caAoHeL1SfIsR4-c4GcIng6wFvTKisxtagM4WAidGv-go5yrWZSHAE6i7OzQ&amp;dialogCs=2ZRpM1rC7Yo6-GVTRfzWzdkjFJG0LOHXLpsMMLbyrFBmiQ0P6uUXPQcirimPdiJzsajlIGxbFPfrRs-c9LvnlQ' and @title = 'Add Donor Type']</value>
      <webElementGuid>ee416f32-fc4a-4531-9f9d-500308b3b23f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
