<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Donor Type_P19_DONOR_TYPE</name>
   <tag></tag>
   <elementGuidId>ccdfe3fe-b547-4211-98ec-3e3857ce4f05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P19_DONOR_TYPE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P19_DONOR_TYPE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27abc68b-bdd3-456d-8182-6e1117d23e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>640a3e82-2fa6-496d-9a4e-24de947a3c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P19_DONOR_TYPE</value>
      <webElementGuid>567bfc76-e1b3-4753-a680-a419bd728b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P19_DONOR_TYPE</value>
      <webElementGuid>75d603fb-e588-4872-be39-c8ae44bc0c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>c82a0243-ac7f-4216-86c9-74fa0b1c4ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>01bbf08f-0552-48f2-8c8e-88488dd94523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>5c7c5095-e260-4693-bac6-173f1c90337b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>bb5d2a58-16a9-43f6-8b37-aa62d5bab273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P19_DONOR_TYPE&quot;)</value>
      <webElementGuid>85a3e6cc-b637-454b-ab7e-64d8a1775aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Doner Type Master (Donor Receipt)/Page_Donor Type Master/iframe</value>
      <webElementGuid>a2feb521-7636-46f1-bbd3-ca2a3327b188</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P19_DONOR_TYPE']</value>
      <webElementGuid>247c6e8c-5320-4da4-b078-ed2afe9494eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P19_DONOR_TYPE_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>742e1cf8-bc6a-487a-823c-610ddebb4046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>37dd182f-7b90-4667-ad98-2ee3b65e05ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P19_DONOR_TYPE' and @name = 'P19_DONOR_TYPE']</value>
      <webElementGuid>210e0f6a-8abd-4d39-ac1d-ffed5ac4fe97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
