<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Latur</name>
   <tag></tag>
   <elementGuidId>ad43398b-70df-4fd8-b475-5deb2a289a7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='R238373431837570428_calendar']/div[4]/div/table/tbody/tr[2]/td/div/div/div/table/tbody/tr[5]/td[6]/div/div[2]/div/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0a4ed39-a605-4d33-8d2d-79d27fde69d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-event-title fc-sticky</value>
      <webElementGuid>f719dda5-a289-4dcd-8040-1d2fb239edcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Latur</value>
      <webElementGuid>bcb2bf06-7cfb-4cf7-97bf-0234023d842a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R238373431837570428_calendar&quot;)/div[@class=&quot;fc-view-harness fc-view-harness-active&quot;]/div[@class=&quot;fc-daygrid fc-dayGridMonth-view fc-view&quot;]/table[@class=&quot;fc-scrollgrid  fc-scrollgrid-liquid&quot;]/tbody[1]/tr[@class=&quot;fc-scrollgrid-section fc-scrollgrid-section-body  fc-scrollgrid-section-liquid&quot;]/td[1]/div[@class=&quot;fc-scroller-harness fc-scroller-harness-liquid&quot;]/div[@class=&quot;fc-scroller fc-scroller-liquid-absolute&quot;]/div[@class=&quot;fc-daygrid-body fc-daygrid-body-unbalanced&quot;]/table[@class=&quot;fc-scrollgrid-sync-table&quot;]/tbody[1]/tr[5]/td[@class=&quot;fc-daygrid-day fc-day fc-day-fri fc-day-past&quot;]/div[@class=&quot;fc-daygrid-day-frame fc-scrollgrid-sync-inner&quot;]/div[@class=&quot;fc-daygrid-day-events&quot;]/div[@class=&quot;fc-daygrid-event-harness&quot;]/a[@class=&quot;fc-daygrid-event fc-daygrid-dot-event fc-event fc-event-start fc-event-end fc-event-past apex-cal-green&quot;]/div[@class=&quot;fc-event-title fc-sticky&quot;]</value>
      <webElementGuid>5472f64b-8963-4e82-870d-15962ce77a14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R238373431837570428_calendar']/div[4]/div/table/tbody/tr[2]/td/div/div/div/table/tbody/tr[5]/td[6]/div/div[2]/div/a/div</value>
      <webElementGuid>df16c5cf-42ac-4030-85c7-0ad7c5b58656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ariyalur'])[1]/following::div[22]</value>
      <webElementGuid>205005a3-65d1-4d95-8515-80ada6a773e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Latur'])[3]/following::div[44]</value>
      <webElementGuid>602c5304-98af-46cf-a177-524abea3d2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CSV'])[1]/preceding::div[8]</value>
      <webElementGuid>1fc0bf25-1d61-41d8-b136-56fe5831484b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iCal'])[1]/preceding::div[8]</value>
      <webElementGuid>eea933dc-ed25-4ebc-9f4d-a25c2c8a2415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[6]/div/div[2]/div/a/div</value>
      <webElementGuid>d8001ef0-f7cb-4c9c-aff5-4e2dfdfee57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Latur' or . = 'Latur')]</value>
      <webElementGuid>f1ab5000-2bed-45c1-80c5-052bbe61747e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
