<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Matrimony Data Verification</name>
   <tag></tag>
   <elementGuidId>966d09b8-9760-4ab3-86e3-a8d736d925af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.a-TreeView-content.is-hover > a.a-TreeView-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='t_TreeNav_4']/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c547307-9908-47ca-8786-0cca4bbe352a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>1d56a272-602b-47b9-aab8-ed3ae4cff724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>fdd4d7a0-350a-4b31-81a5-05986803600b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-label</value>
      <webElementGuid>6f13f283-aadb-4522-ae59-5468bbfd914b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ords/r/social_events/social-events/matrimony-data-verification?session=13764574442777</value>
      <webElementGuid>83c47bf7-dd00-46da-877a-2e8cfd5b2852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4daf65a8-6a7b-4fb2-8a53-f12848817fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>da4648b1-7bdb-4863-8f32-29e59c106008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Matrimony Data Verification</value>
      <webElementGuid>0d112bc4-28a8-4c4f-a524-3ebe02d4ccd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_4&quot;)/div[@class=&quot;a-TreeView-content is-hover&quot;]/a[@class=&quot;a-TreeView-label&quot;]</value>
      <webElementGuid>f9512da9-2600-4b2b-a33d-ec4aa0c88be5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_4']/div[2]/a</value>
      <webElementGuid>51e9b38b-738f-41bc-8eff-8fbeaa4a72bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Matrimony Data Verification')]</value>
      <webElementGuid>57fa7fd9-b441-4699-aa37-f57f7c2cd09d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master'])[1]/following::a[1]</value>
      <webElementGuid>4b9e9394-8857-41e2-a057-b230460c4c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User List'])[1]/following::a[1]</value>
      <webElementGuid>903437c5-2116-4d8d-858e-e466754340ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matrimony Profile Report'])[1]/preceding::a[1]</value>
      <webElementGuid>3a05e653-a029-4cc7-94d4-b89f03d85a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Matrimony Events'])[1]/preceding::a[2]</value>
      <webElementGuid>4d3c8d4c-98c0-4b76-b0db-d84405352f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Matrimony Data Verification']/parent::*</value>
      <webElementGuid>9a9d20ad-e515-4539-abb7-1c7324612346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ords/r/social_events/social-events/matrimony-data-verification?session=13764574442777')]</value>
      <webElementGuid>46f675c1-befe-4e4c-a508-6171279c103e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div[2]/a</value>
      <webElementGuid>d20f7ea0-fbdc-48ff-968a-517c348825b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ords/r/social_events/social-events/matrimony-data-verification?session=13764574442777' and (text() = 'Matrimony Data Verification' or . = 'Matrimony Data Verification')]</value>
      <webElementGuid>6b19c877-70fb-4468-b6d0-8c4b751a023a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
