<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>504b0d1b-5579-41e0-8ffd-f535d262928e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Approve/Reject Records&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2ab3234c-9ce2-4e7c-9c36-ce9e2e8485a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/social_events/social-events/approve-reject-records?p39_x_pp_id=205&amp;p39_x_email_id=sankumar.us%40gmail.com&amp;p39_x_mobile_no=1234567890&amp;p39_x_first_name=sdfsd&amp;p39_x_last_name=sdfsd&amp;clear=39&amp;session=13764574442777&amp;cs=1WSq60MZeKA_NhH-eXknahp-uMC7ChKKGYUC9ru_l7M1vYZFl8ETGyaOnehQxnzDdowIKZaKpzW4ew4fWYKuiCQ&amp;dialogCs=7aX3YdVlhq3gf5OTwzUe9jIJgQvlTGOYzKOs81nrKj5A5bbUBpXNkgp-KsTAT8aEgpTFz_A4le77_Y7lt-lc1Q</value>
      <webElementGuid>512a6b99-f927-4695-850f-d7857b0a1787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Approve/Reject Records</value>
      <webElementGuid>34fbe40c-53b8-4688-acee-7cd75baf8716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>d20dc806-a122-439a-bf39-b1c7abfa188b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>0e3305f0-ac23-465d-9678-facc4333d035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>aa7ab51f-d6da-4dd4-be2b-c6c22fc7ce49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>7df37037-b830-4c56-bf7d-40eb710e6d78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>e47851c8-501e-4005-b318-c4bc9bee7897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>fab7022a-0be5-4b3d-aa9a-23db6658b04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/social_events/social-events/approve-reject-records?p39_x_pp_id=205&amp;p39_x_email_id=sankumar.us%40gmail.com&amp;p39_x_mobile_no=1234567890&amp;p39_x_first_name=sdfsd&amp;p39_x_last_name=sdfsd&amp;clear=39&amp;session=13764574442777&amp;cs=1WSq60MZeKA_NhH-eXknahp-uMC7ChKKGYUC9ru_l7M1vYZFl8ETGyaOnehQxnzDdowIKZaKpzW4ew4fWYKuiCQ&amp;dialogCs=7aX3YdVlhq3gf5OTwzUe9jIJgQvlTGOYzKOs81nrKj5A5bbUBpXNkgp-KsTAT8aEgpTFz_A4le77_Y7lt-lc1Q' and @title = 'Approve/Reject Records']</value>
      <webElementGuid>3ab547b5-4864-48f5-aafa-6011f1dfbe2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
