<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ApproveReject</name>
   <tag></tag>
   <elementGuidId>c489b72b-6a81-479f-a061-a58e5b59cde5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B188762070665502276 > span.t-Button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B188762070665502276']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7983c4b3-d3a1-4ede-a79e-dedab7f99c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button-label</value>
      <webElementGuid>58de419e-6a87-4410-9815-e0058bff1e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve/Reject</value>
      <webElementGuid>6f09643b-523b-4b25-80b0-bfca23931e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B188762070665502276&quot;)/span[@class=&quot;t-Button-label&quot;]</value>
      <webElementGuid>2f39b21e-dad6-43e1-bfae-ec54cc1d705c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='B188762070665502276']/span[2]</value>
      <webElementGuid>8733d504-32af-44d0-a352-d28b7e927036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[2]</value>
      <webElementGuid>73795d0b-296c-4935-a1d8-4b1a18267230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pincode'])[2]/following::span[5]</value>
      <webElementGuid>835e32ed-2ad9-4df7-bdea-b1f1ead96041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Release 1.0'])[1]/preceding::span[2]</value>
      <webElementGuid>32a0944e-8425-4bf5-ac39-f0b747922775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='---'])[1]/preceding::span[3]</value>
      <webElementGuid>19cf45f3-a2fd-4a64-8fa7-ff606f4b01f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Approve/Reject']/parent::*</value>
      <webElementGuid>b59c79b3-6ed0-4730-b207-fd245b41e8ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span[2]</value>
      <webElementGuid>b6a7544a-b23d-421d-add5-5912e7ac432f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Approve/Reject' or . = 'Approve/Reject')]</value>
      <webElementGuid>2e449654-15ed-465a-b797-7cfe6e79ea9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
