<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Manage Masters</name>
   <tag></tag>
   <elementGuidId>7fccc466-3100-4c11-b0f0-ee8cf2bd8cc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='t_TreeNav_1']/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.a-TreeView-label.is-current</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>93f59bc1-8c38-4802-b762-6b6a090a839d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>574aff3a-15d8-4add-819c-37699a15446d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>2648b1b2-0b22-4aaa-bfed-64a3a751dd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-TreeView-label is-current</value>
      <webElementGuid>7bf155d8-682f-4930-a6d1-6855c03b7cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation177/manage-masters?session=12384949946323</value>
      <webElementGuid>bd762da8-993b-4b88-b577-85f18ee4d185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9fbd765f-15a5-4e7b-9ef4-ea39b8a66e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>29c902b8-7d88-409e-a312-a4f3069ab532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>550e2f1c-2f2c-4c5c-8d61-a1b4952fbce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage Masters</value>
      <webElementGuid>70de694a-5411-4318-8184-d977048e8cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_TreeNav_1&quot;)/div[@class=&quot;a-TreeView-content is-selected is-current--top is-hover&quot;]/a[@class=&quot;a-TreeView-label is-current&quot;]</value>
      <webElementGuid>1c73316e-f498-468d-8efd-87b53b72ce7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='t_TreeNav_1']/div[2]/a</value>
      <webElementGuid>99ce1d76-27df-4e94-b837-01f38d89bf23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Manage Masters')]</value>
      <webElementGuid>bd273df1-3e7e-4d90-b42c-3138ed7f3a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>660c467f-85c1-47d0-b686-d3f23fc7c289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About'])[1]/following::a[2]</value>
      <webElementGuid>8b104430-7c8a-4c04-a072-2aeb7d1969a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donor Details'])[1]/preceding::a[1]</value>
      <webElementGuid>ca0eade6-9640-4ec5-87e1-6f22d43bc5a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorized Person Master'])[2]/preceding::a[2]</value>
      <webElementGuid>dcdb40e8-98c5-4acd-9297-15782a5d2a80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage Masters']/parent::*</value>
      <webElementGuid>38a158b6-2d96-4f68-b98a-834d6058578c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/ords/r/ambay_valley/donor-receipt-generation177/manage-masters?session=12384949946323')]</value>
      <webElementGuid>8e0a6b97-4f08-4228-a50f-890c1aef6ee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/a</value>
      <webElementGuid>2af92d9e-dc1b-4abd-b87d-8f10c1e9f567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ords/r/ambay_valley/donor-receipt-generation177/manage-masters?session=12384949946323' and (text() = 'Manage Masters' or . = 'Manage Masters')]</value>
      <webElementGuid>b5687be2-1b39-4eae-9efb-4a97956f58ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
