<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>3a9bd892-8de4-4e71-a672-01465919895a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add Organisation&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2a8dc301-fa24-4b49-9ba5-d3da53731416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation177/add-organisation?clear=6&amp;session=12384949946323&amp;cs=3A6kdvhPo9d6yFhgqBNBSPxxaJBHTcVlgZY1CMMK2H6gyznpp7fD1ihtCgw0yCn-JVMKg4miRYMd-ASA4npP2XA&amp;dialogCs=CpKZrs8a6L4W0--2hFGs-tBcAmQywo7LIVESQ7iFYsmpeGZElfLtNoPEVnJW9FJRvl0b-OkfjIO9vkUyfxKyrg</value>
      <webElementGuid>bba21591-a0d7-4b00-9464-e2f15be9ca54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Organisation</value>
      <webElementGuid>2d6adc52-0f40-4d48-b085-67ea67982879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>292c5d3c-712e-4061-b024-e3c54aa8158a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e9d404f5-f954-44d5-88de-9d14beca4f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>31fc0d67-8ee4-4382-8363-026070b72c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>0a8e9a9d-353a-4aa1-9bb6-5492d0b68e59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>a5c5f213-7618-45ac-a20f-df9738780033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4d815f5b-c48c-490a-af16-72859cd817d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation177/add-organisation?clear=6&amp;session=12384949946323&amp;cs=3A6kdvhPo9d6yFhgqBNBSPxxaJBHTcVlgZY1CMMK2H6gyznpp7fD1ihtCgw0yCn-JVMKg4miRYMd-ASA4npP2XA&amp;dialogCs=CpKZrs8a6L4W0--2hFGs-tBcAmQywo7LIVESQ7iFYsmpeGZElfLtNoPEVnJW9FJRvl0b-OkfjIO9vkUyfxKyrg' and @title = 'Add Organisation']</value>
      <webElementGuid>259b7240-5e71-48f1-85c9-8b796ca57ed9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
