<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Auth Person Middle Name_P6_AUTH_PERSO_230c66</name>
   <tag></tag>
   <elementGuidId>03b6f648-71ab-48c7-9570-a4ca472cd098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_AUTH_PERSON_MIDDLE_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P6_AUTH_PERSON_MIDDLE_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>038d38e6-366b-4fff-bb80-6d98eba190b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>094b6f7b-7946-4c10-905d-70632ac9c0dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_AUTH_PERSON_MIDDLE_NAME</value>
      <webElementGuid>970303df-c3d5-4c56-b3c0-831d44e8ac44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_AUTH_PERSON_MIDDLE_NAME</value>
      <webElementGuid>ca3bbde6-8ae1-472e-bf4f-405de4442800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>cbb74677-1d69-4657-ace0-cbc07c47833c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>00235c93-c7c5-4725-b5e1-48686e4e91b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>896ab420-4021-4fc8-87e8-70445ca330fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>06a26e4e-7d41-44c8-9e86-cdefa3083f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_AUTH_PERSON_MIDDLE_NAME&quot;)</value>
      <webElementGuid>0b57b93b-cad8-45b1-913c-f398c2772dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Manage Mater(Donor Receipt BJS)OLD/Page_Authorized Person Master/iframe</value>
      <webElementGuid>c1935106-a32c-4773-b989-dbf68e24df72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_AUTH_PERSON_MIDDLE_NAME']</value>
      <webElementGuid>2afc1215-f9b5-45df-9255-1689c63a4504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_AUTH_PERSON_MIDDLE_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>923be800-d81c-454a-ad54-036ffe66549b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>379757bd-561a-4cfb-9e79-b304d97d2a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_AUTH_PERSON_MIDDLE_NAME' and @name = 'P6_AUTH_PERSON_MIDDLE_NAME']</value>
      <webElementGuid>b067b239-44f7-410a-9341-4851ec10a691</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
