<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Auth Person First Name_P6_AUTH_PERSON_FIRST_NAME</name>
   <tag></tag>
   <elementGuidId>b47b84c0-1516-4d4b-bd91-1987a51e5276</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_AUTH_PERSON_FIRST_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P6_AUTH_PERSON_FIRST_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59fbb726-1a32-4a21-afa0-8f6fe6827613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9f53b77a-2d93-43ef-9585-0ee00fe008a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_AUTH_PERSON_FIRST_NAME</value>
      <webElementGuid>88c0bdc2-0eea-4eca-adda-21dfefda7815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_AUTH_PERSON_FIRST_NAME</value>
      <webElementGuid>ce19cf33-8560-4207-93bf-b242da9b69e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>c29f2f20-5b31-4585-bedc-c34ffb24545d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>826e45ca-0ea3-480f-959c-f478bcf6f930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>54dc1e83-ce6e-4589-859c-c4c0ebd3e653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>29edaf8b-74ea-4c47-8e7a-54121c255ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_AUTH_PERSON_FIRST_NAME&quot;)</value>
      <webElementGuid>8d9d63a9-3457-448b-bc69-d8519e00e1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Manage Mater(Donor Receipt BJS)OLD/Page_Authorized Person Master/iframe</value>
      <webElementGuid>49a1937a-82b6-4144-94e2-1b0d654868b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_AUTH_PERSON_FIRST_NAME']</value>
      <webElementGuid>c46257a4-4da3-4009-af43-351dadd9c3eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_AUTH_PERSON_FIRST_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>7d40cb8e-46b7-4220-ba74-e6796c15cc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>3ebfb58a-c604-419f-802d-cad2ff685e38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_AUTH_PERSON_FIRST_NAME' and @name = 'P6_AUTH_PERSON_FIRST_NAME']</value>
      <webElementGuid>e6508ac9-e492-474f-a143-5924c7c481fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
