<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Auth Person Last Name_P6_AUTH_PERSON__b07843</name>
   <tag></tag>
   <elementGuidId>dc075775-6691-4d42-96c3-ba2cbb504d12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P6_AUTH_PERSON_LAST_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P6_AUTH_PERSON_LAST_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6e6ebf1-6de5-4348-b10c-ce6bd037d9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8feb0ea-3b79-4886-8e80-a35ace3bd9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P6_AUTH_PERSON_LAST_NAME</value>
      <webElementGuid>56d01a89-372d-410a-91e1-be6258ae3b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P6_AUTH_PERSON_LAST_NAME</value>
      <webElementGuid>84d9a608-6153-4f17-a65b-21abc2441d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>79dd6417-184f-4500-aa02-4051a6266ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>04099af0-9a68-456b-8ad0-0c9c90d8380f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>e986eaf3-5d46-40bd-8e0c-e7fee55a24c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>35bbccf8-f7ff-43b3-9f41-1db1362f8c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P6_AUTH_PERSON_LAST_NAME&quot;)</value>
      <webElementGuid>f5bda5d8-ac10-4254-bc5a-6159cb500e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Manage Mater(Donor Receipt BJS)OLD/Page_Authorized Person Master/iframe</value>
      <webElementGuid>39b2bbd5-a6fa-4c67-932f-a9eea9597ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P6_AUTH_PERSON_LAST_NAME']</value>
      <webElementGuid>819c00d5-e036-4092-a6bc-3a7ba953e1ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P6_AUTH_PERSON_LAST_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>dce1a901-abf0-4089-acd8-dd4e5792af9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>1768ce4f-e7e0-47bd-82ec-44a3a9ba0c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P6_AUTH_PERSON_LAST_NAME' and @name = 'P6_AUTH_PERSON_LAST_NAME']</value>
      <webElementGuid>78fce53c-7ecb-45a1-83d3-b6f4671a1563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
