<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skip to Main Content_t_Button_navControl</name>
   <tag></tag>
   <elementGuidId>244fc77a-6fb1-4281-ad2b-67ad474e3ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='t_Button_navControl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#t_Button_navControl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90b662e8-36be-4c08-b66e-c271fae4af66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--icon t-Button--header t-Button--headerTree</value>
      <webElementGuid>857f8225-6795-4795-90ae-de1a56aa171c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>be5ae315-85fb-4935-9bf4-73ad9b9302ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>5ca6901c-f9ab-4132-84a1-5f3f8c51477c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>t_Button_navControl</value>
      <webElementGuid>d44eb4ee-4200-445d-a3ec-eb0849fdd5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e682fb5-8d4a-405d-b875-f0c2f985f7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>t_TreeNav</value>
      <webElementGuid>10674fc9-9f92-4ace-96e3-b286214afd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>29d51011-38ad-4784-be14-cafc84c4662e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_Button_navControl&quot;)</value>
      <webElementGuid>0148b597-0ac1-4136-a8bf-7aba7fe31d41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='t_Button_navControl']</value>
      <webElementGuid>d2494d97-a968-40d3-9c11-61dbb186c75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='t_Header']/div/div/button</value>
      <webElementGuid>befa1d90-d3fd-4e1f-b0b6-8f7a90702aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::button[1]</value>
      <webElementGuid>d8b553a5-65b1-4f38-baea-d0ad65aaba7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donor Receipt Generation'])[1]/preceding::button[1]</value>
      <webElementGuid>ce186f3e-e3ff-4ed7-90bf-167108814836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Install App'])[1]/preceding::button[1]</value>
      <webElementGuid>376b0dfa-2892-468f-96da-9b942af15fdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f1d2a364-13bc-481c-9786-fb36aea4c526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Main Navigation' and @id = 't_Button_navControl' and @type = 'button']</value>
      <webElementGuid>40b84a13-3c3f-4e80-8fac-b069564fb698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
