<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>d6ea41ca-b0f6-4ca5-9727-9f459f2b65a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add Organisation&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b1d6a071-aa8c-4823-bec0-5336b7752677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation/add-organisation1?clear=17&amp;session=10720524817684&amp;cs=3nWX1NpG57rKBmoiTTTsSa1M5ArotGxVZfMh4vpPTh8w8TdQI2ayL4SvhdWNb7DILioDOTRlKI0B1m6BwgVwWxg&amp;dialogCs=qzKr-XwgHnek2RKcvSe2YoVWW1MZyBgHKPhyMolx3JQZeNHYz6EBdNqybR7heB_F0YvW4ZnFd9qn1L5rIQocag</value>
      <webElementGuid>88beb897-1606-4d58-9b51-93fe013b7103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Organisation</value>
      <webElementGuid>e2fa7d60-a314-4a61-a488-8b6c1f9aa435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b6780e18-85fd-4a81-9111-c135cffb42e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>6140cb20-e7b4-4e3f-84dd-d0fdbd025790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>4e64b0c1-4f09-4f4e-bf86-e9506a8e3694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>6849b41f-9f97-46e1-801f-3712fa933926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>2e951d75-3546-4d71-97b0-4b841cfc3848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>35b52d7b-21cb-4667-a68f-3944d8fb4fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation/add-organisation1?clear=17&amp;session=10720524817684&amp;cs=3nWX1NpG57rKBmoiTTTsSa1M5ArotGxVZfMh4vpPTh8w8TdQI2ayL4SvhdWNb7DILioDOTRlKI0B1m6BwgVwWxg&amp;dialogCs=qzKr-XwgHnek2RKcvSe2YoVWW1MZyBgHKPhyMolx3JQZeNHYz6EBdNqybR7heB_F0YvW4ZnFd9qn1L5rIQocag' and @title = 'Add Organisation']</value>
      <webElementGuid>d01b2da8-d6d6-45db-92bb-608ab283a517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
