<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Auth Person Last Name_P17_AUTH_PERSON_981ad1</name>
   <tag></tag>
   <elementGuidId>e9e0de54-af1c-4c31-ac93-c7da942be6d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P17_AUTH_PERSON_LAST_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P17_AUTH_PERSON_LAST_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>22ab9ff4-1f8f-46d8-8705-6079af385191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>634e73ee-312c-4ec8-9054-1d2c336c6c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P17_AUTH_PERSON_LAST_NAME</value>
      <webElementGuid>72f9ebe2-9855-479a-a9a1-983ea7dc1800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P17_AUTH_PERSON_LAST_NAME</value>
      <webElementGuid>efd7e2c5-dd18-432e-8817-9b9f1269710e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>f33154a4-9e6d-4795-95e0-820fbde24220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>625baaa6-8408-4bbb-b88d-62eeb17ba829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>5ea19386-c6e5-4d6b-9d33-c3f7d7fecd4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>d5dfb092-206d-42d4-929d-9c31b2ad8135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P17_AUTH_PERSON_LAST_NAME&quot;)</value>
      <webElementGuid>0e4e0008-fb7f-43fc-8d03-5f5994123d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add Authorized Person Donor Receipt(Master Entries)/Page_Authorized Person Master/iframe</value>
      <webElementGuid>ccf2d3b9-2843-4224-a24e-9915d0bf851c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P17_AUTH_PERSON_LAST_NAME']</value>
      <webElementGuid>b6c27867-301d-4d89-8982-eb0dcc1eb98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P17_AUTH_PERSON_LAST_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>ce66c44a-752c-49a7-83b0-571e9fbefd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>b9d8339a-0b65-447a-bee4-cefa6f826f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P17_AUTH_PERSON_LAST_NAME' and @name = 'P17_AUTH_PERSON_LAST_NAME']</value>
      <webElementGuid>09dd29aa-037b-4081-a4bf-bd502f63cf6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
