<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Signature Photo_a-Icon icon-file-browse</name>
   <tag></tag>
   <elementGuidId>dcb8904c-b663-47fa-9434-8a2abe723a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='P17_DOC_CONTENT_DROPZONE']/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.a-Icon.icon-file-browse</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e72c3dc5-97b2-4ede-ae2d-8b6d2edc53a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Icon icon-file-browse</value>
      <webElementGuid>145a8d82-083f-4c39-a86f-6f99b1adbb6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d0fd0e2-682f-40a4-b15a-a64e5ac0ca22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P17_DOC_CONTENT_DROPZONE&quot;)/div[@class=&quot;apex-item-filedrop-icon&quot;]/span[@class=&quot;a-Icon icon-file-browse&quot;]</value>
      <webElementGuid>bdc5ffdb-65b6-4e2d-9469-6850493dd135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add Authorized Person Donor Receipt(Master Entries)/Page_Authorized Person Master/iframe</value>
      <webElementGuid>490822cc-673c-4766-87ea-6759ad3a8d2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P17_DOC_CONTENT_DROPZONE']/div/span</value>
      <webElementGuid>0d8949dc-d912-405c-a89f-93e9e8cd0b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>e849b73f-0405-46f0-aec1-83bfda126cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
