<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>8520b231-aabc-4aa3-92a3-231d45aea462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add/Edit event&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>05fc2e20-4e37-439d-95e8-b2871f935f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/social_events/social-events/add-edit-event?clear=35&amp;session=3312897903369&amp;cs=3KVrHqfbFDtVG5qU0RS52JgqIVXA8GOPjvttNr91qCs_qgGHGmwObaUT0Dw8N2sBJ3B1dy24Kox5DBjVx3LzFyQ&amp;dialogCs=b6XKEgLdn2FdxGq7ll8MuM6FpwiIPWFcZ2X1OYAfRImQxE_DrizgbGH3CvjqVHqxHmnWgzFaEsC5Q-JMA3f-7Q</value>
      <webElementGuid>8736d433-875a-4f6b-b1e5-94719e5351a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add/Edit event</value>
      <webElementGuid>972fd44d-e893-4480-bb09-8f38963f210d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>487b0f58-94cf-4d31-a856-68d749c6514d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>a9f99096-0590-454d-bb32-ee0063aaa1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>bc43d0dd-216d-48ae-8b62-a902320a5211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>188685e3-e4d9-4d9c-bb1a-f2b81fac5a6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>bcae2cdb-150f-490a-8712-6c52ff709ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>38a80266-c17b-400d-a4fa-d6a56f7dbf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/social_events/social-events/add-edit-event?clear=35&amp;session=3312897903369&amp;cs=3KVrHqfbFDtVG5qU0RS52JgqIVXA8GOPjvttNr91qCs_qgGHGmwObaUT0Dw8N2sBJ3B1dy24Kox5DBjVx3LzFyQ&amp;dialogCs=b6XKEgLdn2FdxGq7ll8MuM6FpwiIPWFcZ2X1OYAfRImQxE_DrizgbGH3CvjqVHqxHmnWgzFaEsC5Q-JMA3f-7Q' and @title = 'Add/Edit event']</value>
      <webElementGuid>72733043-feef-4ccf-a2aa-072ff2b809af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
