<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Event Name_P35_EVENT_NAME</name>
   <tag></tag>
   <elementGuidId>e2a1d0ae-037d-4632-a248-4a1c3e668bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P35_EVENT_NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P35_EVENT_NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c690da77-86aa-4464-986d-ae6a4c9c29d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e516450-ddca-45d2-8ef9-cb9e3e7b5ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P35_EVENT_NAME</value>
      <webElementGuid>fe48b4d0-fda8-4d9d-8f64-068ae5fe1dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P35_EVENT_NAME</value>
      <webElementGuid>38b7c106-ecfc-4f93-8f51-b92d35604a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>e96606e8-aa45-44e6-84ce-c89d3ae3fefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>4a67a5e4-9760-499f-9949-02c16ad8fb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>13194092-7c47-4d34-9291-6f2fbe966640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>97aada6e-fac9-43dd-8946-54cf16ffa4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P35_EVENT_NAME&quot;)</value>
      <webElementGuid>93d34e72-7ad0-4736-abe7-f2cc3427d024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Event Create(Social Event)/Page_Event Master/iframe</value>
      <webElementGuid>4dedccc2-993f-412f-a43d-49c651c89733</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P35_EVENT_NAME']</value>
      <webElementGuid>6a666d1d-6b73-4eea-bdbe-b3545c9229a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P35_EVENT_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>c72adda8-44b0-4a0c-9907-eee8cbe2bc9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>d8c86ba8-4d50-49c2-ab96-489ef2520c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P35_EVENT_NAME' and @name = 'P35_EVENT_NAME']</value>
      <webElementGuid>f6561f63-b56a-4401-887d-474f41e002cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
