<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Start Date_P35_START_DATE</name>
   <tag></tag>
   <elementGuidId>87f7477d-a7ef-46f7-9e89-dd9eb9485893</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P35_START_DATE_input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P35_START_DATE_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32f4501a-1d20-4fb5-93b0-fa7ee0a720e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>15846834-9338-4d16-bd0a-9e899f533237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-text apex-item-datepicker</value>
      <webElementGuid>1302b260-5c07-4c70-b66d-f78e738c5331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P35_START_DATE</value>
      <webElementGuid>d1cbcf56-956b-41d9-afa7-75a3d403c8ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>844fcd5f-53d8-4212-b987-add183b152ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e1d06b8-d23b-489f-8cb5-810223e86b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P35_START_DATE_input</value>
      <webElementGuid>5aca49a8-4260-4dba-9cce-bb61991ac595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>P35_START_DATE_LABEL</value>
      <webElementGuid>57d8064c-5c21-46aa-9da5-e26396e7bdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>e9a8f174-417f-49b7-b762-e24caed9bda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>45fef11c-7f5c-4500-bbef-542f7302481e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P35_START_DATE_input&quot;)</value>
      <webElementGuid>2b28b6ce-fa05-4059-9f4c-d3de79c9bd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Event Create(Social Event)/Page_Event Master/iframe</value>
      <webElementGuid>fdaf64cc-d394-4138-9a13-f073d33b3ae3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P35_START_DATE_input']</value>
      <webElementGuid>6c481ba9-45b7-4e3f-8dbc-7720ca3134c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a-date-picker[@id='P35_START_DATE']/input</value>
      <webElementGuid>6f5804b7-2dd7-458c-b6b5-7187dfd317fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a-date-picker/input</value>
      <webElementGuid>0afe10d2-459a-4bf8-8d93-8491a078e67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'P35_START_DATE' and @type = 'text' and @id = 'P35_START_DATE_input']</value>
      <webElementGuid>efd88668-c99c-4ae2-b4f3-660899569466</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
