<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Kishor Shevkar</name>
   <tag></tag>
   <elementGuidId>f1b1360f-55b7-4055-a91a-ebfbe0216d18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='P35_SUPPORTIVE_ORG_ID']/div/div[2]/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b7676c8f-02f4-406d-92f4-2fbbdee52b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-checkbox</value>
      <webElementGuid>b75e45d0-a1d1-49c7-ab3d-f591b65df34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>P35_SUPPORTIVE_ORG_ID_4</value>
      <webElementGuid>2ac95ab0-c329-4c40-bd3f-2011fa5eb36e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9b8459f1-34f6-451f-86c4-7443c141c89b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kishor Shevkar</value>
      <webElementGuid>c50a30b7-5ac6-443a-963a-e3c830caeaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P35_SUPPORTIVE_ORG_ID&quot;)/div[@class=&quot;apex-item-grid checkbox_group&quot;]/div[@class=&quot;apex-item-grid-row&quot;]/div[@class=&quot;apex-item-option&quot;]/label[@class=&quot;u-checkbox&quot;]</value>
      <webElementGuid>bd31c4ae-7ef5-48f0-894e-dd61b157db58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Event Create(Social Event)/Page_Event Master/iframe</value>
      <webElementGuid>dfc41b62-57c2-4099-8835-62cf0f5ab3fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P35_SUPPORTIVE_ORG_ID']/div/div[2]/div[2]/label</value>
      <webElementGuid>90bc1531-851f-4127-946d-0777d3d124c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Supportive Organiser Name'])[1]/following::label[5]</value>
      <webElementGuid>d1c34935-5b0f-44eb-950d-f3567be29c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::label[6]</value>
      <webElementGuid>264f5a04-e014-4b8e-876c-c7a1fccada15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QR Code Upload'])[1]/preceding::label[6]</value>
      <webElementGuid>f099038e-796b-4833-b00d-056a30b6baa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choose File'])[1]/preceding::label[7]</value>
      <webElementGuid>a4cbc4f2-b2d3-4343-9480-6fb0e30d7867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/label</value>
      <webElementGuid>5466c55b-9982-4745-a8b3-2caa076d6084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Kishor Shevkar' or . = 'Kishor Shevkar')]</value>
      <webElementGuid>97469ff8-eef6-4f7c-a429-156f2a965952</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
