<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_ANDAMAN  NICOBAR ISLANDS</name>
   <tag></tag>
   <elementGuidId>9b1e6a2c-5081-4ab8-80f4-5a4be7a8cfdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.a-IconList-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupLov_35_P35_STATE_dlg']/div[3]/div/div[3]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2d791577-e425-41ec-b286-0e39982f2b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>81</value>
      <webElementGuid>a7b0d03f-2392-4b64-be3d-8dcde413dd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IconList-item</value>
      <webElementGuid>3910f77e-c864-4b40-9c04-d3230cc582a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>b9d045e9-ed0f-4bfc-9fd8-073e8bfc9b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b951f562-b5f4-46bf-9882-6a7152d3770b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ANDAMAN &amp; NICOBAR ISLANDS</value>
      <webElementGuid>cd091a8c-3bc3-4bf8-918e-62842d40d588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupLov_35_P35_STATE_dlg&quot;)/div[@class=&quot;a-PopupLOV-results a-TMV&quot;]/div[@class=&quot;a-TMV-body&quot;]/div[@class=&quot;a-TMV-w-scroll&quot;]/ul[@class=&quot;a-IconList&quot;]/li[@class=&quot;a-IconList-item&quot;]</value>
      <webElementGuid>a3fb901d-ed52-4835-8972-243a8bed260a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupLov_35_P35_STATE_dlg']/div[3]/div/div[3]/ul/li</value>
      <webElementGuid>e710cb21-8679-4aaa-b5ae-441d6803e877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[1]/following::li[1]</value>
      <webElementGuid>87d3fd86-3c3f-4b5e-b6f1-b7f875853381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--Select Any--'])[1]/following::li[1]</value>
      <webElementGuid>a0ae0009-8ca0-4b28-895f-d535551e0988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANDHRA PRADESH'])[1]/preceding::li[1]</value>
      <webElementGuid>89d3dfdc-e64a-4144-bb20-673fcbca0aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARUNACHAL PRADESH'])[2]/preceding::li[2]</value>
      <webElementGuid>b06a0d8c-660c-4f51-bda3-8ea9346f7524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li</value>
      <webElementGuid>e698f7a5-5360-43ed-840b-151c42da0bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'ANDAMAN &amp; NICOBAR ISLANDS' or . = 'ANDAMAN &amp; NICOBAR ISLANDS')]</value>
      <webElementGuid>2ad24ec0-74b5-4fa9-bb86-fa543d04313a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
