<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign Out</name>
   <tag></tag>
   <elementGuidId>5c94ffeb-80db-4e6a-9cd0-ddfbb3ebf05e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_L238282817415005284_3i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_L238282817415005284_3i']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d248999-cc24-4e11-85e1-a4aff157b436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>apex_authentication.logout?p_app_id=184&amp;p_session_id=6623388300990</value>
      <webElementGuid>a03eda30-510c-41b2-9c7f-914b6d65c82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_L238282817415005284_3i</value>
      <webElementGuid>6cdcb67c-c40f-47ba-8dc8-0822bb166262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>89fcf714-acb9-447b-a821-590da37c04f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Menu-label</value>
      <webElementGuid>e6f3b039-a899-4997-87d1-9f5b5f4f84e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Out</value>
      <webElementGuid>3a24beaf-57e8-4807-a93d-718793ba55bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_L238282817415005284_3i&quot;)</value>
      <webElementGuid>f0568dc5-a93c-4392-949e-94889cc4b693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_L238282817415005284_3i']</value>
      <webElementGuid>c61a4b96-9b2d-4850-8cef-a73a1324b482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu_L238282817415005284_3']/div/span/a</value>
      <webElementGuid>0e25fa1f-3c67-4a78-bdbc-4366f5b047a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign Out')]</value>
      <webElementGuid>ee688ac6-4342-4ffc-aa28-a602b1808006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/following::a[1]</value>
      <webElementGuid>f9ff0f4b-e4ee-483e-99bb-2242dba28994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Team Roles'])[1]/following::a[2]</value>
      <webElementGuid>098b6595-3bd8-4ad5-80fe-7e31a06f7362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'menu_L238282817415005284_3i', '&quot;', ')')])[1]/preceding::a[1]</value>
      <webElementGuid>aa0ef75f-61a2-4bec-ae84-c7708ad424a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign Out']/parent::*</value>
      <webElementGuid>0bc7fd9d-0af7-47ec-8bd7-186cf0747a9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'apex_authentication.logout?p_app_id=184&amp;p_session_id=6623388300990')]</value>
      <webElementGuid>6753d001-e107-4971-a600-e5fbb1bd80fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/span/a</value>
      <webElementGuid>e0bc0933-35ac-4a35-ac17-011d526a8966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'apex_authentication.logout?p_app_id=184&amp;p_session_id=6623388300990' and @id = 'menu_L238282817415005284_3i' and (text() = 'Sign Out' or . = 'Sign Out')]</value>
      <webElementGuid>de4efdfd-961f-4be4-b860-dd502801f48a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
