<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>773c5919-25fd-4a7a-9953-68086b4e53da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Attendance Sheet&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5cf42048-6a16-4f51-bd16-fa924bc7c4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/attendance-sheet?p311_meeting_id=162&amp;clear=311&amp;session=6623388300990&amp;cs=19hrkLJRqBmZQynpto4EEFNMwnrFSWgvQ2A9wVSJoZ1IqQffrGbNHOpQQPKFOHP43SGcOI0YEnkVtrq2dZZfl8w&amp;dialogCs=HwWe6neAVXOEXA48XiFzm9Ub0cAuGPlgHd2ahvGYR6DG8syXIHb5ZMIc9KagyDcH09JpJFAK_JlBO8jwlv_vuA</value>
      <webElementGuid>c892e571-fea1-4062-88c2-8801f171b28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Attendance Sheet</value>
      <webElementGuid>52cc332f-c83a-4ce7-9de7-58cc39c36215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>1759d580-1614-4b57-8ce6-73025680d7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>aeda64a3-e257-4aba-90c7-38033980a1b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>780a00d3-3a6c-4162-bec8-6c3b7982b752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>4700f732-c53f-4992-a5a2-5610327fef52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>bed7b0fc-2883-49a7-b1d7-b748b8ff4c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>160342b5-1773-46a1-bda3-51af09b24e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/attendance-sheet?p311_meeting_id=162&amp;clear=311&amp;session=6623388300990&amp;cs=19hrkLJRqBmZQynpto4EEFNMwnrFSWgvQ2A9wVSJoZ1IqQffrGbNHOpQQPKFOHP43SGcOI0YEnkVtrq2dZZfl8w&amp;dialogCs=HwWe6neAVXOEXA48XiFzm9Ub0cAuGPlgHd2ahvGYR6DG8syXIHb5ZMIc9KagyDcH09JpJFAK_JlBO8jwlv_vuA' and @title = 'Attendance Sheet']</value>
      <webElementGuid>7ef6f723-b6c6-4c13-a091-692b074adf9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
