<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Whatsapp Number_P311_WHATSAPP_NUMBER</name>
   <tag></tag>
   <elementGuidId>cad043c0-8131-412f-bb01-58bdf70600c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P311_WHATSAPP_NUMBER</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P311_WHATSAPP_NUMBER']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb0aaad7-9413-4552-ac6f-37e796ec302b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfaa4bf3-26b0-431f-ac80-27cdf3531ca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P311_WHATSAPP_NUMBER</value>
      <webElementGuid>04064337-1ea3-4dde-a6c2-121c5f261b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P311_WHATSAPP_NUMBER</value>
      <webElementGuid>7aa3ed4c-d4ba-4e36-9074-6a190424f3ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number</value>
      <webElementGuid>71f5bad6-19e5-4049-943d-7860107f766c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>109d66df-84fa-416c-81b3-4a6bac38bc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1fe72efc-3fb7-4e19-a4f3-03b2f656c590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f0a19ad-5606-4664-aa63-a874fef72faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P311_WHATSAPP_NUMBER&quot;)</value>
      <webElementGuid>e391fb03-1be7-4506-b7d0-de07360b2da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Page_View Meetings/iframe</value>
      <webElementGuid>34e7e6e4-c877-493f-93b8-33d8b36c309e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P311_WHATSAPP_NUMBER']</value>
      <webElementGuid>7d0c13a0-80cc-476a-b015-fad4f00d7ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P311_WHATSAPP_NUMBER_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>f5eb564e-b5c1-42fe-9445-d577370328e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>8d710586-ef53-49a0-a81a-33b3cec6e791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P311_WHATSAPP_NUMBER' and @name = 'P311_WHATSAPP_NUMBER']</value>
      <webElementGuid>013e453e-7603-41e2-ba96-04ff80118150</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
