<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P311_NAME_OF_ATTENDEE</name>
   <tag></tag>
   <elementGuidId>bcc436da-80a0-4807-9ae6-306de23419d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P311_NAME_OF_ATTENDEE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P311_NAME_OF_ATTENDEE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70909806-4cb8-400d-8c76-0fcbaca61223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66f71de9-9d6e-4d42-a5e1-00c9dad04f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P311_NAME_OF_ATTENDEE</value>
      <webElementGuid>4865cead-c2ae-414a-9fab-c4b84affe4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P311_NAME_OF_ATTENDEE</value>
      <webElementGuid>aa7203e0-a2fb-43fa-bb8d-cae93ac1b2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>76463548-f560-4f31-94d9-ce82a77e2c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>3265e294-8f78-4a71-8660-a3b3aefa5c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>76d1e0a8-4b06-4a6f-81f2-72c521f6f609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>5ef80f91-f978-4025-a853-ef89e66a3b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P311_NAME_OF_ATTENDEE&quot;)</value>
      <webElementGuid>1687e701-1d5d-46f5-a169-4343d75b8ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Page_View Meetings/iframe</value>
      <webElementGuid>2ff525b7-e645-4b86-bf3f-c63e3c5cc1e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P311_NAME_OF_ATTENDEE']</value>
      <webElementGuid>93c9e62c-5972-4740-ac84-0b894ebde821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P311_NAME_OF_ATTENDEE_CONTAINER']/div[2]/div[2]/input</value>
      <webElementGuid>61590dc6-49be-4d16-a621-07c493f32018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>38f64b57-67ab-44c5-8551-45f3af64b236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P311_NAME_OF_ATTENDEE' and @name = 'P311_NAME_OF_ATTENDEE']</value>
      <webElementGuid>3f7540e2-321f-4aed-bb54-e7ef6291ad2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
