<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Form</name>
   <tag></tag>
   <elementGuidId>b086468e-08c7-4db3-bc2e-78d085ff26f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B230191122416464574 > span.t-Button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B230191122416464574']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>40840f92-24b0-4030-8a3e-ede33c443b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button-label</value>
      <webElementGuid>bb3fda4e-3f82-419a-9121-b2015cae6d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form</value>
      <webElementGuid>5ced67a2-3d26-4953-bf29-90d400c37296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B230191122416464574&quot;)/span[@class=&quot;t-Button-label&quot;]</value>
      <webElementGuid>73e467cf-ccc4-47da-a976-2d7a571feae1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='B230191122416464574']/span</value>
      <webElementGuid>e9f1c3a2-71c9-4ec5-afc7-23ebddc1d085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attendee'])[3]/following::span[1]</value>
      <webElementGuid>2c1173d8-e283-43e7-a78e-c84fca70ac8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Follow-up'])[1]/following::span[3]</value>
      <webElementGuid>3217620f-e7ad-459c-bb0b-154a86b42948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Observation Points'])[2]/preceding::span[4]</value>
      <webElementGuid>18051bda-f7e9-4233-8da5-82f5a9087464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add/Edit Observation'])[1]/preceding::span[4]</value>
      <webElementGuid>fb46c441-91ce-4ea4-ae70-1927dd1d7f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Form']/parent::*</value>
      <webElementGuid>0d772750-96a4-4d19-b4ac-03d8fdb5e5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button/span</value>
      <webElementGuid>6f755d1a-17da-47b4-ad5b-e7522e1e7c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Form' or . = 'Form')]</value>
      <webElementGuid>e939f3ec-b6fa-4820-82fb-55b674b0cfa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
