<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Nicobars</name>
   <tag></tag>
   <elementGuidId>6bd36820-356d-4609-9aad-1333d95de95f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PopupLov_37_P37_DISTRICT_dlg > div.a-PopupLOV-results.a-TMV > div.a-TMV-body > div.a-TMV-w-scroll > ul.a-IconList > li.a-IconList-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupLov_37_P37_DISTRICT_dlg']/div[3]/div/div[3]/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>eac427cc-d438-4f05-8ca1-99659f9419e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>658</value>
      <webElementGuid>dc3a3b7e-8c39-4f04-9466-745751578567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IconList-item</value>
      <webElementGuid>c0f98e78-18f6-4c69-89e5-644629154a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>bf607fd9-48f0-4e5a-ae88-1201aff0ec09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b2659614-024a-45dc-adcc-c4d3d54436fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nicobars</value>
      <webElementGuid>6ed798fd-e73d-452e-b51a-6e5ab4dec7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupLov_37_P37_DISTRICT_dlg&quot;)/div[@class=&quot;a-PopupLOV-results a-TMV&quot;]/div[@class=&quot;a-TMV-body&quot;]/div[@class=&quot;a-TMV-w-scroll&quot;]/ul[@class=&quot;a-IconList&quot;]/li[@class=&quot;a-IconList-item&quot;]</value>
      <webElementGuid>a14fc604-f952-4e0b-af8a-ba1758e7bd2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupLov_37_P37_DISTRICT_dlg']/div[3]/div/div[3]/ul/li</value>
      <webElementGuid>96d3e3b5-1882-481b-bf13-4663d4d38e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No results found.'])[2]/following::li[1]</value>
      <webElementGuid>ce4e1c73-5283-47c3-9bd5-40c7624874ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--Select Any--'])[2]/following::li[1]</value>
      <webElementGuid>26ccabe6-c961-4076-8266-909208e8ff2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='South Andaman'])[1]/preceding::li[2]</value>
      <webElementGuid>470e0e40-099a-40a8-af6f-869b331c5775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/div[3]/div/div[3]/ul/li</value>
      <webElementGuid>89fbc3e4-329c-4f96-ab75-e4e19976cc2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Nicobars' or . = 'Nicobars')]</value>
      <webElementGuid>24852b34-613b-42e0-b9b5-c235a26b6ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
