<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Address_P37_ADDRESS</name>
   <tag></tag>
   <elementGuidId>fbf74efe-a18a-4b26-92c2-6776608c7faa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P37_ADDRESS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='P37_ADDRESS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>3bdf5b6c-c256-4ac8-800b-e62b5ce209a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P37_ADDRESS</value>
      <webElementGuid>2861d56d-5c15-4401-a8f9-3926f113e883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3afbddee-9c1e-4f2d-8dfc-a411829d6b52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>257ded50-6bcb-4da3-9445-9d9aa0f50829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>091cc53e-0f36-4aa7-a19d-ea25716303ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P37_ADDRESS</value>
      <webElementGuid>2c40f5ff-35a4-4f18-bc2d-4de4c0f3f786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea apex-item-textarea</value>
      <webElementGuid>91d2feb6-2b19-4ac6-a122-979d287f9feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resizable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8839bcbe-f424-467d-8006-825c2e84e5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P37_ADDRESS&quot;)</value>
      <webElementGuid>0284cf09-283e-4bf7-bd20-e3830a88af45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Master (Organizer master)Social Event/Page_Organizer Master/iframe</value>
      <webElementGuid>a118e395-58fc-4661-90e1-9a88a40ee285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='P37_ADDRESS']</value>
      <webElementGuid>4173bc51-03ba-41b9-9306-d1d9d72e14c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P37_ADDRESS_CONTAINER']/div[2]/div/div/textarea</value>
      <webElementGuid>13905792-bdcf-4db9-aacf-16060776fe8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>e05f7839-0c4c-4fd5-a646-e018be2cdc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'P37_ADDRESS' and @id = 'P37_ADDRESS']</value>
      <webElementGuid>9931bd33-239b-4371-a571-8c9d48ef9319</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
