<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>fd03f083-2bd0-4fea-a435-7ed85e069d2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add Organisation&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f78ef7d0-8f3b-4732-8415-bb766e2d6db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation177/add-organisation?p6_id=41&amp;clear=RP&amp;session=8383155275837&amp;cs=3GYNMcRIovo7QG4HkBoDBLbC-qmAPIgGMcCXK9O33K0d_swMZIz1DfyyRWeG5lDEHB3yQi1A3TjASjCs2MSK51w&amp;dialogCs=sutobR1xdjZeGFElkk_4H4nmiLruCmpYzMqxgf_0Y6Zx4nhNYDTZVDQ9TVkquZanyZC65V9_VKbrjsTNDaIVnA</value>
      <webElementGuid>b38ce095-d32a-4147-9746-d9b2bd1d9b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Organisation</value>
      <webElementGuid>ce4f2bbd-d8bc-4c92-82cd-82472599db7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3dd948cb-f21c-4a5b-b70a-39049afe6301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8822b825-70cb-48b9-a0d6-a0b07a039d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c23f594e-7847-4b5a-92a0-d74f24f2f876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>60dc1e29-6fd8-454f-b1cb-a4d7a6700a7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>f56c3f28-012a-457b-b251-261f27383282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7e34da94-c92a-45aa-86cf-8529ee67f6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation177/add-organisation?p6_id=41&amp;clear=RP&amp;session=8383155275837&amp;cs=3GYNMcRIovo7QG4HkBoDBLbC-qmAPIgGMcCXK9O33K0d_swMZIz1DfyyRWeG5lDEHB3yQi1A3TjASjCs2MSK51w&amp;dialogCs=sutobR1xdjZeGFElkk_4H4nmiLruCmpYzMqxgf_0Y6Zx4nhNYDTZVDQ9TVkquZanyZC65V9_VKbrjsTNDaIVnA' and @title = 'Add Organisation']</value>
      <webElementGuid>a18c524a-d590-4fb9-be02-7535d8533556</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
