<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Meeting- Calendar_fc-icon fc-icon-chev_0efa78</name>
   <tag></tag>
   <elementGuidId>0d0ada1e-3917-4dab-a484-aedbbdcfec53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fc-icon.fc-icon-chevron-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='R238373431837570428_calendar']/div[3]/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d287e356-3f9a-49c2-83b4-cda2105cce36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fc-icon fc-icon-chevron-left</value>
      <webElementGuid>2f47fc67-1220-4984-b942-8a0d35e95b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R238373431837570428_calendar&quot;)/div[@class=&quot;fc-header-toolbar fc-toolbar&quot;]/div[@class=&quot;fc-toolbar-chunk&quot;]/div[@class=&quot;fc-button-group&quot;]/button[@class=&quot;fc-prev-button fc-button fc-button-primary&quot;]/span[@class=&quot;fc-icon fc-icon-chevron-left&quot;]</value>
      <webElementGuid>265cd44d-778d-4ac3-9488-825404382b93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R238373431837570428_calendar']/div[3]/div/div/button/span</value>
      <webElementGuid>9681dc8d-e9d3-43f7-9ea7-ff3dfccc2544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button/span</value>
      <webElementGuid>f6bc8436-602c-4118-84af-fe8221638faf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
