<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P102_PROJECT_NAME</name>
   <tag></tag>
   <elementGuidId>4e2a40e0-302e-42c1-bc8a-f62feb88f583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P102_PROJECT_NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P102_PROJECT_NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e88b51f6-6385-4d3f-a4f7-f11db03d4e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fce4eed9-6b4f-4b4e-b763-7db37077ec9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P102_PROJECT_NAME</value>
      <webElementGuid>7675fc4a-21dd-410f-a27f-99d366d8af6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P102_PROJECT_NAME</value>
      <webElementGuid>3dcf2217-837e-4309-b5e8-966577b0e349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>25ebae39-dbc5-4fda-863d-8530991427bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>d3164e29-c0b9-45df-b223-deec9e4c9cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>65005b29-d696-4a8a-b18d-6ca36a75a670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P102_PROJECT_NAME&quot;)</value>
      <webElementGuid>24cf4c9a-be1f-446d-87e4-2976f695f9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Page_Project List/iframe</value>
      <webElementGuid>d47132a7-bcc3-441d-aef0-9a4eb8496a4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P102_PROJECT_NAME']</value>
      <webElementGuid>a4ee5f24-c1d0-406d-87db-fd156186323f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P102_PROJECT_NAME_CONTAINER']/div[2]/div[2]/input</value>
      <webElementGuid>c1dc0763-e9a9-41e2-803f-ea7c8ed71ec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>bca6846c-366d-492a-a8b7-36520ca4d427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P102_PROJECT_NAME' and @name = 'P102_PROJECT_NAME']</value>
      <webElementGuid>7793e883-d12a-4b11-bbc6-75bf1e02352f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
