<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add Project</name>
   <tag></tag>
   <elementGuidId>1805cb9f-1f18-4845-ae8e-24f5dedcc626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B238323283785140821 > span.t-Button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B238323283785140821']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>14a72bcf-23e4-4377-86de-fdfeb7981203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button-label</value>
      <webElementGuid>82620f1b-0934-48e1-aa2f-d976ed2d5dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Project</value>
      <webElementGuid>b3a25a7f-2217-42fa-a8ed-f95372ab7f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B238323283785140821&quot;)/span[@class=&quot;t-Button-label&quot;]</value>
      <webElementGuid>13b1398e-f183-43cc-a869-bdfe7e460ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='B238323283785140821']/span</value>
      <webElementGuid>243e94ec-42e8-404f-ac0d-d211c669f09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/following::span[1]</value>
      <webElementGuid>7ab05009-11a1-4128-aaf2-d8fe53524a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/following::span[2]</value>
      <webElementGuid>71399b3b-03bf-486a-bd24-2c63954fee5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Link'])[1]/preceding::span[1]</value>
      <webElementGuid>0b63c4c6-9324-4869-9a51-6af5b09f1a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organisation'])[1]/preceding::span[2]</value>
      <webElementGuid>cbf21f4d-7e80-4f96-b087-6346a57b844c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Project']/parent::*</value>
      <webElementGuid>c3dd7c16-5724-4577-a86c-cda5350df9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>6bb40972-c9d5-47cc-9933-3c1f00e8765a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add Project' or . = 'Add Project')]</value>
      <webElementGuid>d2f2a991-2996-4557-bdf7-86c6aad4af25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
