<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Skip to Main Content_t-Header-controlsIcon</name>
   <tag></tag>
   <elementGuidId>b06de6a1-a08b-4b80-a2b3-8146bdc5f9ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='t_Button_navControl']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.t-Header-controlsIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a6272998-9d52-457e-97d9-c9b4c3a894b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Header-controlsIcon</value>
      <webElementGuid>533edd71-321d-4299-99e8-fd4ffc56191f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e2423649-cb10-4e68-aa7a-18966eb28eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_Button_navControl&quot;)/span[@class=&quot;t-Header-controlsIcon&quot;]</value>
      <webElementGuid>986769f2-0e19-44bf-a122-c384fc0f2fdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='t_Button_navControl']/span</value>
      <webElementGuid>35387f2f-a673-498e-8de0-e3ea3cae7035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>7d2eb8d6-173e-434d-a484-c146da96c6a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
