<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>e8570ac6-286b-4b51-af41-d8a4f8af11fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Payment Details&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>061ad193-a703-49f3-bc46-859e26e5422f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation/payment-details?p8_donor_id=&amp;p8_org_id=148&amp;clear=8&amp;session=6665007892685&amp;cs=1mbk-U_xk8RccCEz0vwMsIaa94wLlibiSozZ1ZqoU5P9pqBRnhIz2Mn05yzaYy5Ey6xQE59-tuKfvnxONiVrdqA&amp;dialogCs=D6SEZAWe8Tv7MhM72i8mMmC6xc5wJnL_ZlYnznhGnEDR3QB90mNWZLYVsAOf2iiy-7inR8YntLpqWvz5pTU0oQ</value>
      <webElementGuid>f851a381-2dce-423a-95e1-5bd69f54c02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Payment Details</value>
      <webElementGuid>2f0ca9e7-6f22-4844-9c47-ffb08aa16a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>6a811680-da87-46b8-bf4a-e152f38cae8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3a4e48d5-ca19-4c6f-bbef-cac540f3634b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>cbcb6013-594e-401a-a41e-03d78a2d8c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>fd7b3aa6-1d6a-48f0-a4f5-223daa27e659</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>255c1a56-d428-4941-95fc-8e13ff110fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d2af739a-a784-4f19-9bca-622f171965f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation/payment-details?p8_donor_id=&amp;p8_org_id=148&amp;clear=8&amp;session=6665007892685&amp;cs=1mbk-U_xk8RccCEz0vwMsIaa94wLlibiSozZ1ZqoU5P9pqBRnhIz2Mn05yzaYy5Ey6xQE59-tuKfvnxONiVrdqA&amp;dialogCs=D6SEZAWe8Tv7MhM72i8mMmC6xc5wJnL_ZlYnznhGnEDR3QB90mNWZLYVsAOf2iiy-7inR8YntLpqWvz5pTU0oQ' and @title = 'Payment Details']</value>
      <webElementGuid>191bcc26-c354-4f13-9f51-a35226b8be44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
