<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Received Date_P8_RECEIVED_DATE</name>
   <tag></tag>
   <elementGuidId>37d9b2ff-4f6c-4192-ab28-671875f824a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P8_RECEIVED_DATE_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P8_RECEIVED_DATE_input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40efa309-3451-462c-8772-2c8c79cc25c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>be463c89-b2ed-46e1-b8e8-26f9eef36fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-item-text apex-item-datepicker</value>
      <webElementGuid>ce0a7c36-029e-49a6-8015-177da4f50ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P8_RECEIVED_DATE</value>
      <webElementGuid>9fa068cd-7708-4806-a6b0-81a5bf71bb56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>58565a53-7fc0-42be-87d7-fe74019b3418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f58b937-c6ee-4e2d-9121-0536090da552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P8_RECEIVED_DATE_input</value>
      <webElementGuid>9b76e5ce-d16f-4a23-b254-2f8e6e4425bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>P8_RECEIVED_DATE_LABEL</value>
      <webElementGuid>87b0baf5-2cc7-40eb-8676-8caee1ad424f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>b61b0167-5743-4422-a2bc-2e27d5aee0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8db18109-9230-4ac2-b5de-b52f0b1a79f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P8_RECEIVED_DATE_input&quot;)</value>
      <webElementGuid>77ddadee-b0f4-4049-bde5-83f4b3680bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Receipt Generate SMF User(Donor Receipt)/Page_Receipt_details/iframe</value>
      <webElementGuid>6e59eb84-ff35-4cba-902d-dfab58050484</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P8_RECEIVED_DATE_input']</value>
      <webElementGuid>77c8684f-9f7f-4d53-84d5-cffdada79105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a-date-picker[@id='P8_RECEIVED_DATE']/input</value>
      <webElementGuid>bffa8ddc-0e0b-4442-b1a4-931fac91ced0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a-date-picker/input</value>
      <webElementGuid>8ab4c281-14be-4c4e-967c-3f522a478058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'P8_RECEIVED_DATE' and @type = 'text' and @id = 'P8_RECEIVED_DATE_input']</value>
      <webElementGuid>9ffa406b-ec19-4f65-8bfb-ba0ac1a8bd3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
