<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referance Number_P8_REFERANCE_NUMBER</name>
   <tag></tag>
   <elementGuidId>672d9ebe-faf8-4f70-9bfa-5fa5e7beaa7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P8_REFERANCE_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P8_REFERANCE_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49a5c095-c83d-4f4a-9639-7f482834a97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c38dc6fd-f923-418e-9ed7-f1c6196f9ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P8_REFERANCE_NUMBER</value>
      <webElementGuid>ebe27e6d-3586-4526-a9b3-8eab18d67a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P8_REFERANCE_NUMBER</value>
      <webElementGuid>2a3081d3-6019-4aab-b56c-375615855bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>5b0707cd-6493-4336-a263-8b69fa33f1ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>7d36885c-7256-4821-9b08-0b637ad75c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>2a4d029c-a0ca-483c-8f07-286e22845bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>590a8eeb-1d1a-4dd6-ae0e-17918cb78254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P8_REFERANCE_NUMBER&quot;)</value>
      <webElementGuid>ff94396a-8f67-4611-a74c-9c0d1887150d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Receipt Generate SMF User(Donor Receipt)/Page_Receipt_details/iframe</value>
      <webElementGuid>52a50a17-9da7-4ebb-b666-baad7636bfa8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P8_REFERANCE_NUMBER']</value>
      <webElementGuid>28d20746-a191-44ef-968f-3281ee4e2d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P8_REFERANCE_NUMBER_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>55095bdc-4d88-454a-8278-d33042bbf60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>be1bf8e2-f57e-4b0d-82b7-45c0e74fff36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P8_REFERANCE_NUMBER' and @name = 'P8_REFERANCE_NUMBER']</value>
      <webElementGuid>cb82ac2d-1f98-44cb-a60e-5ea84b107477</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
