<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Reset</name>
   <tag></tag>
   <elementGuidId>bb57fa9e-e6e5-4fc5-8529-486c646bcf96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B158579864657934438</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B158579864657934438']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a4d70cc-6ee9-4fa0-be34-f8abdda395f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button js-ignoreChange t-Button--success t-Button--simple t-Button--gapLeft</value>
      <webElementGuid>2e374168-8cd7-4fb1-9343-a5f80ebeca28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b957694-81e8-44c3-80e8-183a2e3d290f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B158579864657934438</value>
      <webElementGuid>76b858ea-e821-41e1-845c-c951c4560f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reset</value>
      <webElementGuid>f3469ad2-b921-4ffa-bbf4-dc8c7c82fac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B158579864657934438&quot;)</value>
      <webElementGuid>3f66040b-1fe7-4274-bede-fb2e012ffd59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='B158579864657934438']</value>
      <webElementGuid>ee1e9e15-ad98-49b9-a8e1-8ab37edb4b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R158359682971537775']/div[2]/div/div[2]/button[2]</value>
      <webElementGuid>738f8bdc-c30a-415b-96fb-3257bcf91a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::button[1]</value>
      <webElementGuid>6980ff74-2b77-43d3-a4e9-6ffabd649beb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Criteria'])[1]/following::button[2]</value>
      <webElementGuid>1bde667c-676b-4fe7-828b-d57d396a8085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::button[1]</value>
      <webElementGuid>97e118a6-4c68-4fd9-a05b-727c2ead4c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>5cb1ac07-772c-4b98-9231-0141a0dc9faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'B158579864657934438' and (text() = 'Reset' or . = 'Reset')]</value>
      <webElementGuid>378278d5-6d5f-489e-9599-f6596cb9625d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
