<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Donor Type_P3_DONOR_TYPE_lov_btn</name>
   <tag></tag>
   <elementGuidId>62b54af9-4165-4d2f-8773-c6f4688ca9fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P3_DONOR_TYPE_lov_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P3_DONOR_TYPE_lov_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0bbdd639-6839-403e-89bb-0c0fada425a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de9401d5-cedd-42d2-a15e-0332a0343984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8a857378-d6c0-43ca-a91f-2a26242b6219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Button--popupLOV</value>
      <webElementGuid>edd6f1b0-edf3-4dc5-ae0e-20fecfa1434c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_DONOR_TYPE_lov_btn</value>
      <webElementGuid>7b44268d-84cd-4022-9a81-9e86bcecbc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>65fc9c09-6c71-4130-9ca2-4981ef1db2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_DONOR_TYPE_lov_btn&quot;)</value>
      <webElementGuid>4defab90-c1e1-43c6-96ae-3081e605145b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Donor Adding(Donor Receipt)/Page_Donor Details/iframe</value>
      <webElementGuid>22966e49-14a7-4ebd-b6bc-4faafd27fd3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='P3_DONOR_TYPE_lov_btn']</value>
      <webElementGuid>c88215a8-a281-46ae-bb8a-6440745101bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_DONOR_TYPE_CONTAINER']/div[2]/div/div/button</value>
      <webElementGuid>a5570e9f-0690-49e3-b2b4-bd57799c08a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donor Type'])[1]/following::button[1]</value>
      <webElementGuid>1f424a40-805a-44ed-b342-c6cf4effcd27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='District'])[1]/following::button[2]</value>
      <webElementGuid>6df1cc80-4ef8-4a3d-a55a-72e98c8fc6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact No.'])[1]/preceding::button[1]</value>
      <webElementGuid>fd272790-2e50-4e10-a3ae-8998a4eca2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::button[1]</value>
      <webElementGuid>82b9e395-1be9-46ed-b50c-cfab5c9a73a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/button</value>
      <webElementGuid>a0ec2d0b-6c81-40c9-a4e6-806aa514cd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'P3_DONOR_TYPE_lov_btn']</value>
      <webElementGuid>1043f375-ce2e-49b4-a382-ff31b2904e64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
