<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_P3_FIRST_NAME</name>
   <tag></tag>
   <elementGuidId>6435deb4-ffad-49f2-abb0-c6c4cb74eff9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P3_FIRST_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P3_FIRST_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb2a5ce1-8ba1-4856-a5a5-2416bd1e7cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e6619eaa-7bca-4f68-a7bc-bfc64a639ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_FIRST_NAME</value>
      <webElementGuid>4eeb1add-9bb0-44cc-bbd2-774f85c0a1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P3_FIRST_NAME</value>
      <webElementGuid>eb0a6f32-c32d-40e1-b8dc-f88f1cf0f425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>d1dadf39-a4d0-47ce-9935-9b97dd552df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>c508b9c5-204e-4ec3-b614-2b87771a893c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>da56c585-b859-4322-b0f2-d564d8794727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>66ea3f23-7353-42dc-9a21-1cc47c3b2662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_FIRST_NAME&quot;)</value>
      <webElementGuid>82a1e4cf-19b1-4f7b-8fa6-1d75c954e4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Donor Adding(Donor Receipt)/Page_Donor Details/iframe</value>
      <webElementGuid>580ee485-fb74-495d-b2da-10a226e8c151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P3_FIRST_NAME']</value>
      <webElementGuid>b6a14221-c94a-423f-9c31-ff53a917f0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_FIRST_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>50b6de8d-d92b-4cf6-8aa9-6c6b0a3876a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>64296ebd-d9d4-4481-a4df-eef29fa44feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P3_FIRST_NAME' and @name = 'P3_FIRST_NAME']</value>
      <webElementGuid>9d0d72bf-dd31-4e8c-886d-2020acd87b3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
