<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pan Number_P3_PAN_NUMBER</name>
   <tag></tag>
   <elementGuidId>46f0a56c-013a-4607-ad7d-99b20db1bcca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P3_PAN_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P3_PAN_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>712a72b1-d72b-4829-8341-4aa7fd3b7694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>28c497f1-9f5a-43dc-844f-3d53a8e35af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_PAN_NUMBER</value>
      <webElementGuid>e57e26af-eb81-485e-ad6c-228b60231a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P3_PAN_NUMBER</value>
      <webElementGuid>0d31f820-2297-43d6-bb0d-b10a67209a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>d836c9a4-2a7f-47f9-ade4-969345858cc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>1f91ccad-0805-4081-b9d5-52889af6a785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>4391fe37-409b-42c9-98f9-7a999c3d60bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>7c70f8b9-6628-4276-bcbd-cf36dd510fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text-case</name>
      <type>Main</type>
      <value>UPPER</value>
      <webElementGuid>c577d47f-daf4-4dce-b54e-1a1ac54fc5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_PAN_NUMBER&quot;)</value>
      <webElementGuid>21ec778e-6abd-44cb-9bba-7258d1448c43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Donor Adding(Donor Receipt)/Page_Donor Details/iframe</value>
      <webElementGuid>98288ec8-acf6-4bd1-8113-95aa8070d55c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P3_PAN_NUMBER']</value>
      <webElementGuid>e8e67bb3-9af2-4c3f-80c8-5c837e0a3cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_PAN_NUMBER_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>bc44029f-3534-4706-b6b8-e2775c893314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>037145bd-9fff-48cc-8cc7-5ac71dc9aec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P3_PAN_NUMBER' and @name = 'P3_PAN_NUMBER']</value>
      <webElementGuid>da9fd2f9-2bb9-4cf1-815d-356555f7b1ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
