<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Salutation_t-Icon icon-close</name>
   <tag></tag>
   <elementGuidId>b00625b2-be64-40ed-b1df-a1c81098b56e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='t_Alert_Notification']/div/div[3]/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.t-Icon.icon-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f1bec560-bbcc-4969-8891-92563cbaf8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Icon icon-close</value>
      <webElementGuid>49bf50cd-9f31-4637-af6b-7256c5d5fb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_Alert_Notification&quot;)/div[@class=&quot;t-Alert-wrap&quot;]/div[@class=&quot;t-Alert-buttons&quot;]/button[@class=&quot;t-Button t-Button--noUI t-Button--icon t-Button--closeAlert&quot;]/span[@class=&quot;t-Icon icon-close&quot;]</value>
      <webElementGuid>d64a985f-f7c1-4a4b-abb1-f74256a1c277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Donor Adding(Donor Receipt)/Page_Donor Details/iframe</value>
      <webElementGuid>b05de7d6-bba4-462b-9ecb-b3565ae25429</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='t_Alert_Notification']/div/div[3]/button/span</value>
      <webElementGuid>be6de445-536b-40e5-9bd9-6c0a4ce851ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>f7d4bde5-d141-49b3-aad6-84674e73cf9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
