<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>30051f12-fcfc-485a-b9c9-381168abc744</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add Year&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f953ad88-2813-492d-aecb-d9f45aadc62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation177/add-year?p23_y_id=5&amp;clear=RP&amp;session=5700117674892&amp;cs=3fzdv7aLzps3eixW1v6d3di5YB9MhfENK7UNhxTCriTWOF70ueYMHGEPXdwOudJhrd6QaK9I09JErNOEYcI2JDg&amp;dialogCs=VDBQwrTlsSjOzz_23RGEV3CCFX1TdIRAqaXtfqJVzOaRTgyNA9ekgWpUQ8Vy7l6CAWYcthmBa8BCWa6oGYV1uQ</value>
      <webElementGuid>670a8c3e-fda6-48cc-9db6-359be0803ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Year</value>
      <webElementGuid>fca57b6b-ed65-455c-949d-e2c16899e1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>805e0479-50bd-4d51-8c55-5b0a121a1f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8f9ae81f-4cb5-46ca-9022-e0c6de119404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>1a931b40-927d-4509-98f6-480a75523ee7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>3cf228cf-5a88-4401-97ae-5ce1eb1fba14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>f917620e-c326-4379-a1ce-8dc7367840fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4aabcb90-229c-4715-b1df-08b0c2c88a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation177/add-year?p23_y_id=5&amp;clear=RP&amp;session=5700117674892&amp;cs=3fzdv7aLzps3eixW1v6d3di5YB9MhfENK7UNhxTCriTWOF70ueYMHGEPXdwOudJhrd6QaK9I09JErNOEYcI2JDg&amp;dialogCs=VDBQwrTlsSjOzz_23RGEV3CCFX1TdIRAqaXtfqJVzOaRTgyNA9ekgWpUQ8Vy7l6CAWYcthmBa8BCWa6oGYV1uQ' and @title = 'Add Year']</value>
      <webElementGuid>1a523669-90fe-45cb-91d4-c3269f9154f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
