<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_State_a-Icon icon-popup-lov-under</name>
   <tag></tag>
   <elementGuidId>8358d127-26ec-466f-9442-acdd419fb64d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-Icon.icon-popup-lov-under</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P12_STATE_lov_btn']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>885276d3-76b6-42e7-8fa4-bc4d64b7388c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Icon icon-popup-lov-under</value>
      <webElementGuid>4c8e8e67-52fd-49c3-939c-4924dd6a4685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P12_STATE_lov_btn&quot;)/span[@class=&quot;a-Icon icon-popup-lov-under&quot;]</value>
      <webElementGuid>11485ac2-c50f-44c1-ac6c-d44f020fdfb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='P12_STATE_lov_btn']/span</value>
      <webElementGuid>b8309736-4ce9-4d65-a43a-0ac9f334c1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>b6718187-e4e4-43b6-bc39-c92be21ab3c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
