<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_State_P3_STATE_lov_btn</name>
   <tag></tag>
   <elementGuidId>7ef7b1f0-9099-4540-b9ad-7124977a8757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P3_STATE_lov_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P3_STATE_lov_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>78897795-682a-4baa-a295-0e32953a0eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c3865bb2-0299-4aa9-b31e-1a956b66db6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>376cfd81-23bf-4954-b6bd-1d1c40f1abb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Button--popupLOV</value>
      <webElementGuid>e5ef362a-ed40-47a2-8d17-708c3a91ea83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_STATE_lov_btn</value>
      <webElementGuid>806da370-f3d0-4681-845d-e1ab46767c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>25bdfe59-ee42-47be-9121-3a351fd5e506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_STATE_lov_btn&quot;)</value>
      <webElementGuid>cb07e72a-389c-466f-baa2-08d82d443c10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='P3_STATE_lov_btn']</value>
      <webElementGuid>b6febb90-d131-4dac-8ca8-c3f96602a87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_STATE_CONTAINER']/div[2]/div/div/button</value>
      <webElementGuid>3b7a9ad5-0143-455d-a521-8318c0db2396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State'])[1]/following::button[1]</value>
      <webElementGuid>618f3530-8642-437c-bc24-7988a8c1df57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::button[1]</value>
      <webElementGuid>69881929-cb46-49a9-862d-a70ff3a4b474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Number'])[1]/preceding::button[1]</value>
      <webElementGuid>3882fe72-a956-485c-aa5e-83c58e78853f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>8b343243-0883-44ff-b85f-be1bfb2a38bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'P3_STATE_lov_btn']</value>
      <webElementGuid>bd77ed57-0a66-4cce-b04b-d2fd18580707</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
