<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Number_P3_MOBILE_NUMBER</name>
   <tag></tag>
   <elementGuidId>d4d6417a-5831-43fb-80d3-658b3cb34ca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P3_MOBILE_NUMBER</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P3_MOBILE_NUMBER']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b1a77a9-3125-46d8-b440-310aff405a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fcf026b-50f0-4b35-8110-4485c5a5b14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_MOBILE_NUMBER</value>
      <webElementGuid>ef512a5b-3ef1-4289-bfc5-d7eac2de0554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P3_MOBILE_NUMBER</value>
      <webElementGuid>d5062fbf-b54f-43a1-b703-08d073d051a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number</value>
      <webElementGuid>e0432d05-ffbf-4b0e-b820-075884f597f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>94024f2c-6cd3-45f7-b4af-e0c05736a94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c80845fa-81e0-42d2-9ecc-26fd37503ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>29aadd1c-f252-4fb2-8bfc-1c114d430f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_MOBILE_NUMBER&quot;)</value>
      <webElementGuid>b9b3cbf6-353e-40b9-8e37-5127dc1df348</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P3_MOBILE_NUMBER']</value>
      <webElementGuid>c4642d56-6056-41fb-8ea9-548301801481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_MOBILE_NUMBER_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>c8ed308d-5a3d-4230-a517-a4bdf5254679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>16005028-3a8c-41fd-bca6-e3839e6c4d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P3_MOBILE_NUMBER' and @name = 'P3_MOBILE_NUMBER']</value>
      <webElementGuid>7b085c66-cf2b-45d0-9518-950180843459</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
