<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_P3_CITY</name>
   <tag></tag>
   <elementGuidId>d8bb0b05-fd8d-4223-a219-e05bde2b9975</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P3_CITY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P3_CITY']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>275dadac-d813-4522-b00f-366021a00ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70213024-76b8-4c3a-ab3b-0b7c75ba065c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_CITY</value>
      <webElementGuid>7ef67ce5-e2ad-425e-86c3-214c21395153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P3_CITY</value>
      <webElementGuid>ab2f6f33-a323-4e72-b9e6-15ac055e08c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>ad210682-ba1f-4d78-a8c1-8f3169dc59e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>ea2cee0c-7c34-4722-aef7-d362bcca3ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>fe46fad4-ce91-4ff6-8964-19f8b3b6fc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_CITY&quot;)</value>
      <webElementGuid>764a7228-a38c-497f-875a-9e557b57e9c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P3_CITY']</value>
      <webElementGuid>3f0e4c54-a587-4b5a-9701-3dc82449c23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_CITY_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>a3dcdd79-85fe-4a87-9b7b-c1d313b8af30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div[2]/div/input</value>
      <webElementGuid>7cd5b7e3-f286-4ba5-8580-aac24d78d7f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P3_CITY' and @name = 'P3_CITY']</value>
      <webElementGuid>97239fd7-3669-4cf7-8b8a-2621dfe464c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
