<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_P3_LAST_NAME</name>
   <tag></tag>
   <elementGuidId>7b098af5-0f1d-4b9f-b3ab-84e27de4fef5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P3_LAST_NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P3_LAST_NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f4e1984-b72e-4277-8909-7f412771d527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c6014f8-656b-4187-83c3-b09d83c3876a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_LAST_NAME</value>
      <webElementGuid>c3142daf-a56a-4438-869b-59121f536cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P3_LAST_NAME</value>
      <webElementGuid>d1b627b5-6c22-45dd-bc86-aa21ed501b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>c7e3aefe-66f2-4526-a57c-22f066fe2a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>352ff1f9-da1d-40bd-916b-fc3b110cf555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>94a96407-4989-4c5e-8dc8-471ce242684f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_LAST_NAME&quot;)</value>
      <webElementGuid>c54b65c6-610d-41d8-9f13-f23388bf1345</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P3_LAST_NAME']</value>
      <webElementGuid>2641a39b-565b-46ed-b13d-2b6bac9588b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_LAST_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>2a3b9ff2-a1c0-41c8-86f9-266ddad51537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/input</value>
      <webElementGuid>720fe7bd-1801-4fa2-a5ed-ce44e680f498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P3_LAST_NAME' and @name = 'P3_LAST_NAME']</value>
      <webElementGuid>59fe0af4-74b1-4889-8b45-678556033a57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
