<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Village Name_P3_VILLAGE_NAME</name>
   <tag></tag>
   <elementGuidId>6b159361-7673-446f-a1ec-5d3359ef0c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P3_VILLAGE_NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P3_VILLAGE_NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b67f889f-5245-46f1-8c42-f3083348753f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01502fb9-93dd-4562-befb-d81ac2370556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_VILLAGE_NAME</value>
      <webElementGuid>b39b0201-c7a6-48c8-b80b-b76d8c7f3c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P3_VILLAGE_NAME</value>
      <webElementGuid>8bdf7ff1-3095-4279-80dc-8ccd94eea2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>ff34367f-a790-40e1-b3c3-1815770d59a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>3f60c06f-bafb-4bf3-b780-48034255aa51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>94107c97-21dc-481c-adc7-7b79c9ee5ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_VILLAGE_NAME&quot;)</value>
      <webElementGuid>2fd32121-eb5b-4a0e-9e6e-666e35d17da1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P3_VILLAGE_NAME']</value>
      <webElementGuid>7d7caf78-b7ee-422f-bd66-0a55da940c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_VILLAGE_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>db67f663-5d74-474d-8b6a-ce7a8b23bb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>ac69c529-f213-46b6-aac2-58ad3025891e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P3_VILLAGE_NAME' and @name = 'P3_VILLAGE_NAME']</value>
      <webElementGuid>f7145212-4664-4c7b-a171-10fce9a4de41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
