<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Image Of  Hand 1_a-Icon icon-file-browse</name>
   <tag></tag>
   <elementGuidId>7dfd1d6f-7e79-49d2-bb0c-83d6e51a4f4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.a-Icon.icon-file-browse</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='P3_IMG_OF_HAND1_DROPZONE']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c45fb5f9-197a-4f6d-a905-566126d4ed86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Icon icon-file-browse</value>
      <webElementGuid>d59aaabb-b2e8-4140-b132-a1b4abd3cba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>617f817f-cefc-489c-8597-e259c9f4d3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_IMG_OF_HAND1_DROPZONE&quot;)/div[@class=&quot;apex-item-filedrop-icon&quot;]/span[@class=&quot;a-Icon icon-file-browse&quot;]</value>
      <webElementGuid>50d44861-fe10-44dd-9d01-4d3a3de74535</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_IMG_OF_HAND1_DROPZONE']/div/span</value>
      <webElementGuid>24df8b92-bc94-4993-852e-291f9c8e8c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]/div/div/div/div/span</value>
      <webElementGuid>bfbc3754-a613-4523-841f-1f3388227a45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
