<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Approval_a-Icon icon-popup-lov-under</name>
   <tag></tag>
   <elementGuidId>7f3648e1-33d2-4c8c-a17e-85b399146a65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P3_APPROVAL_lov_btn > span.a-Icon.icon-popup-lov-under</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P3_APPROVAL_lov_btn']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>75d894bf-491d-43eb-9e50-d779bf0e132f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Icon icon-popup-lov-under</value>
      <webElementGuid>a74edcd8-17f4-4d41-bfa3-f400227ec415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_APPROVAL_lov_btn&quot;)/span[@class=&quot;a-Icon icon-popup-lov-under&quot;]</value>
      <webElementGuid>6e853c27-5091-490c-bce5-5a9f4acb14f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='P3_APPROVAL_lov_btn']/span</value>
      <webElementGuid>4fdc1b68-c7cd-438d-bcf8-de4f40bd3749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/button/span</value>
      <webElementGuid>a4f142ca-95fc-4b4e-aae7-82afc5dded5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
