<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>b0a39c22-f669-4699-be83-bd440c3960e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add/Edit Member&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e81ab000-53d2-4366-95ff-fc6fa290f78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/add-edit-member?clear=108&amp;session=15970039120172&amp;cs=3Suukf3M8HOHkZ60IctVO2EmsrJH7ieo9Ic_VXCRpL8uJjkuo53N6sgpMtnKep4rsFkh8bN7lT8-jXuvKP-qmWw&amp;dialogCs=vamCprdV_XgV8WV2c8dpGu9-KbyRknbE5no2SMNCidt9q7JQDP7ejwr7UwGXvpBGWIlPFEi1P_ARqLF1WjBEAQ</value>
      <webElementGuid>7946e4c7-5949-4715-88b4-b4cd4b28a5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add/Edit Member</value>
      <webElementGuid>cd7118e0-9122-408b-aee5-67b802109ce5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>651100b3-9af6-4743-be6c-817e99917b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>611d4857-5c5f-44dc-bea3-2fd3ae4bcedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>a72481e8-87e6-4da5-b7ae-f616137e62f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>5c89af06-2897-4d99-aea5-17536f1794db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>c5b8835c-b135-44c3-8dcb-11256ed10946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6a507991-7df4-48ff-a9cb-a69f65252c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/add-edit-member?clear=108&amp;session=15970039120172&amp;cs=3Suukf3M8HOHkZ60IctVO2EmsrJH7ieo9Ic_VXCRpL8uJjkuo53N6sgpMtnKep4rsFkh8bN7lT8-jXuvKP-qmWw&amp;dialogCs=vamCprdV_XgV8WV2c8dpGu9-KbyRknbE5no2SMNCidt9q7JQDP7ejwr7UwGXvpBGWIlPFEi1P_ARqLF1WjBEAQ' and @title = 'Add/Edit Member']</value>
      <webElementGuid>f789557a-980d-46f4-88dd-2166959157b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
