<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P108_CONTACT_NO</name>
   <tag></tag>
   <elementGuidId>127c621f-0c1b-4dbe-b4aa-6b86135c702d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P108_CONTACT_NO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P108_CONTACT_NO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>648572d1-1f82-4dd6-9280-66f7ca4e8eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dc38d980-ac7d-4fde-9363-8a7a617cb4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P108_CONTACT_NO</value>
      <webElementGuid>2f5414c0-d118-423b-8f1f-cd5227628261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P108_CONTACT_NO</value>
      <webElementGuid>63394f98-7752-4094-a84d-93dc59bff824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number</value>
      <webElementGuid>bec25e92-8edb-4777-8c77-4a6ae8f4fabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>cff21a66-6fd8-43ef-a319-489c6f0ba4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>51771488-81fe-4e1b-bafb-2f424fb6bc2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90d83725-c5cf-445e-8c3f-206eeee53f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P108_CONTACT_NO&quot;)</value>
      <webElementGuid>dc8e6d3e-f8e9-4334-86cb-88e845ee05fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Another master entries (Meeting coordinator)/Page_Members List/iframe</value>
      <webElementGuid>e81cf060-84e8-47e1-9a77-e5dc7c9ddb49</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P108_CONTACT_NO']</value>
      <webElementGuid>bf98f963-a940-479d-a86c-38f8f44ad5a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P108_CONTACT_NO_CONTAINER']/div[2]/div[2]/input</value>
      <webElementGuid>818a2397-7769-4d5c-9f52-07426b780532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>1694705a-d212-41b8-b5d8-f5502885203c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P108_CONTACT_NO' and @name = 'P108_CONTACT_NO']</value>
      <webElementGuid>70a1bb70-61a2-4f86-ae97-ca06fd0ed6a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
