<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P108_LAST_NAME</name>
   <tag></tag>
   <elementGuidId>ec998912-669e-48bc-b577-5e9a2e6f7d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P108_LAST_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P108_LAST_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dcba6e2-8e84-4cd4-bec4-3f769f5844e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c240a20-f722-41b4-805a-41a1a12da7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P108_LAST_NAME</value>
      <webElementGuid>ebe01cf8-4e28-4c1f-8e7c-67dd6087c71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P108_LAST_NAME</value>
      <webElementGuid>43b05663-0445-41c1-8c1f-9d5aa0510e7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>862fd17d-067c-4284-898e-927d04cd087a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>5bdbe7ec-d8bc-4f27-b990-35306b975793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>79ff9b0c-8430-48ca-abb3-03b989f320f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P108_LAST_NAME&quot;)</value>
      <webElementGuid>34198e2e-9d70-4f3b-a08d-b93435d446d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Another master entries (Meeting coordinator)/Page_Members List/iframe</value>
      <webElementGuid>9ba6da39-3fb6-4aa5-9caf-fdb1a11b378e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P108_LAST_NAME']</value>
      <webElementGuid>a70d2338-0397-4933-bd44-db531b9857a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P108_LAST_NAME_CONTAINER']/div[2]/div[2]/input</value>
      <webElementGuid>2ef2f23f-332e-4f51-b010-2cf8e8aad9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/input</value>
      <webElementGuid>568a8050-3fcf-4882-bf65-f27e405ef481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P108_LAST_NAME' and @name = 'P108_LAST_NAME']</value>
      <webElementGuid>d1362169-e48f-48db-8014-5a584d6bd72a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
