<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P108_FIRST_NAME</name>
   <tag></tag>
   <elementGuidId>22668e29-e958-4f77-ba24-e12f3802edef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P108_FIRST_NAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P108_FIRST_NAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9753608e-fdfa-4d18-af62-fc77b84c051e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e7a89053-d54f-401d-845a-60e2a8578810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P108_FIRST_NAME</value>
      <webElementGuid>fd7a948d-2ea9-4a72-9904-a19aa1980817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P108_FIRST_NAME</value>
      <webElementGuid>2eca89be-9c12-44d0-aa58-82299b9b7721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>866f95af-c7dc-4c32-97c7-adf3ed631b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>0108072b-b92e-406c-be81-4f05ea012b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0ef6a966-a745-452b-8730-7d29588e083c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P108_FIRST_NAME&quot;)</value>
      <webElementGuid>80e40c53-3564-4efa-84c9-195128a1345e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Another master entries (Meeting coordinator)/Page_Members List/iframe</value>
      <webElementGuid>a54b92d3-3967-4048-ab74-38d2453cee2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P108_FIRST_NAME']</value>
      <webElementGuid>da87245c-ba84-4b5a-a7f6-fe7d47fae183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P108_FIRST_NAME_CONTAINER']/div[2]/div[2]/input</value>
      <webElementGuid>b8a5b292-0fed-4c55-afb7-ff5242ccacfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>b851917e-dffa-4200-be46-b44306467e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P108_FIRST_NAME' and @name = 'P108_FIRST_NAME']</value>
      <webElementGuid>6ad93637-95fb-4c93-8ebc-1e8088b3a4df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
