<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>8d596371-00e9-4a6c-b0ea-85cc9f3d1f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add Year&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4f48f199-5bdb-4975-b483-b8606680ed48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation/add-year?clear=23&amp;session=13459300080783&amp;cs=3yaR4o13JTDv82elwz-8I5gfq5N6LoJk_pV5byY4PAcA__lBca9qN1FHNkvKjPCMZXgr9SRUckJ_9jp5m75tCZQ&amp;dialogCs=wjlBTakCDDh4NjD9xH3lgd9_08_Y0qeBEyl4X8ANHbOfHiM5QcVZUpNvVHrBEbJO1hnc7IXvdPMQ2UxmGhidjg</value>
      <webElementGuid>88b13463-c230-4043-9dac-25a4b88a6254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Year</value>
      <webElementGuid>93b3ccb7-8914-4814-9044-f89021705951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>71f9fb08-912d-4f15-90b4-6c2ba67079e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>edd9288e-900b-4df0-be1d-f056b711ef84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>bc554494-c6c9-430a-af05-8ea554c2fa92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>4bb17f0c-e771-4a43-8aba-d12182d4c23c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>29e3cbf1-d57f-4f7e-ad0e-a09dce0de65d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7072e7ea-166c-484b-a740-faa62535cf87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation/add-year?clear=23&amp;session=13459300080783&amp;cs=3yaR4o13JTDv82elwz-8I5gfq5N6LoJk_pV5byY4PAcA__lBca9qN1FHNkvKjPCMZXgr9SRUckJ_9jp5m75tCZQ&amp;dialogCs=wjlBTakCDDh4NjD9xH3lgd9_08_Y0qeBEyl4X8ANHbOfHiM5QcVZUpNvVHrBEbJO1hnc7IXvdPMQ2UxmGhidjg' and @title = 'Add Year']</value>
      <webElementGuid>ef2a3ec2-21a6-416e-ae15-3397612a2e05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
