<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Skip to Main Content_t-Header-controlsIcon</name>
   <tag></tag>
   <elementGuidId>ed901f1b-2113-4e65-91eb-6bf406c0d3a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.t-Header-controlsIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='t_Button_navControl']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b44054dd-cd31-4dd2-a7e0-13a1f2cf1d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Header-controlsIcon</value>
      <webElementGuid>870e4c6f-8afb-4a5f-8c96-84a9e7052ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6371f733-64d7-462a-83a4-8a69f6932b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_Button_navControl&quot;)/span[@class=&quot;t-Header-controlsIcon&quot;]</value>
      <webElementGuid>213654f7-03d9-4608-982a-e5ba9456be73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='t_Button_navControl']/span</value>
      <webElementGuid>ec6f4990-7531-4546-a157-59d596d6936a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>5f30ce5a-a55d-4b72-8c09-37467c405e0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
