<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_P9999_PASSWORD</name>
   <tag></tag>
   <elementGuidId>aecf8130-7360-4190-9b15-1ac6f2940055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P9999_PASSWORD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P9999_PASSWORD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db26f274-849a-4b6a-b311-a7532fe26208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>cc2ce1e7-9bbc-4b6e-8161-ea51d9573b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P9999_PASSWORD</value>
      <webElementGuid>f224cfa6-652f-4138-b3e4-9fd59b0b7644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>804e1263-5d21-40b1-a166-a913e8ba8829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>902ab91e-20a4-4683-8714-691968962ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P9999_PASSWORD</value>
      <webElementGuid>d136d9cf-b207-41ee-9d8c-72f392a60c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>b1c8189a-4a66-4b19-a03d-b2fbedf0c72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password apex-item-text apex-item-has-icon</value>
      <webElementGuid>c0d0c584-c50a-4236-bcd9-909e48ae6a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return apex.submit({request:'P9999_PASSWORD',submitIfEnter:event})</value>
      <webElementGuid>3ae6dd92-5d40-45b9-8c80-b2b169e92f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P9999_PASSWORD&quot;)</value>
      <webElementGuid>bc9073eb-914b-4ea1-b632-2b5c282d8d12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P9999_PASSWORD']</value>
      <webElementGuid>1895b42a-c344-4d49-b5f1-552ccf08b60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P9999_PASSWORD_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>1468771c-8c63-4ffe-8cae-722c73f8435a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::input[1]</value>
      <webElementGuid>8f58d921-9ea3-46eb-a5b7-b8068222fa22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::input[2]</value>
      <webElementGuid>d8d15cd7-5996-4763-a355-773f1c83526d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::input[3]</value>
      <webElementGuid>c2b7157e-650b-4591-84aa-091a141fb053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'P9999_USERNAME', '&quot;', ')')])[1]/preceding::input[6]</value>
      <webElementGuid>3555ef55-03cc-452a-9fb3-fe759b9b391e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>e13c6457-2c71-4f6e-a41f-06bd5dd57a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'P9999_PASSWORD' and @id = 'P9999_PASSWORD' and @placeholder = 'Password']</value>
      <webElementGuid>2fc1970f-4575-4404-871b-a4d1e582744b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
