<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>351b91b6-77df-4f87-ae3b-113469d62212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add Year&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>db6bbe1f-0085-442f-b36d-0adebc2afbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation177/add-year?clear=23&amp;session=12384949946323&amp;cs=3pV6bksaBwP5BIUp8ipPqkbGHDO4Ji3gnMyW5Mnd1P615hYeRqg-421YYLO4qJfpI7YaFWtcviyB72rG8vPyvXw&amp;dialogCs=UI_5SfoHpXWLCpNK2jLaADeyMoTNmwda3_ooh27JwuXwZbFyoja5N2JR90PGS1FlCmJP58n8Ws19iNHwXKywFw</value>
      <webElementGuid>5eceecf0-031f-4322-ba9b-24f0d606c646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add Year</value>
      <webElementGuid>9584c029-8a65-4b17-9b4c-147463df6740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>6f7e4540-2ecc-4959-97e6-9b842fb82412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>f479ea3e-3c4f-4abb-9bec-25e226094734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>b751c69b-8119-446d-9a82-4ee12a9514ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>635b3bcf-c830-4724-99f6-c00952fce67b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>bdcea581-ec92-4b40-a14f-ad5b91eff7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d6c50518-df18-44df-ba25-b53a95e864c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation177/add-year?clear=23&amp;session=12384949946323&amp;cs=3pV6bksaBwP5BIUp8ipPqkbGHDO4Ji3gnMyW5Mnd1P615hYeRqg-421YYLO4qJfpI7YaFWtcviyB72rG8vPyvXw&amp;dialogCs=UI_5SfoHpXWLCpNK2jLaADeyMoTNmwda3_ooh27JwuXwZbFyoja5N2JR90PGS1FlCmJP58n8Ws19iNHwXKywFw' and @title = 'Add Year']</value>
      <webElementGuid>264e62eb-b972-4f1a-a068-0f8dc3652f6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
