<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Start Year_a-Icon icon-calendar</name>
   <tag></tag>
   <elementGuidId>ab68b02d-23b1-4340-9714-f54baee3cc58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a-date-picker[@id='P23_START_YEAR']/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.a-Icon.icon-calendar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3c2e2b73-195c-4210-9c98-edeff3c2feb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Icon icon-calendar</value>
      <webElementGuid>aa793c34-71a3-4f16-9324-4179fcebd3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P23_START_YEAR&quot;)/button[@class=&quot;a-Button a-Button--calendar&quot;]/span[@class=&quot;a-Icon icon-calendar&quot;]</value>
      <webElementGuid>4209bc92-1dad-4be1-8278-40c6dcb0a68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Manage Mater(Donor Receipt BJS)OLD/Page_Period Master/iframe</value>
      <webElementGuid>191a694f-211d-4afe-b4ae-bed6302caee0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a-date-picker[@id='P23_START_YEAR']/button/span</value>
      <webElementGuid>40f91a1f-e781-429a-90bb-e71e267720e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>2e786a1d-74ca-4d42-85b7-700b86a45866</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
