<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_1_2</name>
   <tag></tag>
   <elementGuidId>6053fafe-0be7-4be4-9d5c-aba4dc6e7017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Topic Master&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_2']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>edf848b9-173a-44e3-b10b-f78ff5ce711e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/topic-master?session=15970039120172&amp;success_msg=QWRkZWQgc3VjY2Vzc2Z1bGx5Lg%2FvjVBcyXR61nKZMwSTQyaVwyzlOkwELwDY7NDU-D6M7WF3sz9RvUrXhLY-qUMa2P4xxd60ISaRfm2zCtbMD0_IA&amp;dialogCs=X4PNmttRhzN0u5sgNLN8ZOsC888AMncbNlyJd4H6-lQItSy4IVQKsecfEx2armnL_ZRHsmVaMZGCL_0b8hiyQw</value>
      <webElementGuid>d89a7be1-67a1-41f9-b7b5-778d21955b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Topic Master</value>
      <webElementGuid>5124d610-2a5a-431f-9447-474be512a99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>3fc73481-1426-4f1b-949f-b4cc9aaaf275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>0a5c5a9e-2d2e-42f7-912c-801447ed3816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3435089a-bc6d-4f40-a180-aedaf8d320c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_2&quot;)/iframe[1]</value>
      <webElementGuid>f42d6c8b-9a17-4b8a-b682-9d18ef469ba4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_2']/iframe</value>
      <webElementGuid>93de94df-02fa-4e44-b33f-b5b4ca6d430a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>146c5ca5-91a9-4472-b70e-a5e90fa3f45f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/topic-master?session=15970039120172&amp;success_msg=QWRkZWQgc3VjY2Vzc2Z1bGx5Lg%2FvjVBcyXR61nKZMwSTQyaVwyzlOkwELwDY7NDU-D6M7WF3sz9RvUrXhLY-qUMa2P4xxd60ISaRfm2zCtbMD0_IA&amp;dialogCs=X4PNmttRhzN0u5sgNLN8ZOsC888AMncbNlyJd4H6-lQItSy4IVQKsecfEx2armnL_ZRHsmVaMZGCL_0b8hiyQw' and @title = 'Topic Master']</value>
      <webElementGuid>0e4a9782-9e10-4dc4-8625-a9e3574ca549</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
