<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Follow-up_232300152168468492</name>
   <tag></tag>
   <elementGuidId>2b7e3ac2-ea2c-4a19-a7d8-dedd2e6c250f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C232300152168468492</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='C232300152168468492']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0cbdd868-e5ae-4af3-9bba-73a4070b5776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>94e728a7-1df7-443a-8465-71d7b710d937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C232300152168468492</value>
      <webElementGuid>6bb7dbd5-e680-4e01-b880-6a65cd721f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>232300152168468492</value>
      <webElementGuid>0e3cf2fa-d821-4da1-992b-b3cb69eac5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number js-ignoreChange</value>
      <webElementGuid>269edcdc-8cdd-44ad-8b59-851e5e43df4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36e99e80-754c-4acf-8d6e-e817da135f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>252bba1e-83be-4190-9ea6-a03d4f04bc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C232300152168468492_HDR</value>
      <webElementGuid>dc20c353-751f-40b9-9f04-57f31cd7a8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C232300152168468492&quot;)</value>
      <webElementGuid>64ad27fb-5b92-4c2d-9e3a-4ceffc860fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Another master entries (Meeting coordinator)/Page_Administration/iframe_1</value>
      <webElementGuid>4cd8217c-c9d0-42a0-82e3-08c48e2fce56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='C232300152168468492']</value>
      <webElementGuid>c5d2927a-4606-46b3-bfe4-05883d4dde58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='R204771455490959986_ig_grid_vc_cur']/div/input</value>
      <webElementGuid>6bdce3ab-1d26-4c11-b5c3-72535be4dfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/input</value>
      <webElementGuid>65f6392b-fae1-44a4-b52b-bdc3211941ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'C232300152168468492' and @name = '232300152168468492']</value>
      <webElementGuid>e656bec6-7ba0-4fa9-b791-8ec05e8035a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
