<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Yes_204767588418959977</name>
   <tag></tag>
   <elementGuidId>8a6ec976-df04-4b5f-8790-07e9c00e3b92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C204767588418959977</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='C204767588418959977']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fd77cc8-a912-49dd-a0ee-6f09604cc619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>730c13d7-9956-4323-a735-d1a724d90bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C204767588418959977</value>
      <webElementGuid>20e475cf-882d-4774-9e2f-79127f026fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>204767588418959977</value>
      <webElementGuid>47e666d9-6547-4300-8a17-0da1037603ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text js-ignoreChange</value>
      <webElementGuid>387c9b9f-3772-4c69-915d-50441e2c059a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>763c3ab9-72c5-400a-8ce5-eb25bb3d2013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4b2a93bb-ddb2-4ad5-b647-bd22e24f8cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C204767588418959977_HDR</value>
      <webElementGuid>2754d710-a981-4e55-a3ec-cf392411e693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C204767588418959977&quot;)</value>
      <webElementGuid>5382cf59-cc7f-4807-bb61-08a4bd4eca7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Another master entries (Meeting coordinator)/Page_Administration/iframe_1</value>
      <webElementGuid>67aa0177-f4ad-476c-9932-fbc7720be647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='C204767588418959977']</value>
      <webElementGuid>3f97d361-fedf-4fd2-b7fc-60b93e02ad06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='R204771455490959986_ig_grid_vc_cur']/div/input</value>
      <webElementGuid>bda92840-fda3-4fad-8e56-cf88fac93a75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>a3782d4c-02c0-4a13-a54f-4abc98d9fa06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'C204767588418959977' and @name = '204767588418959977']</value>
      <webElementGuid>d7f62d63-8d3f-4dde-b1af-0a9a7a1c863a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
