<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Testing all chaturmas event_189413645_4b2f88</name>
   <tag></tag>
   <elementGuidId>f295a1b5-5fcf-443d-af2c-9b15e604f1d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C189413645541424152</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='C189413645541424152']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e93a7ac8-bd18-4f63-90df-16ae0524d704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1a72678d-f4d2-4fff-8866-e0e799838a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C189413645541424152</value>
      <webElementGuid>7e82600a-0322-4f9f-8f47-36872d57c918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>189413645541424152</value>
      <webElementGuid>924e445d-0768-40e0-b37a-983cf4f01662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text js-ignoreChange</value>
      <webElementGuid>697c67e0-67ea-408e-ba0f-b63447ceb282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3aceccc9-5ac1-4ff9-8004-cfe096354797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>526c73cd-f45c-4f86-8ad6-d381457a6a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C189413645541424152_HDR</value>
      <webElementGuid>1cae5a71-115e-4424-b5f7-d848e17ef899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C189413645541424152&quot;)</value>
      <webElementGuid>0c0805ff-913d-40e7-821e-7172c54488c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Another master entries (Meeting coordinator)/Page_Administration/iframe</value>
      <webElementGuid>adb5f013-5ae3-456d-94d3-a1e637aba971</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='C189413645541424152']</value>
      <webElementGuid>9c76c771-e38f-48b1-a772-d1c170bdbb1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='R189409855295424147_ig_grid_vc_cur']/div/input</value>
      <webElementGuid>9298189b-55b9-46dd-b813-7029171b13e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>1f81af85-cada-4740-ba23-52ff548726ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'C189413645541424152' and @name = '189413645541424152']</value>
      <webElementGuid>5960af50-73b6-4efe-8da2-497e69f41bc6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
