<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>2672befb-541d-473a-ac01-3eb653b5dea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Payment Details&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f1d1fcc4-c437-476a-ada3-f56c29f116a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation/payment-details?p8_donor_id=&amp;p8_org_id=149&amp;clear=8&amp;session=5645694127925&amp;cs=12f96Z25blRQvH5f6fHktd-6l5lSgE-hpD0KlcubMr1QH3dD9bKFh1ZrrCkuNBgDRQofR7lyK7eofI1IiPbZ1Bg&amp;dialogCs=I7g5lC6hyc5l2TFfHD0FO0B9Ff3b-NxynFC94M54WoXDovT8X7fF13CbDSAPN1iV1M5iyvQXrMYTI-AvAzKVdw</value>
      <webElementGuid>10837994-d89e-4519-8be1-9f0331542bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Payment Details</value>
      <webElementGuid>3ae065f3-b30c-4ff3-904e-d59a1960c877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>cad5d672-c90d-4ef4-9bf7-fec01963777f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c9fab1f0-4d5e-489b-89a0-26cba9d81bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>da9c8dc7-6859-4b07-8b2b-c760f15bfa2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>9ce50319-91da-4bb4-81f7-a9badf03d36e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>0d4ca145-f88d-41d6-8141-b68e5feec189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cc29289b-3328-4111-a60b-c9ce15060c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation/payment-details?p8_donor_id=&amp;p8_org_id=149&amp;clear=8&amp;session=5645694127925&amp;cs=12f96Z25blRQvH5f6fHktd-6l5lSgE-hpD0KlcubMr1QH3dD9bKFh1ZrrCkuNBgDRQofR7lyK7eofI1IiPbZ1Bg&amp;dialogCs=I7g5lC6hyc5l2TFfHD0FO0B9Ff3b-NxynFC94M54WoXDovT8X7fF13CbDSAPN1iV1M5iyvQXrMYTI-AvAzKVdw' and @title = 'Payment Details']</value>
      <webElementGuid>0d257d8f-6788-4e29-b08d-5abf247fd690</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
