<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referance Number_P8_REFERANCE_NUMBER</name>
   <tag></tag>
   <elementGuidId>a89f8bd6-b140-41c6-9885-2a9523d3c032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P8_REFERANCE_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P8_REFERANCE_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>202ec447-ef9a-4535-8ca1-5a2eec0d1306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16498095-2595-49ca-9a48-e0a4d9bb6bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P8_REFERANCE_NUMBER</value>
      <webElementGuid>85165457-780e-437c-8757-40a37f25d8b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P8_REFERANCE_NUMBER</value>
      <webElementGuid>066fb910-4279-4cee-be0e-e94abc53c16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>e788df14-a0a1-439d-ac62-f990111a61b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>0a323c12-5ac3-46c6-af2e-359521f8fcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>d2630dde-6059-45d3-b9e1-3ec506565451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>c3d378a1-d856-48f0-849d-96c0bc1a9b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P8_REFERANCE_NUMBER&quot;)</value>
      <webElementGuid>e92a573a-44ee-4325-b1ae-859f64426222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Receipt Generate(BJS User)/Page_Receipt_details/iframe</value>
      <webElementGuid>7d067527-2586-46b3-ad3d-dde2ba8fa205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P8_REFERANCE_NUMBER']</value>
      <webElementGuid>fd4efc8e-1d55-4af5-bd77-0337c85e4d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P8_REFERANCE_NUMBER_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>aa03929c-b122-4af4-a220-54f495c1fe7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>261de246-369d-4015-842b-7f1c074e5e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P8_REFERANCE_NUMBER' and @name = 'P8_REFERANCE_NUMBER']</value>
      <webElementGuid>4d3e2bd6-45df-42cb-8dd1-fd1ee4247dad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
