<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Received Date_a-Icon icon-calendar</name>
   <tag></tag>
   <elementGuidId>e21cb1f4-3e8e-4a18-a3f1-0e4cd1bb26ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a-date-picker[@id='P8_RECEIVED_DATE']/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.a-Icon.icon-calendar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>96ee5be5-34c5-407f-93d7-4df12e54abdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Icon icon-calendar</value>
      <webElementGuid>600a5c63-a181-4f02-ad6e-d57269b77f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P8_RECEIVED_DATE&quot;)/button[@class=&quot;a-Button a-Button--calendar&quot;]/span[@class=&quot;a-Icon icon-calendar&quot;]</value>
      <webElementGuid>562e2788-fb34-4bc2-83ef-37e7526da2c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Receipt Generate(BJS User)/Page_Receipt_details/iframe</value>
      <webElementGuid>b8ece0ca-055e-4297-bcfe-bbd4544d84c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a-date-picker[@id='P8_RECEIVED_DATE']/button/span</value>
      <webElementGuid>b0928572-299a-4195-af6c-2080690c6cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a-date-picker/button/span</value>
      <webElementGuid>2da6ddd6-cf0e-45d3-965d-665722f3058d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
