<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_P131_X_USERNAME</name>
   <tag></tag>
   <elementGuidId>cf443652-1bee-462d-8c6e-947c62c33563</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P131_X_USERNAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P131_X_USERNAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0fe126b7-31f4-45b3-b1e1-d21cee21dcc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0a40f0e-1f62-46d3-a732-b1a6cdf08e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P131_X_USERNAME</value>
      <webElementGuid>0de6e73c-2c0b-4498-accb-621ca9252af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P131_X_USERNAME</value>
      <webElementGuid>dbf0ae55-c2e3-41c5-9736-288519dce8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>dfbcf5a4-a2a3-4146-8808-0d0138cf82b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>f0e68ebe-d43d-40fd-974c-2804b0dab25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P131_X_USERNAME&quot;)</value>
      <webElementGuid>2d702e1a-affc-4b30-859a-957aea01c343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Create User(MV School)Admin/Page_Users List/iframe</value>
      <webElementGuid>eba6b9d6-bb77-48fd-ad04-0e5c8ae8a20a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P131_X_USERNAME']</value>
      <webElementGuid>de877c74-db9b-4753-bd7c-8955231e6ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P131_X_USERNAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>fd395b64-165a-49a8-8052-ceac8e17e560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>f8d4f5f9-0b82-4348-9df9-3331f0390798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P131_X_USERNAME' and @name = 'P131_X_USERNAME']</value>
      <webElementGuid>bb5c34e7-a608-467d-adb6-0e66348fbc65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
