<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_P131_X_PASSWORD</name>
   <tag></tag>
   <elementGuidId>c31a8c92-7dde-4037-9e76-ee99c0b3c2df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P131_X_PASSWORD</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P131_X_PASSWORD']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c060ad8d-5e4e-4506-8348-2f7472630db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e4b61452-7268-40a8-a7bb-91e4b68d763b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P131_X_PASSWORD</value>
      <webElementGuid>ee05ed03-7bd5-4ab0-b9bf-6c438e221221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>e4ede540-4dfc-4219-aec2-54d0895e3b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P131_X_PASSWORD</value>
      <webElementGuid>276c168e-c39f-4b90-a8cf-292e6e6ef4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password apex-item-text</value>
      <webElementGuid>2bee3138-27fc-4c3c-94d1-a14cecd7d90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return apex.submit({request:'P131_X_PASSWORD',submitIfEnter:event})</value>
      <webElementGuid>84c73561-c2ab-423e-991a-857504418730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P131_X_PASSWORD&quot;)</value>
      <webElementGuid>5178a65f-edd2-4a82-95be-39f8fbe214ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Create User(MV School)Admin/Page_Users List/iframe</value>
      <webElementGuid>3670bc8a-9a86-4885-9b2a-61781fecbee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P131_X_PASSWORD']</value>
      <webElementGuid>e30436be-b27a-4aa8-8e31-99bca548d909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P131_X_PASSWORD_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>4f78cfb6-8e61-49f2-927e-61493c0a1de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>3060f4d7-ad4e-4f96-b82f-1f4801ef5ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'P131_X_PASSWORD' and @id = 'P131_X_PASSWORD']</value>
      <webElementGuid>0587600c-30ae-45eb-a515-670743c433dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
