<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Approved_t-Icon fa fa-eye</name>
   <tag></tag>
   <elementGuidId>4ca23d24-3b00-4ae7-a898-5a060ae10c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.t-Icon.fa.fa-eye</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='187237571565538176_orig']/tbody/tr[2]/td[9]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bfca2736-5e2c-4cb4-8e62-ef3fa512ff77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Icon fa fa-eye</value>
      <webElementGuid>c5f992f9-d8be-4e79-8a64-ce12ad8602a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;187237571565538176_orig&quot;)/tbody[1]/tr[2]/td[@class=&quot;u-tC&quot;]/a[@class=&quot;t-Button t-Button--warning  t-Button--simple&quot;]/span[@class=&quot;t-Icon fa fa-eye&quot;]</value>
      <webElementGuid>4ae2c2f7-781f-477c-9e33-5e4c5e97ac15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='187237571565538176_orig']/tbody/tr[2]/td[9]/a/span</value>
      <webElementGuid>89bd5c44-e1ec-4a2a-a76f-6275096ae5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[9]/a/span</value>
      <webElementGuid>b83d2d30-ccf5-4e8c-b226-0f54a08fc08b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
