<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_P9999_USERNAME</name>
   <tag></tag>
   <elementGuidId>97d76ee8-1e71-4adf-9aed-39573cbfec54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P9999_USERNAME']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P9999_USERNAME</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbc13d2d-f25d-41e8-9023-e78ca2a8b6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9cbbaf8a-c81a-40f2-bec8-261612418da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P9999_USERNAME</value>
      <webElementGuid>ec09db8b-c4e7-479d-a137-46e14792894c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P9999_USERNAME</value>
      <webElementGuid>2d7070db-911c-49e1-a728-512df17b6282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>c9fe3251-494f-4dca-b6d3-e45d86065e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text apex-item-has-icon</value>
      <webElementGuid>58ed084e-7786-489f-9acb-8922683baba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>62592e44-83ab-4b22-9532-9ae9a40144d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>27869282-bcf6-4e0a-8026-cd44f11f0c3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7f630ff5-ea06-49c6-b152-06e04df6c522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>3aa95114-4e32-4225-9e8a-76c24a189f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P9999_USERNAME&quot;)</value>
      <webElementGuid>69c8ca31-530e-4d04-ba90-2dac59970bae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P9999_USERNAME']</value>
      <webElementGuid>438afa2d-bc1d-44a7-a8d9-0b6605d9a2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P9999_USERNAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>cec50c96-0b54-43d3-a535-7e43d264cfe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>93056d40-0d50-4ea2-93f7-a9809abf2263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P9999_USERNAME' and @name = 'P9999_USERNAME' and @placeholder = 'Username']</value>
      <webElementGuid>7358225e-8e74-4c10-bdbf-3c03b9b1ad3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
