<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save</name>
   <tag></tag>
   <elementGuidId>a981220f-1e0b-4e48-ad2c-ad28c54d15c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.t-Button-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B105459539703866208']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>26b462f6-d2bc-4c1e-bb5a-e320091024e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button-label</value>
      <webElementGuid>9bfc3c57-3cff-46b5-b0d4-047d13f17033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>f8312d7e-6b2f-47fe-bfd4-c1321f689b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B105459539703866208&quot;)/span[@class=&quot;t-Button-label&quot;]</value>
      <webElementGuid>3935ae33-343c-4692-9357-d345d3f36c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Another master entries (Meeting coordinator)/Page_Administration/iframe</value>
      <webElementGuid>3599fb6b-857b-4cd9-a735-fccfb76f77d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='B105459539703866208']/span</value>
      <webElementGuid>88a149f0-1135-4e32-a495-fb16d1591760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[2]/following::span[2]</value>
      <webElementGuid>d879d106-cac5-418a-ae4d-db537a735a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancle'])[1]/preceding::span[1]</value>
      <webElementGuid>455d0877-33f3-41fc-be52-8130eab6e995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::span[4]</value>
      <webElementGuid>f0722055-7ba2-43d2-bf0d-8a3947f25f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>4829974c-3c77-446c-bcff-4620df10f1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>b0336305-c97b-47ec-9aad-e3d46c00dd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>1d5972dc-d199-494a-936b-d2bba181c339</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
