<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_concat(id(, , C189414662760424153,_26fb6d</name>
   <tag></tag>
   <elementGuidId>256e6473-417e-4c5c-b6fd-22a9d7a969d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C189414662760424153</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='C189414662760424153']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>12caa507-1cd9-4bc7-8c01-e357227d4ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>189414662760424153</value>
      <webElementGuid>b65c9d7e-6914-4fb6-b989-46995053e521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>52244773-69ee-41e1-ae08-5ea409e6e707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>0f7f9889-e60a-44f8-838c-8c39cc02d9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C189414662760424153</value>
      <webElementGuid>1d47d621-9340-4493-9ade-d3398dad9604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea apex-item-textarea js-ignoreChange js-uses-enter</value>
      <webElementGuid>6d569734-394f-4845-906c-80eb9d3f67ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resizable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>367a3e58-89c0-4fcf-8dd1-753cc5a192a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>19cb9900-2493-4627-8ae2-41d9a4678b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C189414662760424153_HDR</value>
      <webElementGuid>3be4d93c-be2d-43bd-a385-a8a08e5b59d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C189414662760424153&quot;)</value>
      <webElementGuid>507e989f-5481-46f2-9b96-18ea92f263ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Another master entries (Meeting coordinator)/Page_Administration/iframe</value>
      <webElementGuid>e6ba3094-ef1c-4c92-9018-a322bc6ed219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='C189414662760424153']</value>
      <webElementGuid>73bcf9e3-2a37-4cf8-b4ef-f94bd6215c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div/div/textarea</value>
      <webElementGuid>4c71e573-2451-4fa8-990a-131e3851026d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = '189414662760424153' and @id = 'C189414662760424153']</value>
      <webElementGuid>1eb9426c-6640-49b1-bb46-532ec2644be8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
