<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>13bb125e-5f49-4e74-9eec-22fb11a87ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Payment Details&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a8e61c6a-d4f6-4966-bcd1-c03cea5820c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation177/payment-details?p8_donor_id=41&amp;p8_org_id=149&amp;clear=8&amp;session=2610388511477&amp;cs=1Xleh9-6NTzeXUyEWST_semxWpF-tuFc9jd2Frt8JOEu7F29Z7ao_AVmJgNvzvxbwG_SHwEYrpPaxWpgX4WGmHw&amp;dialogCs=-poeXtXcnzJerpt9V6ya7J6sIYqu9P7hdQlM9KrSWG7rqnBKImjWxMwWSiVXeYq4TBhNVQphTuLRAfQKHmmL0Q</value>
      <webElementGuid>595e0b25-1abd-4084-b2ac-1f6d2687f7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Payment Details</value>
      <webElementGuid>614a2c32-1b41-40e5-8d81-779739e5a985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>30b49be5-3783-4c2f-8b36-e0e303a6ff5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e5784d25-cd16-4134-8e7d-0d012deecebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>a5ced6af-a428-4b04-b48b-47c90de7a91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>a10e80ed-7e3d-45cc-8188-102a51eb1269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>36c4be38-7bcd-493c-9f6e-8697f037ce1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6412b266-d928-46f2-9e5f-f1f7258f8a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation177/payment-details?p8_donor_id=41&amp;p8_org_id=149&amp;clear=8&amp;session=2610388511477&amp;cs=1Xleh9-6NTzeXUyEWST_semxWpF-tuFc9jd2Frt8JOEu7F29Z7ao_AVmJgNvzvxbwG_SHwEYrpPaxWpgX4WGmHw&amp;dialogCs=-poeXtXcnzJerpt9V6ya7J6sIYqu9P7hdQlM9KrSWG7rqnBKImjWxMwWSiVXeYq4TBhNVQphTuLRAfQKHmmL0Q' and @title = 'Payment Details']</value>
      <webElementGuid>aa09de41-25b7-4bf6-99b5-3ac223873a39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
