<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount_P8_AMOUNT</name>
   <tag></tag>
   <elementGuidId>823e68da-741f-479f-a543-492d4bd01a5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P8_AMOUNT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P8_AMOUNT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>079457aa-137c-4bef-9521-c03eccb3c6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4eedae96-ad6f-40cd-9019-4e563af06a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P8_AMOUNT</value>
      <webElementGuid>e5af426c-284d-413b-9cf7-133f26ca3229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P8_AMOUNT</value>
      <webElementGuid>70971e7a-cafb-4013-8958-31cf47e4b799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number</value>
      <webElementGuid>f85dddfd-6c73-408f-b18f-86fa2ca317c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>0f5d4a6d-8533-49c7-b715-0230a90ff535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>c543e473-7a46-4458-a051-0ab724f219e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-format</name>
      <type>Main</type>
      <value>999G999G999G999G999G999G990</value>
      <webElementGuid>6739bc56-2f55-4bdb-b3b6-885cf4d16ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>d81bc5ec-18cc-4e37-8263-6acd12bf3aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P8_AMOUNT&quot;)</value>
      <webElementGuid>4222cc38-e3cc-430c-a12a-80dfd9aa5074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add Receipt(Donor Receipt)OLD/Page_Donor Details/iframe</value>
      <webElementGuid>9f5f3945-97e7-4ddf-b0bf-e2dd8ee4fe99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P8_AMOUNT']</value>
      <webElementGuid>70c3b2b6-0077-4797-a046-9399325f2fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P8_AMOUNT_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>5fac610d-fbfe-4382-9c5f-99f8afeefff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>40436b1b-b419-4728-889d-7c12edddbbe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P8_AMOUNT' and @name = 'P8_AMOUNT']</value>
      <webElementGuid>cc01447b-9028-497f-8609-86507232d1e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
