<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Referance Number_P8_REFERANCE_NUMBER</name>
   <tag></tag>
   <elementGuidId>43ea36fc-b7f6-4419-bd2a-e27609fd0640</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P8_REFERANCE_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P8_REFERANCE_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ce8fef7-dfa0-410e-abb8-8449ae4abc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9e947c0c-b05c-4e5d-b63a-470f09059567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P8_REFERANCE_NUMBER</value>
      <webElementGuid>a04b5165-5390-4fd7-96dc-5dc0a106b13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P8_REFERANCE_NUMBER</value>
      <webElementGuid>8c9d4c40-59ea-48dc-b35d-885cad789c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>79ec8922-8e0d-469a-966e-0f7b0af280ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>a7c4a798-4c11-4184-a5e6-4e9bddc22bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>39bd9958-a099-47f2-a671-38f7f033e401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>6c062bbb-2b86-46ab-8ad5-850b9753429e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P8_REFERANCE_NUMBER&quot;)</value>
      <webElementGuid>d6e8d6cc-89ec-48e0-bfb5-4d3f7f86b396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add Receipt(Donor Receipt)OLD/Page_Donor Details/iframe</value>
      <webElementGuid>485a128d-6dc2-40a8-b741-e7b1400c6c93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P8_REFERANCE_NUMBER']</value>
      <webElementGuid>b5681567-6a40-4c10-8507-699eee165cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P8_REFERANCE_NUMBER_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>9c4a2186-2c6d-4977-bc1c-f5268a94e2b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>97d56e55-e0eb-47d0-aaa0-90f26a4d0716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P8_REFERANCE_NUMBER' and @name = 'P8_REFERANCE_NUMBER']</value>
      <webElementGuid>2b90ddb6-39ff-4978-b24e-8a736d338aa7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
