<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Purpose_P8_PURPOSE</name>
   <tag></tag>
   <elementGuidId>de0350e2-fc29-4882-b852-7705d5c007e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='P8_PURPOSE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P8_PURPOSE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>f1292503-3191-4837-96e4-ea3d7aadb6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P8_PURPOSE</value>
      <webElementGuid>51bdbd0b-0a37-428b-a085-1d34a104f4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c3745149-9354-49d4-9768-0da503a28982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>635d5bcb-4879-49ca-a3a4-fd504d0d090d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>03e5e714-4457-4c04-8560-fa90315d84ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P8_PURPOSE</value>
      <webElementGuid>47764dc3-9cb0-4c7b-8a6c-a3b1fbb219d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea apex-item-textarea</value>
      <webElementGuid>bc33f27a-ebd5-4128-a697-a4ec1f16b5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-resizable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>43bc47b8-0532-4787-8b08-4db0b4457c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P8_PURPOSE&quot;)</value>
      <webElementGuid>47efaf49-2b0f-49ca-ae65-c3542dcd41d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Add Receipt(Donor Receipt)OLD/Page_Donor Details/iframe</value>
      <webElementGuid>51a2c458-a944-41c8-a064-b73487494561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='P8_PURPOSE']</value>
      <webElementGuid>0800cf4e-5f06-47d0-88c7-19c1220d2f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P8_PURPOSE_CONTAINER']/div[2]/div/div/textarea</value>
      <webElementGuid>cc0d1e9e-8917-45e6-9b7c-fccad3e72473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>6c14ce0a-1f15-4c44-97ac-ef21abe02725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'P8_PURPOSE' and @id = 'P8_PURPOSE']</value>
      <webElementGuid>4a4475e7-710d-40a2-8b43-5e2b810a1d78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
