<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In</name>
   <tag></tag>
   <elementGuidId>83d4ca0b-7562-4c06-b6a2-4c1555806df1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#B155334272622192457</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='B155334272622192457']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>210f608b-aceb-4d3b-a3fc-4a5d9b2add57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>apex.submit({request:'LOGIN',validate:true});</value>
      <webElementGuid>d4f6e372-1974-46c8-b3b6-fa58da864b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--hot </value>
      <webElementGuid>f435662d-477e-44a5-b0ac-2e4f3884bac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e449b054-4e71-4f81-aa9a-fa20667a3d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>B155334272622192457</value>
      <webElementGuid>c244af3a-d1ae-4abf-ac46-150ee4fffbbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>713f6931-e415-4bcd-b2c3-def948388f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;B155334272622192457&quot;)</value>
      <webElementGuid>affdc3ab-bcf7-40ae-abcb-0ec4effe665e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='B155334272622192457']</value>
      <webElementGuid>6672df20-3c1d-4398-9d41-98c5ebd47df6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R155332203756192450']/div[3]/button</value>
      <webElementGuid>ca5b8341-ef8f-4f52-92ee-50e044ee2c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::button[1]</value>
      <webElementGuid>f19089bd-d94c-4b1a-b4d6-82ff8b2eba51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::button[1]</value>
      <webElementGuid>26c7a760-faf1-47e5-a8fb-1517706cb13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'B155334272622192457', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>3c3fff6e-e28e-4837-a27d-ced7a9f08933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4d1b83f9-85f9-43af-b83d-ac4b2e0ec7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'B155334272622192457' and (text() = 'Sign In' or . = 'Sign In')]</value>
      <webElementGuid>a9df72ba-141e-4ebc-a31d-78cf68a6304f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
