<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>8438050b-5fd1-43c6-9159-716fceefdc97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Areas Of Interest&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a9a6f8e3-6d5c-4b5a-8802-c8ec5b33d6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/areas-of-interest?clear=105&amp;session=3521688964023&amp;cs=3BFfCm3Fea-zVyZnk_PBguMUqOQuQE8xKXhjd4hWSv4e8QUc5L6Q_TlVRA8eWBolF7iiVwOO1iCthnQkrsZ8Wsg&amp;dialogCs=66iW1IsrtEWQ9KRQL5eVsNn8-ZnVpHcLTMVuIm8DC7iNmvuAnBmYYM6giBRSXnrLTqdw-SsZUsAq6AhIbmGvRQ</value>
      <webElementGuid>62a6f69f-723b-4351-928b-28b121587c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Areas Of Interest</value>
      <webElementGuid>3ee40821-41a1-4a73-9666-7438ac3b45d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2db3a5d4-1ba1-42a8-9c14-707c1bdd8858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>dfd4da5e-e4d1-4df6-8785-8e91296cacd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c2396c5a-80b9-4654-897b-4c602acd9bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>9bb7f285-d4a4-4357-960f-301767825a41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>cf8cd855-0544-4433-8f57-e6d56d7bd191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>bc53deed-8039-4231-af8a-fd63ddb9421f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/areas-of-interest?clear=105&amp;session=3521688964023&amp;cs=3BFfCm3Fea-zVyZnk_PBguMUqOQuQE8xKXhjd4hWSv4e8QUc5L6Q_TlVRA8eWBolF7iiVwOO1iCthnQkrsZ8Wsg&amp;dialogCs=66iW1IsrtEWQ9KRQL5eVsNn8-ZnVpHcLTMVuIm8DC7iNmvuAnBmYYM6giBRSXnrLTqdw-SsZUsAq6AhIbmGvRQ' and @title = 'Areas Of Interest']</value>
      <webElementGuid>97603f0f-1a66-48d8-baeb-ed72b7cc8ed6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
