<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_1</name>
   <tag></tag>
   <elementGuidId>394ca3e7-d6cf-48d1-991a-6caa0ed15e3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Participation Level&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_2']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>56034d36-1924-403a-bf06-2c62aea2d84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/participation-level?session=3521688964023&amp;dialogCs=suMmxX_QT28ekZ-X07NNSaMh2R7lezZ4q0xfbYPPuBUOBy55WPPRI3Cd9w-VdcTg-QfEIiFlI6y5E4EcWHSUfg</value>
      <webElementGuid>9c00f15b-2636-438c-9cca-3a2910861e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Participation Level</value>
      <webElementGuid>dc69c8ab-3f8d-4ab0-b4f1-285241302354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9c006109-d7e7-47b2-9e4b-ed623c082e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>bf703ab2-da6e-40bd-adf1-62657380cdd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>333ce9f1-49fe-495f-9066-a0ccfb076864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_2&quot;)/iframe[1]</value>
      <webElementGuid>a8c1a2ef-7073-4e46-b01a-3affc5e76ac3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_2']/iframe</value>
      <webElementGuid>ce056f99-473f-4ba1-8639-56480d329e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cc546423-da14-427e-961c-786c2b4db97e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/participation-level?session=3521688964023&amp;dialogCs=suMmxX_QT28ekZ-X07NNSaMh2R7lezZ4q0xfbYPPuBUOBy55WPPRI3Cd9w-VdcTg-QfEIiFlI6y5E4EcWHSUfg' and @title = 'Participation Level']</value>
      <webElementGuid>83d1d760-7e99-438d-bd20-159ed8546bf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
