<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Manage_238931663623776432</name>
   <tag></tag>
   <elementGuidId>6606ad56-4bd2-4c0b-aef6-96fbc68deec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C238931663623776432</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='C238931663623776432']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8804b9b4-4fcb-4efe-a32b-291dbf1604e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4003bc58-fcda-41c1-b7ea-cef40a835d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C238931663623776432</value>
      <webElementGuid>17ff5ce7-d467-48fa-b30a-35c6f4947257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>238931663623776432</value>
      <webElementGuid>f55de231-b46f-4ed4-9dd7-b801af818ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text js-ignoreChange</value>
      <webElementGuid>a12e2491-45ba-417f-b44e-e2a9391ea8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>6f2dab4c-7a7c-4e0e-a10c-7d28e2d09837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb1e4d8f-a795-459a-a75d-b245a7a17f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C238931663623776432_HDR</value>
      <webElementGuid>84121a19-6edc-4687-83fb-41cd2ae8dd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C238931663623776432&quot;)</value>
      <webElementGuid>ad37e6c5-c2a7-46ca-8625-2d5117f82a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Page_Administration/iframe</value>
      <webElementGuid>757bbdbc-e1f8-47bb-b269-3fde03dc5242</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='C238931663623776432']</value>
      <webElementGuid>e299fd79-3623-4964-90fa-ac4b2310ad52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='R238927834646776423_ig_grid_vc_cur']/div/input</value>
      <webElementGuid>bcfc93ad-f346-45ce-af41-257aff9360fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>efceb732-9dd8-4369-8d39-b28e1e2cefce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'C238931663623776432' and @name = '238931663623776432']</value>
      <webElementGuid>d070f8f4-4dbc-4352-8bd8-aacdf1915afc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
