<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Medium_239001515090148825</name>
   <tag></tag>
   <elementGuidId>e663569b-eb6d-42b7-ba14-633495e42cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#C239001515090148825</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='C239001515090148825']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>688fc6f8-05d8-4223-9c83-421b9a3ad951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>472273fa-4d99-42da-968b-f0832dd3b3d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>C239001515090148825</value>
      <webElementGuid>61be4976-185e-4829-9f7c-d4f909626641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>239001515090148825</value>
      <webElementGuid>34f2d5b5-c180-45f3-accd-d86070f725dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number js-ignoreChange</value>
      <webElementGuid>8c480551-38a1-4bc6-a966-d742afca6e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>f2f84bae-7721-4c4f-bc7a-e74e05378762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d0b8a25-d7b8-4764-a9d4-b51263fe22c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>C239001515090148825_HDR</value>
      <webElementGuid>7d603d12-4e08-4797-9131-64ea2e4a3bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;C239001515090148825&quot;)</value>
      <webElementGuid>b9b7f3ae-72fe-47b0-98ab-d569ebd48b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Page_Administration/iframe_1</value>
      <webElementGuid>80213069-eea5-42aa-8838-7e786552b77d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='C239001515090148825']</value>
      <webElementGuid>e90d2b48-14e9-444a-a25a-f474179f0d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='R238998786485148822_ig_grid_vc_cur']/div/input</value>
      <webElementGuid>0ada5b13-1a8c-4b96-83dc-b73c35c2ed77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>af97da28-cfc9-408a-afda-c62e4f75b696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'C239001515090148825' and @name = '239001515090148825']</value>
      <webElementGuid>d13ffc04-6f34-4c39-9faa-0b5ca0ed2378</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
