<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_List of Areas of Interest</name>
   <tag></tag>
   <elementGuidId>bd639848-6ac2-4f24-b387-4e89798f583b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='R238289924594005295']/div[2]/div[2]/ul/li[2]/a/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6d568c67-506e-479b-bc7a-528196c8600a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-MediaList-desc</value>
      <webElementGuid>83ed7e7a-9ba7-42d0-83dc-7382831bbfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>List of Areas of Interest</value>
      <webElementGuid>2de0c614-d01c-4162-a4f9-1dd891392da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R238289924594005295&quot;)/div[@class=&quot;t-Region-bodyWrap&quot;]/div[@class=&quot;t-Region-body&quot;]/ul[@class=&quot;t-MediaList t-MediaList--showIcons t-MediaList--showDesc u-colors&quot;]/li[@class=&quot;t-MediaList-item&quot;]/a[@class=&quot;t-MediaList-itemWrap&quot;]/div[@class=&quot;t-MediaList-body&quot;]/p[@class=&quot;t-MediaList-desc&quot;]</value>
      <webElementGuid>303c5a14-e3f6-4ffa-9d31-2a5b23982fef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R238289924594005295']/div[2]/div[2]/ul/li[2]/a/div[2]/p</value>
      <webElementGuid>77ba36c4-4b45-442b-9c80-9f9dc3654cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Areas Of Interest'])[1]/following::p[1]</value>
      <webElementGuid>8d4532f5-5d7b-47e3-bee7-c6359e98f253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Projects'])[1]/following::p[2]</value>
      <webElementGuid>337128b0-196f-4c09-a6d3-74117dc2eb36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participation Level'])[1]/preceding::p[1]</value>
      <webElementGuid>0254deb9-0721-4ce7-9e38-d113c0ff326e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member Designation'])[1]/preceding::p[2]</value>
      <webElementGuid>8ebe3d3d-f3cc-493f-9920-8bdef251ef75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='List of Areas of Interest']/parent::*</value>
      <webElementGuid>a26a2efb-b69b-4a03-9d7b-5a3c537788ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div[2]/p</value>
      <webElementGuid>3c92e797-1358-4716-9ba5-91d1e2ba0a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'List of Areas of Interest' or . = 'List of Areas of Interest')]</value>
      <webElementGuid>666353ec-5d00-49f3-a018-9752fdfda90c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
