<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Manage List of participation level</name>
   <tag></tag>
   <elementGuidId>5508cf44-7f28-454c-8a12-913ab2ecacd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='R238289924594005295']/div[2]/div[2]/ul/li[3]/a/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a12c505a-b45e-4c2b-9aac-55998ac4e347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-MediaList-desc</value>
      <webElementGuid>e37ad4b7-971b-4f7f-9daf-7ea9ba6095fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage List of participation level</value>
      <webElementGuid>fa9110a1-8648-4418-8255-430b96009084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R238289924594005295&quot;)/div[@class=&quot;t-Region-bodyWrap&quot;]/div[@class=&quot;t-Region-body&quot;]/ul[@class=&quot;t-MediaList t-MediaList--showIcons t-MediaList--showDesc u-colors&quot;]/li[@class=&quot;t-MediaList-item&quot;]/a[@class=&quot;t-MediaList-itemWrap&quot;]/div[@class=&quot;t-MediaList-body&quot;]/p[@class=&quot;t-MediaList-desc&quot;]</value>
      <webElementGuid>9e20811d-cc11-4d25-a34f-581c10a95d39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R238289924594005295']/div[2]/div[2]/ul/li[3]/a/div[2]/p</value>
      <webElementGuid>fbaf3422-5f78-4992-b8e5-a496150e1956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participation Level'])[1]/following::p[1]</value>
      <webElementGuid>52d6f9ba-797b-420f-afd5-7acc51044e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Areas Of Interest'])[1]/following::p[2]</value>
      <webElementGuid>9fc3ddbd-59a8-407b-b443-7099813c46ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member Designation'])[1]/preceding::p[1]</value>
      <webElementGuid>c65d1dd9-e2f7-4391-92fb-eb2f5e9bb1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Member Master'])[1]/preceding::p[2]</value>
      <webElementGuid>2a67482e-a2f4-4779-bb4c-6753b2e63317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage List of participation level']/parent::*</value>
      <webElementGuid>ba6ec9c7-b8d2-4ab2-b795-0af6286ef82f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div[2]/p</value>
      <webElementGuid>ca6482b8-6880-4873-aede-efaafe24dc17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Manage List of participation level' or . = 'Manage List of participation level')]</value>
      <webElementGuid>358a23af-4e37-4cbf-b919-4b8b5f11c08c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
