<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Manage all projects by organisations</name>
   <tag></tag>
   <elementGuidId>0d7e52b3-c57b-428f-9b9e-e5cf4ea973d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.t-MediaList-desc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='R238289924594005295']/div[2]/div[2]/ul/li/a/div[2]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bc509abf-6810-49ed-a8e5-04225b5cc9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-MediaList-desc</value>
      <webElementGuid>09587ab1-5d3b-446c-b684-078621002980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Manage all projects by organisations</value>
      <webElementGuid>389f2667-d851-486c-b044-243dc9060d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R238289924594005295&quot;)/div[@class=&quot;t-Region-bodyWrap&quot;]/div[@class=&quot;t-Region-body&quot;]/ul[@class=&quot;t-MediaList t-MediaList--showIcons t-MediaList--showDesc u-colors&quot;]/li[@class=&quot;t-MediaList-item&quot;]/a[@class=&quot;t-MediaList-itemWrap&quot;]/div[@class=&quot;t-MediaList-body&quot;]/p[@class=&quot;t-MediaList-desc&quot;]</value>
      <webElementGuid>5386c955-f005-42f3-b27c-ebc65d644ef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R238289924594005295']/div[2]/div[2]/ul/li/a/div[2]/p</value>
      <webElementGuid>d13da78b-72b6-45e7-a81a-d12c641c25fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Projects'])[1]/following::p[1]</value>
      <webElementGuid>c1b91dcd-b2c5-4f1b-a3f6-e22f72ba8337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration'])[1]/following::p[1]</value>
      <webElementGuid>786f86ea-594a-4cec-a3ec-a43a41154a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Areas Of Interest'])[1]/preceding::p[1]</value>
      <webElementGuid>1163e859-6af9-41e4-a3c7-a501dcf1ec85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participation Level'])[1]/preceding::p[2]</value>
      <webElementGuid>1c6523ed-fc5c-42a8-b20f-db355fc64f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Manage all projects by organisations']/parent::*</value>
      <webElementGuid>7d794b8b-43c3-4032-9409-00eb1d4b9672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>5fe0552a-2d46-4da2-89f6-061583ffb55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Manage all projects by organisations' or . = 'Manage all projects by organisations')]</value>
      <webElementGuid>e3ef2db6-aa1e-42ba-bb5f-31888cbb49f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
