<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--select any--MeetingEvent OneEvent _83ac3d</name>
   <tag></tag>
   <elementGuidId>3485d028-826e-4312-8741-f71444b12165</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P105_PLAN_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P105_PLAN_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>daba9bc2-a3dc-426a-9867-8520bedace66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P105_PLAN_ID</value>
      <webElementGuid>a437af48-63f5-417d-a677-b3dbc3c7be8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P105_PLAN_ID</value>
      <webElementGuid>1fef92c5-b080-4477-9ad2-2f52f19ee165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>1bad4ac0-60b2-4ad1-bdbe-6489f2e9fae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>55ad3b68-c5bc-4bc9-a206-09f064b0d8db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e9a19360-7820-4ac6-84f0-2f4629bcba13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--select any--
MeetingEvent OneEvent TwoChaturmas 2023</value>
      <webElementGuid>87c2bb6f-34a6-4250-b8dd-15d39b824854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P105_PLAN_ID&quot;)</value>
      <webElementGuid>742c63fc-2900-4c0d-87d2-8ed7d4702e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Page_Administration/iframe</value>
      <webElementGuid>0ca2d5d9-6473-4ab1-bba1-80eacb33c82f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P105_PLAN_ID']</value>
      <webElementGuid>e1a41132-abba-484b-887d-7c0ba3f52443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P105_PLAN_ID_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>1639ab65-f9a0-438f-a1b4-5a200134fd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[2]/following::select[1]</value>
      <webElementGuid>1648f4d4-543f-4aeb-9890-cb677b99ad73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::select[1]</value>
      <webElementGuid>541c8580-9093-4ce5-9fbb-57e9b74da693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::select[2]</value>
      <webElementGuid>7e97b61c-a6c9-4b5c-b6d9-a16edfc13880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/select</value>
      <webElementGuid>b25eaeba-9e39-4a12-a495-14ad88de97a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P105_PLAN_ID' and @name = 'P105_PLAN_ID' and (text() = '--select any--
MeetingEvent OneEvent TwoChaturmas 2023' or . = '--select any--
MeetingEvent OneEvent TwoChaturmas 2023')]</value>
      <webElementGuid>cd85b0f7-f0d6-40d0-9955-b6174629a59b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
