<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--select any--MeetingEvent OneEvent _83ac3d (1)</name>
   <tag></tag>
   <elementGuidId>31618cc1-993b-444d-b0d2-3ba25e459500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P106_PLAN_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='P106_PLAN_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dc23e3fb-f7e3-4999-8118-3fb49d297f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P106_PLAN_ID</value>
      <webElementGuid>59468989-1dcd-4fd5-8148-cee1ab9493a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P106_PLAN_ID</value>
      <webElementGuid>9be9eb69-cf96-40b0-aafe-dd3cd84c81d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectlist apex-item-select</value>
      <webElementGuid>c87592da-3069-40c0-a2c7-c69da1cd322a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-native-menu</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2a065df-2fbb-4916-983b-06354f5a2989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>7304be69-41f9-4a65-9490-74f61050779f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--select any--
MeetingEvent OneEvent TwoChaturmas 2023</value>
      <webElementGuid>9025fa76-5204-4caf-ba30-4f86582ae70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P106_PLAN_ID&quot;)</value>
      <webElementGuid>ba99a1cd-a1b9-4d74-a0bd-0c99de923461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Page_Administration/iframe_1</value>
      <webElementGuid>6fb6ca7c-2ea6-4ea8-846f-58b91ba9363a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='P106_PLAN_ID']</value>
      <webElementGuid>fbd744a9-b50b-4c7a-bed5-42b0cc8128ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P106_PLAN_ID_CONTAINER']/div[2]/div/select</value>
      <webElementGuid>7b0f4f62-5212-41d0-9b17-2641767b0506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[2]/following::select[1]</value>
      <webElementGuid>6c24059f-b3b3-44b1-9015-3cea70695228</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go'])[1]/preceding::select[1]</value>
      <webElementGuid>34e1556b-0c69-47b1-8aae-c956ee35fcde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actions'])[1]/preceding::select[2]</value>
      <webElementGuid>f62f2345-7069-48b3-b5d0-bb0384b0b359</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/select</value>
      <webElementGuid>06177ed5-e3f0-49b2-a092-1e331acb0458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'P106_PLAN_ID' and @name = 'P106_PLAN_ID' and (text() = '--select any--
MeetingEvent OneEvent TwoChaturmas 2023' or . = '--select any--
MeetingEvent OneEvent TwoChaturmas 2023')]</value>
      <webElementGuid>55ed9975-950c-4c34-be09-bb0b9566aada</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
