<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Medium_a-GV-cell u-tS is-focused</name>
   <tag></tag>
   <elementGuidId>0abf14ba-9926-4eba-a8bc-6dca9b78dbd4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.a-GV-cell.u-tS.is-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='R238998786485148822_ig_grid_vc']/div[4]/div[3]/table/tbody/tr[2]/td[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>237404c4-6eb4-4650-b4c8-c51967ac93c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3a1e3a55-28f4-4fe1-9d3c-60bef464b51a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>39aa5387-05cc-4f01-afc9-5442fe5b2811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-GV-cell u-tS is-focused</value>
      <webElementGuid>15dd43cd-4263-4006-87e0-5396043cace0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;R238998786485148822_ig_grid_vc&quot;)/div[@class=&quot;a-GV-bdy&quot;]/div[@class=&quot;a-GV-w-scroll&quot;]/table[@class=&quot;a-GV-table a-GV-table--checkbox&quot;]/tbody[1]/tr[@class=&quot;a-GV-row is-selected is-inserted&quot;]/td[@class=&quot;a-GV-cell u-tS is-focused&quot;]</value>
      <webElementGuid>96f677d3-15eb-4332-b031-a6e249567869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BJS Meeting coordinator/Adding Master (Meeting coordinator)/Page_Administration/iframe_1</value>
      <webElementGuid>3752f7d0-0c36-42a3-b215-35672d39c0a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='R238998786485148822_ig_grid_vc']/div[4]/div[3]/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>d5d1b88b-a379-43e3-8339-8bc64d28933e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]</value>
      <webElementGuid>20e60991-0787-467f-a677-e01b73ca9bae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
