<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_(Value Required)_P131_X_EMP_ID_lov_btn</name>
   <tag></tag>
   <elementGuidId>e181188a-9101-4ba9-b075-0a6014c6ea2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='P131_X_EMP_ID_lov_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P131_X_EMP_ID_lov_btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c4b4d578-61d1-40ec-b1c2-9756ba533abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b488a623-793e-461d-9b79-22de5a78bf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5bbd78d5-3ff1-4962-a0f2-91eb0210310a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-Button a-Button--popupLOV</value>
      <webElementGuid>a21332dd-49f3-4d53-9fc8-f2eabfe6741f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P131_X_EMP_ID_lov_btn</value>
      <webElementGuid>d8d2aaad-f805-4e52-8adc-e8be720416e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>d66cc2a8-0639-4ec7-8996-ccb34d3dd926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P131_X_EMP_ID_lov_btn&quot;)</value>
      <webElementGuid>15a827d6-4211-446b-90ea-0a73d5179d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/User Create(Meeting Coordinator)/Page_Users List/iframe</value>
      <webElementGuid>abaf198c-2b7d-4e3f-8434-0c07d335c90d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='P131_X_EMP_ID_lov_btn']</value>
      <webElementGuid>f2ddd6e7-e0e5-47b4-88c5-f6f4ca75df10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P131_X_EMP_ID_CONTAINER']/div[2]/div[2]/div/button</value>
      <webElementGuid>577e7fe1-8231-4fda-9aa1-517f87a939f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[1]/following::button[1]</value>
      <webElementGuid>f44a17a2-646b-4edb-9a53-c99ac4d82337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Value Required)'])[2]/preceding::button[1]</value>
      <webElementGuid>c1644a48-656e-4e50-b17f-322508bc226c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c90bf260-d6f0-4182-95ef-1d7133c2c29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'P131_X_EMP_ID_lov_btn']</value>
      <webElementGuid>3244c7ed-9b01-43fe-b9c0-777b04f03a87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
