<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click Here_apex-edit-pencil</name>
   <tag></tag>
   <elementGuidId>9aa44e1e-9804-47f3-a145-bc9aada93dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='239714087504221300_orig']/tbody/tr[15]/td/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f6b5da31-3a1c-46c8-aee8-d73b92d9d04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/i/23.1.1/app_ui/img/icons/apex-edit-pencil.png</value>
      <webElementGuid>a4d5131a-9b4b-41c3-8cd2-8de177f406f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>apex-edit-pencil</value>
      <webElementGuid>c888fe35-e921-4f63-8c6d-ae0845f0f73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;239714087504221300_orig&quot;)/tbody[1]/tr[15]/td[@class=&quot;a-IRR-linkCol u-tC&quot;]/a[1]/img[@class=&quot;apex-edit-pencil&quot;]</value>
      <webElementGuid>b056421e-399c-4960-ba1c-c8cabb103d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='239714087504221300_orig']/tbody/tr[15]/td/a/img</value>
      <webElementGuid>256bf645-3cc2-4764-a647-3467225a0048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td/a/img</value>
      <webElementGuid>26de2214-2068-48d9-959d-bf9868497286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/i/23.1.1/app_ui/img/icons/apex-edit-pencil.png']</value>
      <webElementGuid>26a1a072-1721-401d-bb14-10bdf840960f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
