<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P131_X_PASSWORD</name>
   <tag></tag>
   <elementGuidId>56153b80-d815-4d3b-8d79-e50c10bb698d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P131_X_PASSWORD']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P131_X_PASSWORD</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6111fa6f-15d8-452c-9e39-f0a86d199611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6b17f94a-6b2f-4eeb-8569-405b6f4b386e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P131_X_PASSWORD</value>
      <webElementGuid>7ea17987-92cf-4d90-9ef9-a7735cbdc2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>16a8a10d-f1bf-47c0-a5bf-2b1959c641c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P131_X_PASSWORD</value>
      <webElementGuid>6727eaf8-f4ea-464e-b429-77aec1960b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>password apex-item-text</value>
      <webElementGuid>80edb3a3-cdb5-4d95-9115-1eaa53e7b377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return apex.submit({request:'P131_X_PASSWORD',submitIfEnter:event})</value>
      <webElementGuid>002b42d2-1484-42ac-8033-fe1662a2c759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P131_X_PASSWORD&quot;)</value>
      <webElementGuid>62f9c5ed-6f74-4b75-81ee-a3903f9f118b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/User Create(Meeting Coordinator)/Page_Users List/iframe</value>
      <webElementGuid>d39f2913-1983-477d-8263-3e8d8f581c14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P131_X_PASSWORD']</value>
      <webElementGuid>6a11fba6-f391-4080-bb33-366333b57eca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P131_X_PASSWORD_CONTAINER']/div[2]/div[2]/input</value>
      <webElementGuid>46560338-f06b-4f60-93c4-01085d4d44c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>ea8e1dfb-74f5-490d-8f48-532e233a32e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'P131_X_PASSWORD' and @id = 'P131_X_PASSWORD']</value>
      <webElementGuid>556f50c3-fea8-4d05-9812-afac6d1c2145</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
