<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Babasaheb Gite</name>
   <tag></tag>
   <elementGuidId>63c721bb-4690-4a61-b5e3-239812a89568</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='PopupLov_131_P131_X_EMP_ID_dlg']/div[2]/div/div[3]/ul/li[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fa180731-6a86-4f89-a601-adf481cdae3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>41</value>
      <webElementGuid>30803863-4d6b-4b1a-90d3-70866afbe2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-IconList-item</value>
      <webElementGuid>0ce09289-3b52-4507-a874-e9516bf77e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>a442399c-7c82-4617-81e8-ddc6e4823185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bd72c0bb-47ad-4294-a68d-a5e62ee04a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Babasaheb Gite</value>
      <webElementGuid>5e889105-a339-486a-a216-05fb9829ea7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PopupLov_131_P131_X_EMP_ID_dlg&quot;)/div[@class=&quot;a-PopupLOV-results a-TMV&quot;]/div[@class=&quot;a-TMV-body&quot;]/div[@class=&quot;a-TMV-w-scroll&quot;]/ul[@class=&quot;a-IconList&quot;]/li[@class=&quot;a-IconList-item&quot;]</value>
      <webElementGuid>91f00fb7-9523-4daf-9be6-959d716b6787</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PopupLov_131_P131_X_EMP_ID_dlg']/div[2]/div/div[3]/ul/li[6]</value>
      <webElementGuid>3a27d3d6-e043-4105-8b82-ea3d5ecf81e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Avinash Suryavanshi'])[1]/following::li[1]</value>
      <webElementGuid>5a6325ac-8752-447f-80f5-8d46085ed2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asif Shaikh'])[1]/following::li[2]</value>
      <webElementGuid>2edca57e-bd13-474a-bae8-5cf7e4452c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bhagyashree Sawant'])[1]/preceding::li[1]</value>
      <webElementGuid>7a093943-462a-44b5-8f0f-223c589e6060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chakradhar Shelke'])[1]/preceding::li[2]</value>
      <webElementGuid>52ee9656-c794-424b-9329-24dad168ef64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Babasaheb Gite']/parent::*</value>
      <webElementGuid>a1f48e90-20fd-4fb9-af6c-f99c45190f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[6]</value>
      <webElementGuid>4d8eb413-2e78-4ab8-952e-f6a64a22c675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Babasaheb Gite' or . = 'Babasaheb Gite')]</value>
      <webElementGuid>6471c535-bac5-4f39-934a-0fdb38aa1a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
