<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skip to Main Content_t_Button_navControl</name>
   <tag></tag>
   <elementGuidId>eb96bf80-9dca-457f-87e5-9a2efab65bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='t_Button_navControl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#t_Button_navControl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>598feda2-367e-49bc-b3cf-3b1de485f94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Button t-Button--icon t-Button--header t-Button--headerTree</value>
      <webElementGuid>02cac7e1-ec24-4e44-b493-a960c32f2c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>8f0ed5ed-dbeb-4514-9c22-b921bb9e722e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Main Navigation</value>
      <webElementGuid>24f9b706-e2c8-4eb6-8977-1352fdac168b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>t_Button_navControl</value>
      <webElementGuid>7f45969e-b487-416f-8ea4-bb9ecfc87ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4864a44b-c082-4939-b78a-af2e794064f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>t_TreeNav</value>
      <webElementGuid>89b3785e-5934-47e7-bd3c-82c89fde142f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>476d4c57-0fb0-409c-abb7-d90c9fdcd725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_Button_navControl&quot;)</value>
      <webElementGuid>9db7b408-9c13-4eeb-9d5b-6c37cf5b3158</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='t_Button_navControl']</value>
      <webElementGuid>16b5e4df-c9fe-44ba-8f88-6d14be5aba4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='t_Header']/div/div/button</value>
      <webElementGuid>b243e1e4-8c7c-4434-8497-940d8ef58add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to Main Content'])[1]/following::button[1]</value>
      <webElementGuid>60c88d37-6324-46d1-a955-731765397512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Donor Receipt Generation'])[1]/preceding::button[1]</value>
      <webElementGuid>eadd36cd-304c-436d-9808-d5a1d2eb0fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Install App'])[1]/preceding::button[1]</value>
      <webElementGuid>18d36002-3f33-4ee1-9112-37d7a17bccdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>167e52b7-5707-4e04-a786-05084ef9be2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Main Navigation' and @id = 't_Button_navControl' and @type = 'button']</value>
      <webElementGuid>6d457a90-9c06-4d74-bd03-28806047e959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
