<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>60bf8032-fc73-4acb-bb6d-c0812ea62754</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Plan Master&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a63cc4c7-d34a-4e2b-9621-d9d5c65bb7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/plan-master?session=5964279848727&amp;dialogCs=_KnEmGoZ3qwHRXPjqa4sPl9KX698Wi5IBefC2gCqHOPNGVDro3ZUNTa7f3TPwninWPXMoydh18TuatsZlIXV0w</value>
      <webElementGuid>a0cb311a-d7ff-4488-9e68-96f814e3bf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Plan Master</value>
      <webElementGuid>8faca0d6-dd7d-49d5-a242-fa5d317de123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>1df1d2ab-da16-46d7-a564-0de599960d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>13fa7ac1-ea21-4aa3-88f9-ea2d285028b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>20e5aa13-b07d-4de3-a5f8-d04aefc84e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>b6e9ba35-ee6e-4ff0-b8d1-76442f884987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>f0ad3f5e-900d-4dfd-9a6c-18ea01274a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b6dd44b2-c703-48e0-b584-5541aaa7035b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/plan-master?session=5964279848727&amp;dialogCs=_KnEmGoZ3qwHRXPjqa4sPl9KX698Wi5IBefC2gCqHOPNGVDro3ZUNTa7f3TPwninWPXMoydh18TuatsZlIXV0w' and @title = 'Plan Master']</value>
      <webElementGuid>40293bf0-6bca-4737-bda6-982449346c1d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
