<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Plan Master_ui-button-icon ui-icon ui-_ef410f</name>
   <tag></tag>
   <elementGuidId>c580afd3-1ddb-4508-a83d-02333da7b89b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-button-icon.ui-icon.ui-icon-closethick</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='t_PageBody']/div[4]/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1e4b3f4e-7db5-4259-89e5-0b07de4fe54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-icon ui-icon ui-icon-closethick</value>
      <webElementGuid>c375280b-4da7-4122-9e79-6093aa513c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_PageBody&quot;)/div[@class=&quot;ui-dialog ui-corner-all ui-widget ui-widget-content ui-front ui-dialog--apex t-Dialog-page--standard ui-draggable ui-dialog--stretch&quot;]/div[@class=&quot;ui-dialog-titlebar ui-corner-all ui-widget-header ui-helper-clearfix ui-draggable-handle&quot;]/button[@class=&quot;ui-button ui-corner-all ui-widget ui-button-icon-only ui-dialog-titlebar-close&quot;]/span[@class=&quot;ui-button-icon ui-icon ui-icon-closethick&quot;]</value>
      <webElementGuid>633ab2e1-7a8a-47e5-b0a6-74762baaa3ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='t_PageBody']/div[4]/div/button/span</value>
      <webElementGuid>3f36a8f8-3b79-4298-a110-ab16dd29e4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button/span</value>
      <webElementGuid>f836fe09-6b45-4c74-aed4-0dbd7d851f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
