<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Skip to Main Content_t-Header-controlsIcon</name>
   <tag></tag>
   <elementGuidId>21d7df91-e29e-4a0d-b170-e4ba70136ca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='t_Button_navControl']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.t-Header-controlsIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>353006e5-ad47-4371-b87c-cf31670c2811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>t-Header-controlsIcon</value>
      <webElementGuid>b557cb8f-44a8-4884-9b62-fe959a2384bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dd79d963-eb31-4cee-81e4-568318e449bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_Button_navControl&quot;)/span[@class=&quot;t-Header-controlsIcon&quot;]</value>
      <webElementGuid>dcfae628-7e79-4018-a65b-1dafc8ca73fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='t_Button_navControl']/span</value>
      <webElementGuid>0e9e1165-a241-4e25-9ef3-d69572b32111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>a22a1aa4-f2b7-4c6e-ae3b-45d827c44246</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
