<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>d24cfa3d-938d-4cd6-af63-d766fe60f0c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Add/Edit Donor&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>41cb4df1-840c-41b2-a1ad-19941b7e8c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/ambay_valley/donor-receipt-generation177/add-edit-donor?clear=3&amp;session=11231303033025&amp;cs=3pNrjpdN2vzRWQIn_8wu6XeyNgEy9NAWdxSZrxNSxaDGeiOaE8KhHTJMpEp5zH9qTDkPhL4AGc3tDgOBadIl2Qg&amp;dialogCs=KWeHZpZMkGtxCNCEPWPHMZKAt4LO9j-l4JKpk5_fswGAVmOyLYmfW2lNBV_rloyI_TeabTfHvToFkV5Y7zKsvQ</value>
      <webElementGuid>3368ce78-7eb5-439c-9e07-9755f8aad99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add/Edit Donor</value>
      <webElementGuid>3d3a73c4-2ba7-4200-a850-707773aeadaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>bdd5bd57-0585-41a0-ac2a-25338afca2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>308fdf00-a5c7-4233-aab0-7e8049757f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>8f43dd32-1c96-4c26-a4b9-3eae8b51fa47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>c8ea22ac-b0ca-4962-b727-88e71e70f86e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>e74d2fff-dec5-4a53-a7a4-2f952d526b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>77c59419-cc97-480b-a31d-72ee38ede08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/ambay_valley/donor-receipt-generation177/add-edit-donor?clear=3&amp;session=11231303033025&amp;cs=3pNrjpdN2vzRWQIn_8wu6XeyNgEy9NAWdxSZrxNSxaDGeiOaE8KhHTJMpEp5zH9qTDkPhL4AGc3tDgOBadIl2Qg&amp;dialogCs=KWeHZpZMkGtxCNCEPWPHMZKAt4LO9j-l4JKpk5_fswGAVmOyLYmfW2lNBV_rloyI_TeabTfHvToFkV5Y7zKsvQ' and @title = 'Add/Edit Donor']</value>
      <webElementGuid>d30489b5-2371-4510-a13d-7f6acd53aa3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
