<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pan Number_P3_PAN_NUMBER</name>
   <tag></tag>
   <elementGuidId>641e32f3-dc26-4ebe-9668-0d3cc6191b8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P3_PAN_NUMBER']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P3_PAN_NUMBER</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24b3d3d5-bd7f-4b54-afa3-5d3a88612626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0bdc51b-05cd-4034-80f1-38edf75813a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_PAN_NUMBER</value>
      <webElementGuid>d3f85061-4d4a-496b-b70e-898c67c518f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P3_PAN_NUMBER</value>
      <webElementGuid>df153af9-c2e1-4420-9efb-69d6198fdafe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>2bc95b6c-66df-47b0-8dee-c85f1500a4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>f781bbe5-d0cf-4416-9046-24e93b690863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>48ea3384-3c81-4d4e-8f35-6dd6da9c236d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>69c2732e-7abf-4785-8af4-9691eaa0f641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-text-case</name>
      <type>Main</type>
      <value>UPPER</value>
      <webElementGuid>ab59f975-d67a-42e0-8e5d-336d342d4d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_PAN_NUMBER&quot;)</value>
      <webElementGuid>ddf572bc-9bf9-42a8-b280-6992d1452b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Donor Adding(Donor Receipt)OLD/Page_Donor Details/iframe</value>
      <webElementGuid>b4c1776c-6a5c-4ad6-82a4-08f24897a0d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P3_PAN_NUMBER']</value>
      <webElementGuid>2882f9ad-7dd9-4244-92d4-5b14f55739d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_PAN_NUMBER_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>7917ff76-4b4b-4c89-b4ec-b5d9ec17a0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/input</value>
      <webElementGuid>bddede40-e7f6-4069-88ee-11e22cf8d5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P3_PAN_NUMBER' and @name = 'P3_PAN_NUMBER']</value>
      <webElementGuid>2fae1e20-2b50-4735-8eb4-2a1f97621683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
