<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Id_P3_EMAIL_ID</name>
   <tag></tag>
   <elementGuidId>550aefd2-bc3d-4d90-baeb-631ca8215ff3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P3_EMAIL_ID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P3_EMAIL_ID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d04365fd-074e-491e-b6a1-df468f713576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4440343-0500-453a-b758-6f28f6ce40ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P3_EMAIL_ID</value>
      <webElementGuid>d4a52d69-10ab-4277-b527-326912dc2961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P3_EMAIL_ID</value>
      <webElementGuid>c2a2af43-9cb4-4cf5-9ee7-4e7af8cf0b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>d388d80b-da98-491c-a225-fbc4fa720c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>554958c2-3244-4171-a3f6-eb7a6807b00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3858900d-02d0-417a-aaf8-6126c3611899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trim-spaces</name>
      <type>Main</type>
      <value>NONE</value>
      <webElementGuid>b67b105d-dc15-445a-a666-f1cc27f6fe3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P3_EMAIL_ID&quot;)</value>
      <webElementGuid>c6afadc2-b59c-463e-9847-f45d6af9385f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Donor Adding(Donor Receipt)OLD/Page_Donor Details/iframe</value>
      <webElementGuid>e6c4090d-37bb-43b6-8191-1ecb7131f4eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P3_EMAIL_ID']</value>
      <webElementGuid>cf297640-590a-4208-a6a8-415f1665ca36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P3_EMAIL_ID_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>8b899a0e-78a1-4489-bfbb-8566d7d482c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>66b42f35-0300-4ab7-ad61-6a3ba491761f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P3_EMAIL_ID' and @name = 'P3_EMAIL_ID']</value>
      <webElementGuid>c7fb09aa-d179-411e-a177-2fe9aef3bbbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
