<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>2573d8c3-7835-46bf-898f-6d4b72418344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Potential Sponsor&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='apex_dialog_1']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>be0c4136-3c2f-4091-acc5-314de794658e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ords/r/coordination/progmgt173184/potential-sponsor?p23_state=17&amp;p23_plan=91&amp;p23_project=3&amp;p23_district=407&amp;p23_meeting_id=162&amp;clear=311&amp;session=9485208309336&amp;cs=1TFCMlaJndapsGHbVuOQd9LE9v3yCkIAEh1FUY8JR2UxLra1YkSgTQVPWcp-cqalI6aXCwcneT7l75ai7CS6V7w&amp;dialogCs=8SSbJVACaC3O-Ns4NcUIpIMeXM7FsBHoXlSfqRt9OZzMK_xADb8oarIE7Bt7PKDqVuSjAxKTEsFCzKR-uWjhow</value>
      <webElementGuid>e0786648-9139-408d-97a7-6ba3cb319718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Potential Sponsor</value>
      <webElementGuid>1404857a-691a-42fe-80e5-88951c83a985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>555dd967-cc3c-4783-8475-20505fdbc80c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>89a6ed00-c385-47c5-9c32-6278f4540aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>891defc7-dd2b-4e97-bd58-d7eb365211cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;apex_dialog_1&quot;)/iframe[1]</value>
      <webElementGuid>91197ec6-bb87-430a-92bf-09b5638367d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apex_dialog_1']/iframe</value>
      <webElementGuid>583730a3-1309-4229-97c5-7041cce44da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f9f36bcf-c3de-409c-b0bb-e65106b89dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/ords/r/coordination/progmgt173184/potential-sponsor?p23_state=17&amp;p23_plan=91&amp;p23_project=3&amp;p23_district=407&amp;p23_meeting_id=162&amp;clear=311&amp;session=9485208309336&amp;cs=1TFCMlaJndapsGHbVuOQd9LE9v3yCkIAEh1FUY8JR2UxLra1YkSgTQVPWcp-cqalI6aXCwcneT7l75ai7CS6V7w&amp;dialogCs=8SSbJVACaC3O-Ns4NcUIpIMeXM7FsBHoXlSfqRt9OZzMK_xADb8oarIE7Bt7PKDqVuSjAxKTEsFCzKR-uWjhow' and @title = 'Potential Sponsor']</value>
      <webElementGuid>4a386f9d-419d-4efb-bf0c-d29c3ce3c2c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
