<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Venue_P23_VENUE</name>
   <tag></tag>
   <elementGuidId>da4d1c6c-7b13-43f1-bed6-b5f1d3c5f85c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P23_VENUE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P23_VENUE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1578099c-8da3-45cb-b517-39a550bab907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8661f8d9-e99f-4069-b587-a942d6225c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P23_VENUE</value>
      <webElementGuid>df8d008e-cb4c-4bd8-ac1d-dd81e8f94818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P23_VENUE</value>
      <webElementGuid>fb264f23-ac5f-4e66-977c-c63fca0bef8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>98db4161-87f3-40dd-bcb3-23258f0231cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>e5e34fc5-2f0a-4a0a-be02-30e6a3ee1c59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>d0d1b7ba-ae56-46f9-be90-fb85863a9be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P23_VENUE&quot;)</value>
      <webElementGuid>0c7348fc-28c7-49b0-9fd4-16b96a582848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Potential sponser (Meeting coordinator)/Page_View Meetings/iframe</value>
      <webElementGuid>a1373820-83ac-4289-93ec-d8f13dd99e18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P23_VENUE']</value>
      <webElementGuid>2c9b9489-a2a4-49c5-8f19-ab0453fb3293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P23_VENUE_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>1313b636-648d-419b-a252-b82faae57303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>c5be22bb-9169-4d2c-8934-f90480db8a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P23_VENUE' and @name = 'P23_VENUE']</value>
      <webElementGuid>6c1fdcdf-9b4f-4494-884e-dacc67f009d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
