<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P23_POT_SPO_MOBILE_NO</name>
   <tag></tag>
   <elementGuidId>2b663867-84cd-4210-a331-bfd55d237c7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P23_POT_SPO_MOBILE_NO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P23_POT_SPO_MOBILE_NO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29776078-3c01-46ca-a9b2-47eeded596e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7866d6b4-5c0a-4bf3-82c4-50c7df6674b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P23_POT_SPO_MOBILE_NO</value>
      <webElementGuid>5678968b-5416-4f25-929f-18f63edee077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P23_POT_SPO_MOBILE_NO</value>
      <webElementGuid>dc64b53b-c790-46ec-b745-0980304415ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number</value>
      <webElementGuid>75275e3d-1af3-4a23-96fa-e3e3022417f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>8acf7f58-071c-4b4f-91d5-67d034a38de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e280c745-1167-4239-b44b-ace6d8b9f527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>e13f8b2d-9e0c-43a9-8957-895adf578363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P23_POT_SPO_MOBILE_NO&quot;)</value>
      <webElementGuid>c9bd0842-e73f-4a6e-8953-c07c5255c4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Potential sponser (Meeting coordinator)/Page_View Meetings/iframe</value>
      <webElementGuid>71c2c2da-6ce0-4d0b-ab74-22e00a78106e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P23_POT_SPO_MOBILE_NO']</value>
      <webElementGuid>3b86b8c4-513f-415e-b3db-1a7cfa09901c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P23_POT_SPO_MOBILE_NO_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>97025d31-e79b-42d6-849a-5a9fda70f1dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>35e8fd39-aa33-4d5d-957f-556e3cabda36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P23_POT_SPO_MOBILE_NO' and @name = 'P23_POT_SPO_MOBILE_NO']</value>
      <webElementGuid>99667040-4157-4902-b8c8-cd06a9fa17f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
