<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P23_EMAIL_ID</name>
   <tag></tag>
   <elementGuidId>ce699a24-80b3-43f6-a07b-ac43b956475a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P23_EMAIL_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P23_EMAIL_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3db0c63f-8308-41e6-a584-168a90285ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b7975246-c71e-4b9e-a164-9c3d366fe677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P23_EMAIL_ID</value>
      <webElementGuid>8e40224c-23a2-4384-ae79-d2baced21100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P23_EMAIL_ID</value>
      <webElementGuid>abb842dc-1906-48a5-84be-837af65ab9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>fdffb35a-5972-4b92-a942-51495ec8728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>dce84db9-9f35-4f55-9d99-239a1b2a57ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>d27bdcf9-467a-4033-86b8-3992aee3da6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P23_EMAIL_ID&quot;)</value>
      <webElementGuid>40566501-7438-4e2d-8f39-0e51d763452f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Potential sponser (Meeting coordinator)/Page_View Meetings/iframe</value>
      <webElementGuid>aeba52ac-d0f3-4ad0-8e9c-4f729cd40c15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P23_EMAIL_ID']</value>
      <webElementGuid>4c580554-d00f-40a9-a8be-5fead039b42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P23_EMAIL_ID_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>ccc40f6b-ea5e-4892-9c8a-1ec89fc462c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/input</value>
      <webElementGuid>a0ec3e25-c1db-40f5-979c-912b753c64b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P23_EMAIL_ID' and @name = 'P23_EMAIL_ID']</value>
      <webElementGuid>cb41e1db-3a42-48b2-8c99-f3b4336404ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
