<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P23_CON_PERS_MOBILE_NO</name>
   <tag></tag>
   <elementGuidId>c3571b4e-0bdf-4ee4-8f81-f33025d76ee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P23_CON_PERS_MOBILE_NO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P23_CON_PERS_MOBILE_NO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d131a53d-e063-47c3-b8db-f2aea57b902e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9b25097-1d93-4402-b477-284d2a00298d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P23_CON_PERS_MOBILE_NO</value>
      <webElementGuid>aec322c8-21c5-4269-994f-af3f8d77c7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P23_CON_PERS_MOBILE_NO</value>
      <webElementGuid>10f99975-9882-45bb-b58f-a59a291d16ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>number_field apex-item-text apex-item-number</value>
      <webElementGuid>856f463d-7530-413c-ace3-2f22720b2d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>32</value>
      <webElementGuid>efc5d808-f036-457d-82ac-8be886c04df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f18c6c05-28a7-4ff7-84ae-4bebfbfb5310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>ee9cb831-1177-42ed-b866-9d2fe0333dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P23_CON_PERS_MOBILE_NO&quot;)</value>
      <webElementGuid>a342283b-16f3-478e-b1d1-005e49503015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Potential sponser (Meeting coordinator)/Page_View Meetings/iframe</value>
      <webElementGuid>fc0e8461-ae1b-4dcf-91f1-117fd231a74e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P23_CON_PERS_MOBILE_NO']</value>
      <webElementGuid>bbf753ce-7c5d-4fb3-9c54-4e06aec4e59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P23_CON_PERS_MOBILE_NO_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>a930e2f4-77cf-49a7-9ac3-f11b64edcced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>049d22cd-09ee-4aab-bafb-eadea14a060a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P23_CON_PERS_MOBILE_NO' and @name = 'P23_CON_PERS_MOBILE_NO']</value>
      <webElementGuid>aec0e060-c3e8-4492-b612-fce934292210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
