<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P23_OCCUPATION</name>
   <tag></tag>
   <elementGuidId>a8feadb9-e3a4-445a-812a-352bf4305bf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P23_OCCUPATION</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P23_OCCUPATION']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c12d1d9-089c-40ae-b4cb-73e8fba3ce00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5e91125-1dd3-4178-a4df-4dad79a4067f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P23_OCCUPATION</value>
      <webElementGuid>622edb05-0817-4fc4-9b8a-e4c0d44dd731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P23_OCCUPATION</value>
      <webElementGuid>da0744c5-15e8-4d34-aa87-fd868d57aaad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>d27cc515-2971-47ee-80a8-bee331dd369f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>851e2f21-882f-42b3-9eae-ba9bf772a20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>1b15ea9f-5051-47bd-92d3-b9eca30cea31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P23_OCCUPATION&quot;)</value>
      <webElementGuid>60923f7e-c505-4854-95b6-fb08ed55907a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Potential sponser (Meeting coordinator)/Page_View Meetings/iframe</value>
      <webElementGuid>45d75788-4b9f-40ae-ab52-caf43e086b36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P23_OCCUPATION']</value>
      <webElementGuid>143f8ce9-e51a-4bd5-bc43-0cea4639a1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P23_OCCUPATION_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>f8995c94-b021-4ac9-a17b-97b63292966c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>89509329-bc6b-470d-bd7d-08e1c9b917f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P23_OCCUPATION' and @name = 'P23_OCCUPATION']</value>
      <webElementGuid>eadb0ed8-37e7-44aa-bfa4-b61c9dd42027</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
