<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Value Required)_P23_CONNECT_PERSON_NAME</name>
   <tag></tag>
   <elementGuidId>822fec8e-8d28-4dee-a4d8-22d5fa524c41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#P23_CONNECT_PERSON_NAME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='P23_CONNECT_PERSON_NAME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52881cab-5dac-4e4d-9f2b-c3d81db6c19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>63ffb446-17e5-4232-bb9d-7e5d717177c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P23_CONNECT_PERSON_NAME</value>
      <webElementGuid>de9e1b0a-caaa-4718-8007-0e249f4ed838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>P23_CONNECT_PERSON_NAME</value>
      <webElementGuid>a34f4c1d-80ea-4e08-ab5f-ca8ec391597d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text_field apex-item-text</value>
      <webElementGuid>1498bd49-21c3-40e6-a821-ae771c085617</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>a914111d-b409-4df4-9a41-b7b5ff7ec6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>300</value>
      <webElementGuid>4b01d46a-1513-439d-852d-e155c2d3b919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P23_CONNECT_PERSON_NAME&quot;)</value>
      <webElementGuid>e0ee6bb4-fdc9-4bcd-83fe-989460a1cf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Potential sponser (Meeting coordinator)/Page_View Meetings/iframe</value>
      <webElementGuid>db8ea679-437b-4d3f-8bde-03d73a61857f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P23_CONNECT_PERSON_NAME']</value>
      <webElementGuid>31613ed5-e6f4-48a9-8f16-2385a1125b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P23_CONNECT_PERSON_NAME_CONTAINER']/div[2]/div/input</value>
      <webElementGuid>b4078454-b6ed-4236-ad59-bfa77c6b05ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>9cc78878-dc07-48eb-b557-cdd4e5df3720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'P23_CONNECT_PERSON_NAME' and @name = 'P23_CONNECT_PERSON_NAME']</value>
      <webElementGuid>d704fe55-8bef-4e94-b73d-3f6d612d7771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
